-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_passes]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_passes

/-- [core::mem::drop]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 1000:0-1002:24
    Name pattern: [core::mem::drop]
    Visibility: public -/
@[rust_fun "core::mem::drop"]
axiom core.mem.drop {T : Type} : T → Result Unit

/-- [lt_stateful_passes::LockError]
    Source: 'tests/src/lt-stateful-passes.rs', lines 85:0-87:1
    Visibility: public -/
@[discriminant isize]
inductive LockError where
| Busy : LockError

/-- [lt_stateful_passes::{impl core::fmt::Debug for lt_stateful_passes::LockError}::fmt]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 84:9-84:14
    Visibility: public -/
def LockError.Insts.CoreFmtDebug.fmt
  (self : LockError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  core.fmt.Formatter.write_str f (toStr "Busy")

/-- Trait implementation: [lt_stateful_passes::{impl core::fmt::Debug for lt_stateful_passes::LockError}]
    Source: 'tests/src/lt-stateful-passes.rs', lines 84:9-84:14 -/
@[reducible]
def LockError.Insts.CoreFmtDebug : core.fmt.Debug LockError := {
  fmt := LockError.Insts.CoreFmtDebug.fmt
}

/-- [lt_stateful_passes::Lock]
    Source: 'tests/src/lt-stateful-passes.rs', lines 93:0-95:1
    Visibility: public -/
axiom Lock : Type

/-- [lt_stateful_passes::{lt_stateful_passes::Lock}::new]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 99:4-101:5
    Visibility: public -/
axiom Lock.new : Result Lock

/-- [lt_stateful_passes::Guard]
    Source: 'tests/src/lt-stateful-passes.rs', lines 150:0-152:1
    Visibility: public -/
axiom Guard : Type

/-- [lt_stateful_passes::{lt_stateful_passes::Lock}::acquire]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 105:4-107:5
    Visibility: public -/
axiom Lock.acquire : Lock → Result Guard

/-- [lt_stateful_passes::AutoGuard]
    Source: 'tests/src/lt-stateful-passes.rs', lines 178:0-180:1
    Visibility: public -/
axiom AutoGuard : Type

/-- [lt_stateful_passes::{lt_stateful_passes::Lock}::acquire_auto]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 113:4-115:5
    Visibility: public -/
axiom Lock.acquire_auto : Lock → Result AutoGuard

/-- [lt_stateful_passes::{lt_stateful_passes::Lock}::try_acquire]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 119:4-121:5
    Visibility: public -/
axiom Lock.try_acquire : Lock → Result (core.result.Result Guard LockError)

/-- [lt_stateful_passes::{lt_stateful_passes::Lock}::acquire_pair]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 126:4-128:5
    Visibility: public -/
axiom Lock.acquire_pair : Lock → Result (Guard × Std.I32)

/-- [lt_stateful_passes::{lt_stateful_passes::Lock}::release]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 133:4-135:5
    Visibility: public -/
axiom Lock.release : Lock → Guard → Result Unit

/-- [lt_stateful_passes::{lt_stateful_passes::Lock}::touch_unit]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 140:4-142:5
    Visibility: public -/
axiom Lock.touch_unit : Lock → Result Unit

/-- [lt_stateful_passes::{lt_stateful_passes::Guard<'a>}::touch]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 159:4-161:5
    Visibility: public -/
axiom Guard.touch : Guard → Result (Std.I32 × (Std.I32 → Guard))

/-- [lt_stateful_passes::{lt_stateful_passes::Guard<'a>}::get_value]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 164:4-166:5
    Visibility: public -/
axiom Guard.get_value : Guard → Result Std.I32

/-- [lt_stateful_passes::{lt_stateful_passes::Guard<'a>}::set_value]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 169:4-171:5
    Visibility: public -/
axiom Guard.set_value : Guard → Std.I32 → Result Guard

/-- [lt_stateful_passes::{impl core::ops::drop::Drop for lt_stateful_passes::AutoGuard<'a>}::drop]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 184:4-186:5
    Visibility: public -/
axiom AutoGuard.Insts.CoreOpsDropDrop.drop : AutoGuard → Result AutoGuard

/-- Trait implementation: [lt_stateful_passes::{impl core::ops::drop::Drop for lt_stateful_passes::AutoGuard<'a>}]
    Source: 'tests/src/lt-stateful-passes.rs', lines 182:0-187:1 -/
@[reducible]
def AutoGuard.Insts.CoreOpsDropDrop : core.ops.drop.Drop AutoGuard := {
  drop := AutoGuard.Insts.CoreOpsDropDrop.drop
}

/-- [lt_stateful_passes::Arc]
    Source: 'tests/src/lt-stateful-passes.rs', lines 194:0-196:1
    Visibility: public -/
axiom Arc (T : Type) : Type

/-- [lt_stateful_passes::{impl core::ops::drop::Drop for lt_stateful_passes::Arc<T>}::drop]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 217:4-219:5
    Visibility: public -/
axiom Arc.Insts.CoreOpsDropDrop.drop {T : Type} : Arc T → Result (Arc T)

/-- [lt_stateful_passes::{lt_stateful_passes::Arc<T>}::new]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 200:4-202:5
    Visibility: public -/
axiom Arc.new {T : Type} : T → Result (Arc T)

/-- [lt_stateful_passes::{lt_stateful_passes::Arc<T>}::clone_arc]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 205:4-207:5
    Visibility: public -/
axiom Arc.clone_arc {T : Type} : Arc T → Result (Arc T)

/-- [lt_stateful_passes::{lt_stateful_passes::Arc<T>}::get]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 210:4-212:5
    Visibility: public -/
axiom Arc.get {T : Type} : Arc T → Result T

/-- Trait implementation: [lt_stateful_passes::{impl core::ops::drop::Drop for lt_stateful_passes::Arc<T>}]
    Source: 'tests/src/lt-stateful-passes.rs', lines 215:0-220:1 -/
@[reducible]
def Arc.Insts.CoreOpsDropDrop (T : Type) : core.ops.drop.Drop (Arc T) := {
  drop := Arc.Insts.CoreOpsDropDrop.drop
}

/-- [lt_stateful_passes::maybe_alias_effect]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 227:0-229:1
    Visibility: public -/
axiom maybe_alias_effect : Std.I32 → Std.I32 → Result (Std.I32 × Std.I32)

/-- [lt_stateful_passes::identity_mut]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 237:0-239:1
    Visibility: public -/
def identity_mut
  (x : Std.I32) : Result (Std.I32 × (Std.I32 → Std.I32)) := do
  ok (x, fun x1 => x1)

/-- [lt_stateful_passes::two_identical_acquires_no_cse]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 256:0-261:1
    Visibility: public -/
def two_identical_acquires_no_cse (l : Lock) : Result Unit := do
  let g1 ← Lock.acquire l
  Lock.release l g1
  Lock.release l g1

/-- [lt_stateful_passes::two_identical_clones_no_cse]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 271:0-276:1
    Visibility: public -/
def two_identical_clones_no_cse (a : Arc Std.I32) : Result Unit := do
  let b1 ← Arc.clone_arc a
  core.mem.drop b1
  core.mem.drop b1

/-- [lt_stateful_passes::three_identical_acquires_no_cse]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 288:0-295:1
    Visibility: public -/
def three_identical_acquires_no_cse (l : Lock) : Result Unit := do
  let g1 ← Lock.acquire l
  Lock.release l g1
  Lock.release l g1
  Lock.release l g1

/-- [lt_stateful_passes::two_identical_releases_no_cse]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 309:0-314:1
    Visibility: public -/
def two_identical_releases_no_cse (l : Lock) : Result Unit := do
  let g1 ← Lock.acquire l
  Lock.release l g1
  Lock.release l g1

/-- [lt_stateful_passes::infallible_unit_effect_bound_underscore_not_dced]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 330:0-332:1
    Visibility: public -/
def infallible_unit_effect_bound_underscore_not_dced
  (l : Lock) : Result Unit := do
  Lock.touch_unit l

/-- [lt_stateful_passes::unused_arc_must_drop]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 341:0-343:1
    Visibility: public -/
def unused_arc_must_drop (x : Std.I32) : Result Unit := do
  let _ ← Arc.new x
  ok ()

/-- [lt_stateful_passes::unused_guard_must_release]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 351:0-353:1
    Visibility: public -/
def unused_guard_must_release (l : Lock) : Result Unit := do
  let _ ← Lock.acquire_auto l
  ok ()

/-- [lt_stateful_passes::identity_setter_still_runs]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 362:0-365:1
    Visibility: public -/
def identity_setter_still_runs (g : Guard) : Result Guard := do
  let v ← Guard.get_value g
  Guard.set_value g v

/-- [lt_stateful_passes::repeated_deref_mut_preserves_order]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 370:0-375:1
    Visibility: public -/
def repeated_deref_mut_preserves_order (g : Guard) : Result Guard := do
  let (r1, touch_back) ← Guard.touch g
  let r11 ← r1 + 1#i32
  let g1 := touch_back r11
  let (r2, touch_back1) ← Guard.touch g1
  let r21 ← r2 + 2#i32
  ok (touch_back1 r21)

/-- [lt_stateful_passes::beta_reduced_unit_closure_once::closure]
    Source: 'tests/src/lt-stateful-passes.rs', lines 389:21-392:5 -/
@[reducible]
def beta_reduced_unit_closure_once.closure := Lock

/-- [lt_stateful_passes::beta_reduced_unit_closure_once::{impl core::ops::function::Fn<(bool,), bool> for lt_stateful_passes::beta_reduced_unit_closure_once::closure<'_0>}::call]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 389:21-392:5 -/
def
  beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnTupleBoolBool.call
  (c : beta_reduced_unit_closure_once.closure) (tupled_args : Bool) :
  Result Bool
  := do
  Lock.touch_unit c
  ok tupled_args

/-- [lt_stateful_passes::beta_reduced_unit_closure_once]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 388:0-394:1
    Visibility: public -/
def beta_reduced_unit_closure_once (l : Lock) : Result Unit := do
  let _ ←
    beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnTupleBoolBool.call
      l false
  ok ()

/-- [lt_stateful_passes::beta_reduced_unit_closure_once::{impl core::ops::function::FnMut<(bool,), bool> for lt_stateful_passes::beta_reduced_unit_closure_once::closure<'_0>}::call_mut]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 389:21-392:5 -/
def
  beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnMutTupleBoolBool.call_mut
  (state : beta_reduced_unit_closure_once.closure) (args : Bool) :
  Result (Bool × beta_reduced_unit_closure_once.closure)
  := do
  let b ←
    beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnTupleBoolBool.call
      state args
  ok (b, state)

/-- [lt_stateful_passes::beta_reduced_unit_closure_once::{impl core::ops::function::FnOnce<(bool,), bool> for lt_stateful_passes::beta_reduced_unit_closure_once::closure<'_0>}::call_once]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 389:21-392:5 -/
def
  beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool.call_once
  (c : beta_reduced_unit_closure_once.closure) (b : Bool) : Result Bool := do
  let (b1, _) ←
    beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnMutTupleBoolBool.call_mut
      c b
  ok b1

/-- Trait implementation: [lt_stateful_passes::beta_reduced_unit_closure_once::{impl core::ops::function::FnOnce<(bool,), bool> for lt_stateful_passes::beta_reduced_unit_closure_once::closure<'_0>}]
    Source: 'tests/src/lt-stateful-passes.rs', lines 389:21-392:5 -/
@[reducible]
def
  beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool
  : core.ops.function.FnOnce beta_reduced_unit_closure_once.closure Bool Bool
  := {
  call_once :=
    beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool.call_once
}

/-- Trait implementation: [lt_stateful_passes::beta_reduced_unit_closure_once::{impl core::ops::function::FnMut<(bool,), bool> for lt_stateful_passes::beta_reduced_unit_closure_once::closure<'_0>}]
    Source: 'tests/src/lt-stateful-passes.rs', lines 389:21-392:5 -/
@[reducible]
def
  beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnMutTupleBoolBool
  : core.ops.function.FnMut beta_reduced_unit_closure_once.closure Bool Bool
  := {
  FnOnceInst :=
    beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool
  call_mut :=
    beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnMutTupleBoolBool.call_mut
}

/-- Trait implementation: [lt_stateful_passes::beta_reduced_unit_closure_once::{impl core::ops::function::Fn<(bool,), bool> for lt_stateful_passes::beta_reduced_unit_closure_once::closure<'_0>}]
    Source: 'tests/src/lt-stateful-passes.rs', lines 389:21-392:5 -/
@[reducible]
def beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnTupleBoolBool
  : core.ops.function.Fn beta_reduced_unit_closure_once.closure Bool Bool := {
  FnMutInst :=
    beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnMutTupleBoolBool
  call :=
    beta_reduced_unit_closure_once.closure.Insts.CoreOpsFunctionFnTupleBoolBool.call
}

/-- [lt_stateful_passes::beta_reduced_unit_closure_twice::closure]
    Source: 'tests/src/lt-stateful-passes.rs', lines 401:22-404:5 -/
@[reducible]
def beta_reduced_unit_closure_twice.closure := Lock

/-- [lt_stateful_passes::beta_reduced_unit_closure_twice::{impl core::ops::function::Fn<(bool,), bool> for lt_stateful_passes::beta_reduced_unit_closure_twice::closure<'_0>}::call]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 401:22-404:5 -/
def
  beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnTupleBoolBool.call
  (c : beta_reduced_unit_closure_twice.closure) (tupled_args : Bool) :
  Result Bool
  := do
  Lock.touch_unit c
  ok tupled_args

/-- [lt_stateful_passes::beta_reduced_unit_closure_twice]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 400:0-407:1
    Visibility: public -/
def beta_reduced_unit_closure_twice (l : Lock) : Result Unit := do
  let _ ←
    beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnTupleBoolBool.call
      l false
  let _ ←
    beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnTupleBoolBool.call
      l true
  ok ()

/-- [lt_stateful_passes::beta_reduced_unit_closure_twice::{impl core::ops::function::FnMut<(bool,), bool> for lt_stateful_passes::beta_reduced_unit_closure_twice::closure<'_0>}::call_mut]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 401:22-404:5 -/
def
  beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnMutTupleBoolBool.call_mut
  (state : beta_reduced_unit_closure_twice.closure) (args : Bool) :
  Result (Bool × beta_reduced_unit_closure_twice.closure)
  := do
  let b ←
    beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnTupleBoolBool.call
      state args
  ok (b, state)

/-- [lt_stateful_passes::beta_reduced_unit_closure_twice::{impl core::ops::function::FnOnce<(bool,), bool> for lt_stateful_passes::beta_reduced_unit_closure_twice::closure<'_0>}::call_once]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 401:22-404:5 -/
def
  beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool.call_once
  (c : beta_reduced_unit_closure_twice.closure) (b : Bool) : Result Bool := do
  let (b1, _) ←
    beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnMutTupleBoolBool.call_mut
      c b
  ok b1

/-- Trait implementation: [lt_stateful_passes::beta_reduced_unit_closure_twice::{impl core::ops::function::FnOnce<(bool,), bool> for lt_stateful_passes::beta_reduced_unit_closure_twice::closure<'_0>}]
    Source: 'tests/src/lt-stateful-passes.rs', lines 401:22-404:5 -/
@[reducible]
def
  beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool
  : core.ops.function.FnOnce beta_reduced_unit_closure_twice.closure Bool Bool
  := {
  call_once :=
    beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool.call_once
}

/-- Trait implementation: [lt_stateful_passes::beta_reduced_unit_closure_twice::{impl core::ops::function::FnMut<(bool,), bool> for lt_stateful_passes::beta_reduced_unit_closure_twice::closure<'_0>}]
    Source: 'tests/src/lt-stateful-passes.rs', lines 401:22-404:5 -/
@[reducible]
def
  beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnMutTupleBoolBool
  : core.ops.function.FnMut beta_reduced_unit_closure_twice.closure Bool Bool
  := {
  FnOnceInst :=
    beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool
  call_mut :=
    beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnMutTupleBoolBool.call_mut
}

/-- Trait implementation: [lt_stateful_passes::beta_reduced_unit_closure_twice::{impl core::ops::function::Fn<(bool,), bool> for lt_stateful_passes::beta_reduced_unit_closure_twice::closure<'_0>}]
    Source: 'tests/src/lt-stateful-passes.rs', lines 401:22-404:5 -/
@[reducible]
def
  beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnTupleBoolBool
  : core.ops.function.Fn beta_reduced_unit_closure_twice.closure Bool Bool := {
  FnMutInst :=
    beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnMutTupleBoolBool
  call :=
    beta_reduced_unit_closure_twice.closure.Insts.CoreOpsFunctionFnTupleBoolBool.call
}

/-- [lt_stateful_passes::if_branches_effects_remain_conditional]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 428:0-436:1
    Visibility: public -/
def if_branches_effects_remain_conditional
  (l : Lock) (flag : Bool) : Result Unit := do
  if flag
  then let g ← Lock.acquire l
       Lock.release l g
  else let g ← Lock.acquire l
       Lock.release l g

/-- [lt_stateful_passes::if_branches_distinct_effects_not_conflated]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 445:0-453:1
    Visibility: public -/
def if_branches_distinct_effects_not_conflated
  (l : Lock) (a : Arc Std.I32) (flag : Bool) : Result Unit := do
  if flag
  then let g ← Lock.acquire l
       Lock.release l g
  else let b ← Arc.clone_arc a
       core.mem.drop b

/-- [lt_stateful_passes::dead_branch_one_arm_pure]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 458:0-463:1
    Visibility: public -/
def dead_branch_one_arm_pure (l : Lock) (flag : Bool) : Result Unit := do
  if flag
  then let g ← Lock.acquire l
       Lock.release l g
  else ok ()

/-- [lt_stateful_passes::nested_if_let_then_match_effect_order]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 471:0-484:1
    Visibility: public -/
def nested_if_let_then_match_effect_order
  (l : Lock) (opt : Option Std.I32) : Result Std.I32 := do
  match opt with
  | none => ok (-1)#i32
  | some v =>
    match v with
    | 0#iscalar => let g ← Lock.acquire l
                   Lock.release l g
                   ok 0#i32
    | _ => ok v

/-- [lt_stateful_passes::tuple_decomposition_single_eval]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 494:0-498:1
    Visibility: public -/
def tuple_decomposition_single_eval (l : Lock) : Result Std.I32 := do
  let (g, code) ← Lock.acquire_pair l
  Lock.release l g
  ok code

/-- [lt_stateful_passes::nested_result_shaped_effect]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 503:0-511:1
    Visibility: public -/
def nested_result_shaped_effect (l : Lock) : Result Std.I32 := do
  let r ← Lock.try_acquire l
  match r with
  | core.result.Result.Ok g => Lock.release l g
                               ok 1#i32
  | core.result.Result.Err _ => ok 0#i32

/-- [lt_stateful_passes::identical_effects_tuple_no_cse]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 522:0-527:1
    Visibility: public -/
def identical_effects_tuple_no_cse (l : Lock) : Result Std.I32 := do
  let g1 ← Lock.acquire l
  Lock.release l g1
  Lock.release l g1
  ok 0#i32

/-- [lt_stateful_passes::different_binding_shapes_preserve_effects]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 536:0-546:1
    Visibility: public -/
def different_binding_shapes_preserve_effects (l : Lock) : Result Std.I32 := do
  let g1 ← Lock.acquire l
  Lock.release l g1
  let (g2, code) ← Lock.acquire_pair l
  Lock.release l g2
  let r ← Lock.try_acquire l
  match r with
  | core.result.Result.Ok g3 => Lock.release l g3
                                ok code
  | core.result.Result.Err _ => ok code

/-- [lt_stateful_passes::effectful_call_returns_unit]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 555:0-557:1
    Visibility: public -/
def effectful_call_returns_unit (l : Lock) : Result Unit := do
  Lock.touch_unit l

/-- [lt_stateful_passes::effectful_backward_no_data_output]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 564:0-567:1
    Visibility: public -/
def effectful_backward_no_data_output (g : Guard) : Result Guard := do
  let (_, touch_back) ← Guard.touch g
  ok (touch_back 42#i32)

/-- [lt_stateful_passes::pure_and_effectful_interleaved]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 577:0-583:1
    Visibility: public -/
def pure_and_effectful_interleaved
  (l : Lock) (x : Std.I32) : Result Std.I32 := do
  let y ← x + 1#i32
  let g ← Lock.acquire l
  let z ← y * 2#i32
  Lock.release l g
  z + 3#i32

/-- [lt_stateful_passes::lifted_arithmetic_order_repeated_pure_expr]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 591:0-597:1
    Visibility: public -/
def lifted_arithmetic_order_repeated_pure_expr
  (l : Lock) (x : Std.I32) : Result Std.I32 := do
  let i ← x * x
  let p1 ← i + 1#i32
  let g ← Lock.acquire l
  let p2 ← i + 1#i32
  Lock.release l g
  p1 + p2

/-- [lt_stateful_passes::identical_effects_pure_expr_no_cse]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 609:0-611:1
    Visibility: public -/
def identical_effects_pure_expr_no_cse (g : Guard) : Result Std.I32 := do
  let i ← Guard.get_value g
  i + i

/-- [lt_stateful_passes::array_index_projection_no_coalescing]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 629:0-634:1
    Visibility: public -/
def array_index_projection_no_coalescing
  (locks : Slice Lock) (i : Std.Usize) (j : Std.Usize) : Result Unit := do
  let l ← Slice.index_usize locks i
  let gi ← Lock.acquire l
  Lock.release l gi
  let l1 ← Slice.index_usize locks j
  let gj ← Lock.acquire l1
  Lock.release l1 gj

/-- [lt_stateful_passes::array_projection_no_coalescing_same_syntax_diff_index]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 644:0-649:1
    Visibility: public -/
def array_projection_no_coalescing_same_syntax_diff_index
  (locks : Slice Lock) (i : Std.Usize) : Result Unit := do
  let l ← Slice.index_usize locks i
  let g0 ← Lock.acquire l
  Lock.release l g0
  let i1 ← i + 1#usize
  let l1 ← Slice.index_usize locks i1
  let g1 ← Lock.acquire l1
  let l2 ← Slice.index_usize locks i1
  Lock.release l2 g1

/-- [lt_stateful_passes::pure_backward_remains_optimizable]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 661:0-667:1
    Visibility: public -/
def pure_backward_remains_optimizable
  (x : Std.I32) : Result (Std.I32 × Std.I32) := do
  let (r1, identity_mut_back) ← identity_mut x
  let r11 ← r1 + 1#i32
  let x1 := identity_mut_back r11
  let (r2, identity_mut_back1) ← identity_mut x1
  let r21 ← r2 + 1#i32
  let x2 := identity_mut_back1 r21
  ok (x2, x2)

/-- [lt_stateful_passes::real_index_mut_backward_repeated_write]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 680:0-685:1
    Visibility: public -/
def real_index_mut_backward_repeated_write
  (arr : Slice Std.I32) (i : Std.Usize) : Result (Slice Std.I32) := do
  let (r1, index_mut_back) ← Slice.index_mut_usize arr i
  let r11 ← r1 + 1#i32
  let arr1 := index_mut_back r11
  let (r2, index_mut_back1) ← Slice.index_mut_usize arr1 i
  let r21 ← r2 + 2#i32
  ok (index_mut_back1 r21)

/-- [lt_stateful_passes::effect_order_around_opaque_calls]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 695:0-700:1
    Visibility: public -/
def effect_order_around_opaque_calls
  (l : Lock) (a : Arc Std.I32) : Result Unit := do
  let g ← Lock.acquire l
  let b ← Arc.clone_arc a
  Lock.release l g
  core.mem.drop b

/-- [lt_stateful_passes::interleaved_clone_and_lock_effects]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 706:0-711:1
    Visibility: public -/
def interleaved_clone_and_lock_effects
  (l : Lock) (a : Arc Std.I32) : Result Unit := do
  let g ← Lock.acquire l
  let b ← Arc.clone_arc a
  core.mem.drop b
  Lock.release l g

/-- [lt_stateful_passes::no_coalescing_alias_capable_call]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 728:0-731:1
    Visibility: public -/
def no_coalescing_alias_capable_call
  (x : Std.I32) (y : Std.I32) : Result (Std.I32 × Std.I32) := do
  let (x1, y1) ← maybe_alias_effect x y
  maybe_alias_effect x1 y1

/-- [lt_stateful_passes::aliasing_params_swapped_order_no_merge]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 746:0-749:1
    Visibility: public -/
def aliasing_params_swapped_order_no_merge
  (x : Std.I32) (y : Std.I32) : Result (Std.I32 × Std.I32) := do
  let (x1, y1) ← maybe_alias_effect x y
  let (y2, x2) ← maybe_alias_effect y1 x1
  ok (x2, y2)

/-- [lt_stateful_passes::clone_drop_count_observable]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 770:0-775:1
    Visibility: public -/
def clone_drop_count_observable (x : Std.I32) : Result Unit := do
  let a ← Arc.new x
  let b ← Arc.clone_arc a
  core.mem.drop b

/-- [lt_stateful_passes::clone_drop_count_observable_reassign]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 787:0-791:1
    Visibility: public -/
def clone_drop_count_observable_reassign
  (x : Std.I32) (y : Std.I32) : Result Unit := do
  let a ← Arc.new x
  let a1 ← Arc.new y
  let (old, _) := core.mem.replace a a1
  core.mem.drop old

/-- [lt_stateful_passes::guard_replace_no_lost_effects]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 806:0-811:1
    Visibility: public -/
def guard_replace_no_lost_effects (l : Lock) : Result Unit := do
  let g ← Lock.acquire l
  let (old, g1) := core.mem.replace g g
  Lock.release l old
  Lock.release l g1

/-- [lt_stateful_passes::loop_repeated_acquire_release]: loop body 0:
    Source: 'tests/src/lt-stateful-passes.rs', lines 839:4-842:5
    Visibility: public -/
@[rust_loop_body]
def loop_repeated_acquire_release_loop.body
  (l : Lock) (iter : core.ops.range.Range Std.Usize) :
  Result (ControlFlow (core.ops.range.Range Std.Usize) Unit)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done ())
  | some _ => let g ← Lock.acquire l
              Lock.release l g
              ok (cont iter1)

/-- [lt_stateful_passes::loop_repeated_acquire_release]: loop 0:
    Source: 'tests/src/lt-stateful-passes.rs', lines 839:4-842:5
    Visibility: public -/
@[rust_loop]
def loop_repeated_acquire_release_loop
  (iter : core.ops.range.Range Std.Usize) (l : Lock) : Result Unit := do
  loop
    (fun iter1 => loop_repeated_acquire_release_loop.body l iter1)
    iter

/-- [lt_stateful_passes::loop_repeated_acquire_release]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 838:0-843:1
    Visibility: public -/
@[reducible]
def loop_repeated_acquire_release
  (l : Lock) (n : Std.Usize) : Result Unit := do
  loop_repeated_acquire_release_loop { start := 0#usize, «end» := n } l

/-- [lt_stateful_passes::loop_carried_backward_update]: loop body 0:
    Source: 'tests/src/lt-stateful-passes.rs', lines 854:4-857:5
    Visibility: public -/
@[rust_loop_body]
def loop_carried_backward_update_loop.body
  (iter : core.ops.range.Range Std.Usize) (g : Guard) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Guard) Guard)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done g)
  | some _ =>
    let (r, touch_back) ← Guard.touch g
    let r1 ← r + 1#i32
    let g1 := touch_back r1
    ok (cont (iter1, g1))

/-- [lt_stateful_passes::loop_carried_backward_update]: loop 0:
    Source: 'tests/src/lt-stateful-passes.rs', lines 854:4-857:5
    Visibility: public -/
@[rust_loop]
def loop_carried_backward_update_loop
  (iter : core.ops.range.Range Std.Usize) (g : Guard) : Result Guard := do
  loop
    (fun (iter1, g1) => loop_carried_backward_update_loop.body iter1 g1)
    (iter, g)

/-- [lt_stateful_passes::loop_carried_backward_update]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 853:0-858:1
    Visibility: public -/
@[reducible]
def loop_carried_backward_update
  (g : Guard) (n : Std.Usize) : Result Guard := do
  loop_carried_backward_update_loop { start := 0#usize, «end» := n } g

/-- [lt_stateful_passes::unit_effect_loop_iteration]: loop body 0:
    Source: 'tests/src/lt-stateful-passes.rs', lines 866:4-868:5
    Visibility: public -/
@[rust_loop_body]
def unit_effect_loop_iteration_loop.body
  (l : Lock) (iter : core.ops.range.Range Std.Usize) :
  Result (ControlFlow (core.ops.range.Range Std.Usize) Unit)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done ())
  | some _ => Lock.touch_unit l
              ok (cont iter1)

/-- [lt_stateful_passes::unit_effect_loop_iteration]: loop 0:
    Source: 'tests/src/lt-stateful-passes.rs', lines 866:4-868:5
    Visibility: public -/
@[rust_loop]
def unit_effect_loop_iteration_loop
  (iter : core.ops.range.Range Std.Usize) (l : Lock) : Result Unit := do
  loop
    (fun iter1 => unit_effect_loop_iteration_loop.body l iter1)
    iter

/-- [lt_stateful_passes::unit_effect_loop_iteration]:
    Source: 'tests/src/lt-stateful-passes.rs', lines 865:0-869:1
    Visibility: public -/
@[reducible]
def unit_effect_loop_iteration (l : Lock) (n : Std.Usize) : Result Unit := do
  unit_effect_loop_iteration_loop { start := 0#usize, «end» := n } l

end lt_stateful_passes
