-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_concurrency]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_concurrency

/-- [core::mem::maybe_uninit::MaybeUninit]
    Source: '/rustc/library/core/src/mem/maybe_uninit.rs', lines 355:0-355:24
    Name pattern: [core::mem::maybe_uninit::MaybeUninit]
    Visibility: public -/
@[rust_type "core::mem::maybe_uninit::MaybeUninit"]
axiom core.mem.maybe_uninit.MaybeUninit (T : Type) : Type

/-- [core::mem::drop]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 1000:0-1002:24
    Name pattern: [core::mem::drop]
    Visibility: public -/
@[rust_fun "core::mem::drop"]
axiom core.mem.drop {T : Type} : T → Result Unit

/-- [alloc::string::{alloc::string::String}::len]:
    Source: '/rustc/library/alloc/src/string.rs', lines 1869:4-1869:36
    Name pattern: [alloc::string::{alloc::string::String}::len]
    Visibility: public -/
@[rust_fun "alloc::string::{alloc::string::String}::len"]
axiom alloc.string.String.len : String → Result Std.Usize

/-- [alloc::string::{impl core::convert::From<&'_0 str> for alloc::string::String}::from]:
    Source: '/rustc/library/alloc/src/string.rs', lines 3126:4-3126:30
    Name pattern: [alloc::string::{core::convert::From<alloc::string::String, &'0 str>}::from]
    Visibility: public -/
@[rust_fun
  "alloc::string::{core::convert::From<alloc::string::String, &'0 str>}::from"]
axiom alloc.string.String.Insts.CoreConvertFromShared0Str.from
  : Str → Result String

/-- [lt_stateful_concurrency::JoinHandle]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 82:0-84:1
    Visibility: public -/
axiom JoinHandle (T : Type) : Type

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::JoinHandle<T>}::join]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 91:4-93:5
    Visibility: public -/
axiom JoinHandle.join {T : Type} : JoinHandle T → Result T

/-- [lt_stateful_concurrency::spawn]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 106:0-111:1
    Visibility: public -/
axiom spawn
  {F : Type} {T : Type} (coreopsfunctionFnOnceFTupleTInst :
  core.ops.function.FnOnce F Unit T) :
  F → Result (JoinHandle T)

/-- [lt_stateful_concurrency::FallibleJoinHandle]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 123:0-125:1
    Visibility: public -/
axiom FallibleJoinHandle (T : Type) : Type

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::FallibleJoinHandle<T>}::join]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 136:4-138:5
    Visibility: public -/
axiom FallibleJoinHandle.join
  {T : Type} : FallibleJoinHandle T → Result (core.result.Result T Unit)

/-- [lt_stateful_concurrency::spawn_fallible]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 144:0-149:1
    Visibility: public -/
axiom spawn_fallible
  {F : Type} {T : Type} (coreopsfunctionFnOnceFTupleTInst :
  core.ops.function.FnOnce F Unit T) :
  F → Result (FallibleJoinHandle T)

/-- [lt_stateful_concurrency::yield_now]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 155:0-155:21
    Visibility: public -/
axiom yield_now : Result Unit

/-- [lt_stateful_concurrency::Arc]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 168:0-170:1
    Visibility: public -/
axiom Arc (T : Type) : Type

/-- [lt_stateful_concurrency::{impl core::ops::drop::Drop for lt_stateful_concurrency::Arc<T>}::drop]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 191:4-193:5
    Visibility: public -/
axiom Arc.Insts.CoreOpsDropDrop.drop {T : Type} : Arc T → Result (Arc T)

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::Arc<T>}::new]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 174:4-176:5
    Visibility: public -/
axiom Arc.new {T : Type} : T → Result (Arc T)

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::Arc<T>}::get]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 179:4-181:5
    Visibility: public -/
axiom Arc.get {T : Type} : Arc T → Result T

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::Arc<T>}::clone_arc]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 184:4-186:5
    Visibility: public -/
axiom Arc.clone_arc {T : Type} : Arc T → Result (Arc T)

/-- Trait implementation: [lt_stateful_concurrency::{impl core::ops::drop::Drop for lt_stateful_concurrency::Arc<T>}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 189:0-194:1 -/
@[reducible]
def Arc.Insts.CoreOpsDropDrop (T : Type) : core.ops.drop.Drop (Arc T) := {
  drop := Arc.Insts.CoreOpsDropDrop.drop
}

/-- [lt_stateful_concurrency::Lock]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 200:0-202:1
    Visibility: public -/
axiom Lock (T : Type) : Type

/-- [lt_stateful_concurrency::ReadGuard]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 205:0-207:1
    Visibility: public -/
axiom ReadGuard (T : Type) : Type

/-- [lt_stateful_concurrency::WriteGuard]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 210:0-212:1
    Visibility: public -/
axiom WriteGuard (T : Type) : Type

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::Lock<T>}::new]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 216:4-218:5
    Visibility: public -/
axiom Lock.new {T : Type} : T → Result (Lock T)

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::Lock<T>}::read]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 221:4-223:5
    Visibility: public -/
axiom Lock.read {T : Type} : Lock T → Result (ReadGuard T)

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::Lock<T>}::write]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 226:4-228:5
    Visibility: public -/
axiom Lock.write
  {T : Type} : Lock T → Result ((WriteGuard T) × (WriteGuard T → Unit))

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::ReadGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 233:4-235:5
    Visibility: public -/
axiom ReadGuard.get {T : Type} : ReadGuard T → Result T

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::ReadGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 238:4-238:27
    Visibility: public -/
axiom ReadGuard.release {T : Type} : ReadGuard T → Result Unit

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::WriteGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 243:4-245:5
    Visibility: public -/
axiom WriteGuard.get {T : Type} : WriteGuard T → Result T

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::WriteGuard<'a, T>}::get_mut]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 248:4-250:5
    Visibility: public -/
axiom WriteGuard.get_mut
  {T : Type} :
  WriteGuard T → Result (T × (T → WriteGuard T) × (WriteGuard T →
    WriteGuard T))

/-- [lt_stateful_concurrency::{lt_stateful_concurrency::WriteGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 253:4-253:27
    Visibility: public -/
axiom WriteGuard.release {T : Type} : WriteGuard T → Result (WriteGuard T)

/-- [lt_stateful_concurrency::run_with_callback]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 266:0-271:1
    Visibility: public -/
axiom run_with_callback
  {F : Type} {T : Type} (coreopsfunctionFnOnceFTupleI32TInst :
  core.ops.function.FnOnce F Std.I32 T) :
  Std.I32 → F → Result T

/-- [lt_stateful_concurrency::spawn_and_join_single::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 281:23-281:28 -/
@[reducible]
def spawn_and_join_single.closure := Unit

/-- [lt_stateful_concurrency::spawn_and_join_single::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::spawn_and_join_single::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 281:23-281:28 -/
def spawn_and_join_single.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : spawn_and_join_single.closure) (_ : Unit) : Result Std.I32 := do
  ok 42#i32

/-- Trait implementation: [lt_stateful_concurrency::spawn_and_join_single::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::spawn_and_join_single::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 281:23-281:28 -/
@[reducible]
def spawn_and_join_single.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce spawn_and_join_single.closure Unit Std.I32 := {
  call_once :=
    spawn_and_join_single.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::spawn_and_join_single]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 280:0-283:1
    Visibility: public -/
def spawn_and_join_single : Result Std.I32 := do
  let handle ←
    spawn spawn_and_join_single.closure.Insts.CoreOpsFunctionFnOnceTupleI32 ()
  JoinHandle.join handle

/-- [lt_stateful_concurrency::spawn_and_join_two::closure#1]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 291:19-291:23 -/
@[reducible]
def spawn_and_join_two.closure_1 := Unit

/-- [lt_stateful_concurrency::spawn_and_join_two::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::spawn_and_join_two::closure#1}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 291:19-291:23 -/
def spawn_and_join_two.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : spawn_and_join_two.closure_1) (_ : Unit) : Result Std.I32 := do
  ok 2#i32

/-- Trait implementation: [lt_stateful_concurrency::spawn_and_join_two::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::spawn_and_join_two::closure#1}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 291:19-291:23 -/
@[reducible]
def spawn_and_join_two.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce spawn_and_join_two.closure_1 Unit Std.I32 := {
  call_once :=
    spawn_and_join_two.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::spawn_and_join_two::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 290:19-290:23 -/
@[reducible]
def spawn_and_join_two.closure := Unit

/-- [lt_stateful_concurrency::spawn_and_join_two::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::spawn_and_join_two::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 290:19-290:23 -/
def spawn_and_join_two.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : spawn_and_join_two.closure) (_ : Unit) : Result Std.I32 := do
  ok 1#i32

/-- Trait implementation: [lt_stateful_concurrency::spawn_and_join_two::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::spawn_and_join_two::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 290:19-290:23 -/
@[reducible]
def spawn_and_join_two.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce spawn_and_join_two.closure Unit Std.I32 := {
  call_once :=
    spawn_and_join_two.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::spawn_and_join_two]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 289:0-295:1
    Visibility: public -/
def spawn_and_join_two : Result (Std.I32 × Std.I32) := do
  let h1 ←
    spawn spawn_and_join_two.closure.Insts.CoreOpsFunctionFnOnceTupleI32 ()
  let h2 ←
    spawn spawn_and_join_two.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32 ()
  let r1 ← JoinHandle.join h1
  let r2 ← JoinHandle.join h2
  ok (r1, r2)

/-- [lt_stateful_concurrency::two_workers_combine_results::closure#1]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 307:19-307:23 -/
@[reducible]
def two_workers_combine_results.closure_1 := Unit

/-- [lt_stateful_concurrency::two_workers_combine_results::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::two_workers_combine_results::closure#1}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 307:19-307:23 -/
def
  two_workers_combine_results.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : two_workers_combine_results.closure_1) (_ : Unit) : Result Std.I32 := do
  ok 4#i32

/-- Trait implementation: [lt_stateful_concurrency::two_workers_combine_results::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::two_workers_combine_results::closure#1}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 307:19-307:23 -/
@[reducible]
def two_workers_combine_results.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce two_workers_combine_results.closure_1 Unit Std.I32
  := {
  call_once :=
    two_workers_combine_results.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::two_workers_combine_results::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 306:19-306:23 -/
@[reducible]
def two_workers_combine_results.closure := Unit

/-- [lt_stateful_concurrency::two_workers_combine_results::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::two_workers_combine_results::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 306:19-306:23 -/
def
  two_workers_combine_results.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : two_workers_combine_results.closure) (_ : Unit) : Result Std.I32 := do
  ok 3#i32

/-- Trait implementation: [lt_stateful_concurrency::two_workers_combine_results::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::two_workers_combine_results::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 306:19-306:23 -/
@[reducible]
def two_workers_combine_results.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce two_workers_combine_results.closure Unit Std.I32
  := {
  call_once :=
    two_workers_combine_results.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::two_workers_combine_results]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 305:0-309:1
    Visibility: public -/
def two_workers_combine_results : Result Std.I32 := do
  let h1 ←
    spawn
      two_workers_combine_results.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      ()
  let h2 ←
    spawn
      two_workers_combine_results.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32
      ()
  let i ← JoinHandle.join h1
  let i1 ← JoinHandle.join h2
  i * i1

/-- [lt_stateful_concurrency::join_order_reversed::closure#1]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 317:19-317:24 -/
@[reducible]
def join_order_reversed.closure_1 := Unit

/-- [lt_stateful_concurrency::join_order_reversed::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::join_order_reversed::closure#1}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 317:19-317:24 -/
def join_order_reversed.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : join_order_reversed.closure_1) (_ : Unit) : Result Std.I32 := do
  ok 20#i32

/-- Trait implementation: [lt_stateful_concurrency::join_order_reversed::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::join_order_reversed::closure#1}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 317:19-317:24 -/
@[reducible]
def join_order_reversed.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce join_order_reversed.closure_1 Unit Std.I32 := {
  call_once :=
    join_order_reversed.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::join_order_reversed::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 316:19-316:24 -/
@[reducible]
def join_order_reversed.closure := Unit

/-- [lt_stateful_concurrency::join_order_reversed::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::join_order_reversed::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 316:19-316:24 -/
def join_order_reversed.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : join_order_reversed.closure) (_ : Unit) : Result Std.I32 := do
  ok 10#i32

/-- Trait implementation: [lt_stateful_concurrency::join_order_reversed::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::join_order_reversed::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 316:19-316:24 -/
@[reducible]
def join_order_reversed.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce join_order_reversed.closure Unit Std.I32 := {
  call_once :=
    join_order_reversed.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::join_order_reversed]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 315:0-321:1
    Visibility: public -/
def join_order_reversed : Result (Std.I32 × Std.I32) := do
  let h1 ←
    spawn join_order_reversed.closure.Insts.CoreOpsFunctionFnOnceTupleI32 ()
  let h2 ←
    spawn join_order_reversed.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32 ()
  let r2 ← JoinHandle.join h2
  let r1 ← JoinHandle.join h1
  ok (r1, r2)

/-- [lt_stateful_concurrency::handle_drop_without_join::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 330:23-330:28 -/
@[reducible]
def handle_drop_without_join.closure := Unit

/-- [lt_stateful_concurrency::handle_drop_without_join::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::handle_drop_without_join::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 330:23-330:28 -/
def
  handle_drop_without_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : handle_drop_without_join.closure) (_ : Unit) : Result Std.I32 := do
  ok 99#i32

/-- Trait implementation: [lt_stateful_concurrency::handle_drop_without_join::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::handle_drop_without_join::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 330:23-330:28 -/
@[reducible]
def handle_drop_without_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce handle_drop_without_join.closure Unit Std.I32 := {
  call_once :=
    handle_drop_without_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::handle_drop_without_join]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 329:0-332:1
    Visibility: public -/
def handle_drop_without_join : Result Unit := do
  let handle ←
    spawn handle_drop_without_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      ()
  core.mem.drop handle

/-- [lt_stateful_concurrency::handle_detach_then_other_handle_joined::closure#1]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 343:19-343:23 -/
@[reducible]
def handle_detach_then_other_handle_joined.closure_1 := Unit

/-- [lt_stateful_concurrency::handle_detach_then_other_handle_joined::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::handle_detach_then_other_handle_joined::closure#1}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 343:19-343:23 -/
def
  handle_detach_then_other_handle_joined.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : handle_detach_then_other_handle_joined.closure_1) (_ : Unit) :
  Result Std.I32
  := do
  ok 2#i32

/-- Trait implementation: [lt_stateful_concurrency::handle_detach_then_other_handle_joined::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::handle_detach_then_other_handle_joined::closure#1}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 343:19-343:23 -/
@[reducible]
def
  handle_detach_then_other_handle_joined.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce handle_detach_then_other_handle_joined.closure_1
  Unit Std.I32 := {
  call_once :=
    handle_detach_then_other_handle_joined.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::handle_detach_then_other_handle_joined::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 342:19-342:23 -/
@[reducible]
def handle_detach_then_other_handle_joined.closure := Unit

/-- [lt_stateful_concurrency::handle_detach_then_other_handle_joined::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::handle_detach_then_other_handle_joined::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 342:19-342:23 -/
def
  handle_detach_then_other_handle_joined.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : handle_detach_then_other_handle_joined.closure) (_ : Unit) :
  Result Std.I32
  := do
  ok 1#i32

/-- Trait implementation: [lt_stateful_concurrency::handle_detach_then_other_handle_joined::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::handle_detach_then_other_handle_joined::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 342:19-342:23 -/
@[reducible]
def
  handle_detach_then_other_handle_joined.closure.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce handle_detach_then_other_handle_joined.closure
  Unit Std.I32 := {
  call_once :=
    handle_detach_then_other_handle_joined.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::handle_detach_then_other_handle_joined]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 341:0-346:1
    Visibility: public -/
def handle_detach_then_other_handle_joined : Result Std.I32 := do
  let h1 ←
    spawn
      handle_detach_then_other_handle_joined.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      ()
  let h2 ←
    spawn
      handle_detach_then_other_handle_joined.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32
      ()
  core.mem.drop h1
  JoinHandle.join h2

/-- [lt_stateful_concurrency::worker_panic_reflected_in_join_result::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 356:32-356:37 -/
@[reducible]
def worker_panic_reflected_in_join_result.closure := Unit

/-- [lt_stateful_concurrency::worker_panic_reflected_in_join_result::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::worker_panic_reflected_in_join_result::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 356:32-356:37 -/
def
  worker_panic_reflected_in_join_result.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : worker_panic_reflected_in_join_result.closure) (_ : Unit) :
  Result Std.I32
  := do
  ok 42#i32

/-- Trait implementation: [lt_stateful_concurrency::worker_panic_reflected_in_join_result::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::worker_panic_reflected_in_join_result::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 356:32-356:37 -/
@[reducible]
def
  worker_panic_reflected_in_join_result.closure.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce worker_panic_reflected_in_join_result.closure Unit
  Std.I32 := {
  call_once :=
    worker_panic_reflected_in_join_result.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::worker_panic_reflected_in_join_result]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 355:0-361:1
    Visibility: public -/
def worker_panic_reflected_in_join_result : Result Std.I32 := do
  let handle ←
    spawn_fallible
      worker_panic_reflected_in_join_result.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      ()
  let r ← FallibleJoinHandle.join handle
  match r with
  | core.result.Result.Ok v => ok v
  | core.result.Result.Err _ => ok (-1)#i32

/-- [lt_stateful_concurrency::closure_capture_by_move::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 375:23-375:56 -/
def closure_capture_by_move.closure := String × alloc.vec.Vec Std.I32

/-- [lt_stateful_concurrency::closure_capture_by_move::{impl core::ops::function::FnOnce<(), usize> for lt_stateful_concurrency::closure_capture_by_move::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 375:23-375:56 -/
def
  closure_capture_by_move.closure.Insts.CoreOpsFunctionFnOnceTupleUsize.call_once
  (c : closure_capture_by_move.closure) (_ : Unit) : Result Std.Usize := do
  let (s, v) := c
  let i ← alloc.string.String.len s
  let i1 := alloc.vec.Vec.len v
  i + i1

/-- Trait implementation: [lt_stateful_concurrency::closure_capture_by_move::{impl core::ops::function::FnOnce<(), usize> for lt_stateful_concurrency::closure_capture_by_move::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 375:23-375:56 -/
@[reducible]
def closure_capture_by_move.closure.Insts.CoreOpsFunctionFnOnceTupleUsize :
  core.ops.function.FnOnce closure_capture_by_move.closure Unit Std.Usize := {
  call_once :=
    closure_capture_by_move.closure.Insts.CoreOpsFunctionFnOnceTupleUsize.call_once
}

/-- [lt_stateful_concurrency::closure_capture_by_move]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 372:0-377:1
    Visibility: public -/
def closure_capture_by_move : Result Std.Usize := do
  let owned ←
    alloc.string.String.Insts.CoreConvertFromShared0Str.from (toStr "payload")
  let y ←
    lift (Std.Array.to_slice (Array.make 3#usize [ 1#i32, 2#i32, 3#i32 ] :
      Array Std.I32 3#usize))
  let ret := alloc.slice.Slice.into_vec y
  let handle ←
    spawn closure_capture_by_move.closure.Insts.CoreOpsFunctionFnOnceTupleUsize
      (owned, ret)
  JoinHandle.join handle

/-- [lt_stateful_concurrency::spawn_capturing_shared_borrow::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 384:23-384:32 -/
@[reducible]
def spawn_capturing_shared_borrow.closure := Std.I32

/-- [lt_stateful_concurrency::spawn_capturing_shared_borrow::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::spawn_capturing_shared_borrow::closure<'_0>}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 384:23-384:32 -/
def
  spawn_capturing_shared_borrow.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : spawn_capturing_shared_borrow.closure) (_ : Unit) : Result Std.I32 := do
  c + 1#i32

/-- Trait implementation: [lt_stateful_concurrency::spawn_capturing_shared_borrow::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::spawn_capturing_shared_borrow::closure<'_0>}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 384:23-384:32 -/
@[reducible]
def spawn_capturing_shared_borrow.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce spawn_capturing_shared_borrow.closure Unit Std.I32
  := {
  call_once :=
    spawn_capturing_shared_borrow.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::spawn_capturing_shared_borrow]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 383:0-386:1
    Visibility: public -/
def spawn_capturing_shared_borrow (x : Std.I32) : Result Std.I32 := do
  let handle ←
    spawn
      spawn_capturing_shared_borrow.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      x
  JoinHandle.join handle

/-- [lt_stateful_concurrency::arc_cloned_into_worker::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 401:23-401:50 -/
@[reducible]
def arc_cloned_into_worker.closure := Arc Std.I32

/-- [lt_stateful_concurrency::arc_cloned_into_worker::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::arc_cloned_into_worker::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 401:23-401:50 -/
def
  arc_cloned_into_worker.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : arc_cloned_into_worker.closure) (_ : Unit) : Result Std.I32 := do
  Arc.get c

/-- Trait implementation: [lt_stateful_concurrency::arc_cloned_into_worker::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::arc_cloned_into_worker::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 401:23-401:50 -/
@[reducible]
def arc_cloned_into_worker.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce arc_cloned_into_worker.closure Unit Std.I32 := {
  call_once :=
    arc_cloned_into_worker.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::arc_cloned_into_worker]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 398:0-405:1
    Visibility: public -/
def arc_cloned_into_worker (value : Std.I32) : Result Std.I32 := do
  let shared ← Arc.new value
  let worker_owner ← Arc.clone_arc shared
  let handle ←
    spawn arc_cloned_into_worker.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      worker_owner
  let result ← JoinHandle.join handle
  let _ ← Arc.get shared
  ok result

/-- [lt_stateful_concurrency::detached_handle_holds_arc_clone::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 418:23-418:50 -/
@[reducible]
def detached_handle_holds_arc_clone.closure := Arc Std.I32

/-- [lt_stateful_concurrency::detached_handle_holds_arc_clone::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::detached_handle_holds_arc_clone::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 418:23-418:50 -/
def
  detached_handle_holds_arc_clone.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : detached_handle_holds_arc_clone.closure) (_ : Unit) :
  Result Std.I32
  := do
  Arc.get c

/-- Trait implementation: [lt_stateful_concurrency::detached_handle_holds_arc_clone::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::detached_handle_holds_arc_clone::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 418:23-418:50 -/
@[reducible]
def detached_handle_holds_arc_clone.closure.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce detached_handle_holds_arc_clone.closure Unit
  Std.I32 := {
  call_once :=
    detached_handle_holds_arc_clone.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::detached_handle_holds_arc_clone]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 415:0-421:1
    Visibility: public -/
def detached_handle_holds_arc_clone (value : Std.I32) : Result Std.I32 := do
  let shared ← Arc.new value
  let worker_owner ← Arc.clone_arc shared
  let handle ←
    spawn
      detached_handle_holds_arc_clone.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      worker_owner
  core.mem.drop handle
  Arc.get shared

/-- [lt_stateful_concurrency::worker_failure_after_arc_capture::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 434:32-434:59 -/
@[reducible]
def worker_failure_after_arc_capture.closure := Arc Std.I32

/-- [lt_stateful_concurrency::worker_failure_after_arc_capture::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::worker_failure_after_arc_capture::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 434:32-434:59 -/
def
  worker_failure_after_arc_capture.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : worker_failure_after_arc_capture.closure) (_ : Unit) :
  Result Std.I32
  := do
  Arc.get c

/-- Trait implementation: [lt_stateful_concurrency::worker_failure_after_arc_capture::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::worker_failure_after_arc_capture::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 434:32-434:59 -/
@[reducible]
def
  worker_failure_after_arc_capture.closure.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce worker_failure_after_arc_capture.closure Unit
  Std.I32 := {
  call_once :=
    worker_failure_after_arc_capture.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::worker_failure_after_arc_capture]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 431:0-441:1
    Visibility: public -/
def worker_failure_after_arc_capture (value : Std.I32) : Result Std.I32 := do
  let shared ← Arc.new value
  let worker_owner ← Arc.clone_arc shared
  let handle ←
    spawn_fallible
      worker_failure_after_arc_capture.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      worker_owner
  let r ← FallibleJoinHandle.join handle
  let result ←
    match r with
    | core.result.Result.Ok v => ok v
    | core.result.Result.Err _ => ok (-1)#i32
  let _ ← Arc.get shared
  ok result

/-- [lt_stateful_concurrency::lock_in_worker::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 450:23-455:5 -/
@[reducible]
def lock_in_worker.closure := Arc (Lock Std.I32)

/-- [lt_stateful_concurrency::lock_in_worker::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::lock_in_worker::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 450:23-455:5 -/
def lock_in_worker.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : lock_in_worker.closure) (_ : Unit) : Result Std.I32 := do
  let l ← Arc.get c
  let guard ← Lock.read l
  let v ← ReadGuard.get guard
  ReadGuard.release guard
  ok v

/-- Trait implementation: [lt_stateful_concurrency::lock_in_worker::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::lock_in_worker::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 450:23-455:5 -/
@[reducible]
def lock_in_worker.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce lock_in_worker.closure Unit Std.I32 := {
  call_once :=
    lock_in_worker.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::lock_in_worker]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 447:0-457:1
    Visibility: public -/
def lock_in_worker (value : Std.I32) : Result Std.I32 := do
  let l ← Lock.new value
  let shared ← Arc.new l
  let worker_owner ← Arc.clone_arc shared
  let handle ←
    spawn lock_in_worker.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      worker_owner
  JoinHandle.join handle

/-- [lt_stateful_concurrency::lock_around_spawn_join::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 468:23-468:27 -/
@[reducible]
def lock_around_spawn_join.closure := Unit

/-- [lt_stateful_concurrency::lock_around_spawn_join::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::lock_around_spawn_join::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 468:23-468:27 -/
def
  lock_around_spawn_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : lock_around_spawn_join.closure) (_ : Unit) : Result Std.I32 := do
  ok 7#i32

/-- Trait implementation: [lt_stateful_concurrency::lock_around_spawn_join::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::lock_around_spawn_join::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 468:23-468:27 -/
@[reducible]
def lock_around_spawn_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce lock_around_spawn_join.closure Unit Std.I32 := {
  call_once :=
    lock_around_spawn_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::lock_around_spawn_join]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 465:0-473:1
    Visibility: public -/
def lock_around_spawn_join (value : Std.I32) : Result Std.I32 := do
  let lock ← Lock.new value
  let guard ← Lock.read lock
  let handle ←
    spawn lock_around_spawn_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32 ()
  let worker_result ← JoinHandle.join handle
  let v ← ReadGuard.get guard
  ReadGuard.release guard
  v + worker_result

/-- [lt_stateful_concurrency::write_guard_around_spawn_join::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 482:23-482:27 -/
@[reducible]
def write_guard_around_spawn_join.closure := Unit

/-- [lt_stateful_concurrency::write_guard_around_spawn_join::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::write_guard_around_spawn_join::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 482:23-482:27 -/
def
  write_guard_around_spawn_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : write_guard_around_spawn_join.closure) (_ : Unit) : Result Std.I32 := do
  ok 7#i32

/-- Trait implementation: [lt_stateful_concurrency::write_guard_around_spawn_join::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::write_guard_around_spawn_join::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 482:23-482:27 -/
@[reducible]
def write_guard_around_spawn_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce write_guard_around_spawn_join.closure Unit Std.I32
  := {
  call_once :=
    write_guard_around_spawn_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::write_guard_around_spawn_join]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 479:0-488:1
    Visibility: public -/
def write_guard_around_spawn_join (value : Std.I32) : Result Std.I32 := do
  let lock ← Lock.new value
  let (guard, _) ← Lock.write lock
  let handle ←
    spawn
      write_guard_around_spawn_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      ()
  let worker_result ← JoinHandle.join handle
  let (i, get_mut_back, _) ← WriteGuard.get_mut guard
  let i1 ← i + 1#i32
  let guard1 := get_mut_back i1
  let v ← WriteGuard.get guard1
  let _ ← WriteGuard.release guard1
  v + worker_result

/-- [lt_stateful_concurrency::worker_owns_read_guard::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 496:23-500:5 -/
@[reducible]
def worker_owns_read_guard.closure := ReadGuard Std.I32

/-- [lt_stateful_concurrency::worker_owns_read_guard::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::worker_owns_read_guard::closure<'_0>}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 496:23-500:5 -/
def
  worker_owns_read_guard.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : worker_owns_read_guard.closure) (_ : Unit) : Result Std.I32 := do
  let value ← ReadGuard.get c
  ReadGuard.release c
  ok value

/-- Trait implementation: [lt_stateful_concurrency::worker_owns_read_guard::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::worker_owns_read_guard::closure<'_0>}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 496:23-500:5 -/
@[reducible]
def worker_owns_read_guard.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce worker_owns_read_guard.closure Unit Std.I32 := {
  call_once :=
    worker_owns_read_guard.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::worker_owns_read_guard]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 494:0-502:1
    Visibility: public -/
def worker_owns_read_guard (lock : Lock Std.I32) : Result Std.I32 := do
  let guard ← Lock.read lock
  let handle ←
    spawn worker_owns_read_guard.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      guard
  JoinHandle.join handle

/-- [lt_stateful_concurrency::two_locks_two_workers_independent::closure#1]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 521:19-526:5 -/
@[reducible]
def two_locks_two_workers_independent.closure_1 := Arc (Lock Std.I32)

/-- [lt_stateful_concurrency::two_locks_two_workers_independent::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::two_locks_two_workers_independent::closure#1}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 521:19-526:5 -/
def
  two_locks_two_workers_independent.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : two_locks_two_workers_independent.closure_1) (_ : Unit) :
  Result Std.I32
  := do
  let l ← Arc.get c
  let guard ← Lock.read l
  let v ← ReadGuard.get guard
  ReadGuard.release guard
  ok v

/-- Trait implementation: [lt_stateful_concurrency::two_locks_two_workers_independent::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::two_locks_two_workers_independent::closure#1}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 521:19-526:5 -/
@[reducible]
def
  two_locks_two_workers_independent.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce two_locks_two_workers_independent.closure_1 Unit
  Std.I32 := {
  call_once :=
    two_locks_two_workers_independent.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::two_locks_two_workers_independent::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 515:19-520:5 -/
@[reducible]
def two_locks_two_workers_independent.closure := Arc (Lock Std.I32)

/-- [lt_stateful_concurrency::two_locks_two_workers_independent::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::two_locks_two_workers_independent::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 515:19-520:5 -/
def
  two_locks_two_workers_independent.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : two_locks_two_workers_independent.closure) (_ : Unit) :
  Result Std.I32
  := do
  let l ← Arc.get c
  let guard ← Lock.read l
  let v ← ReadGuard.get guard
  ReadGuard.release guard
  ok v

/-- Trait implementation: [lt_stateful_concurrency::two_locks_two_workers_independent::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::two_locks_two_workers_independent::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 515:19-520:5 -/
@[reducible]
def
  two_locks_two_workers_independent.closure.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce two_locks_two_workers_independent.closure Unit
  Std.I32 := {
  call_once :=
    two_locks_two_workers_independent.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::two_locks_two_workers_independent]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 510:0-528:1
    Visibility: public -/
def two_locks_two_workers_independent
  (a : Std.I32) (b : Std.I32) : Result (Std.I32 × Std.I32) := do
  let l ← Lock.new a
  let lock_a ← Arc.new l
  let l1 ← Lock.new b
  let lock_b ← Arc.new l1
  let owner_a ← Arc.clone_arc lock_a
  let owner_b ← Arc.clone_arc lock_b
  let ha ←
    spawn
      two_locks_two_workers_independent.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      owner_a
  let hb ←
    spawn
      two_locks_two_workers_independent.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32
      owner_b
  let i ← JoinHandle.join ha
  let i1 ← JoinHandle.join hb
  ok (i, i1)

/-- [lt_stateful_concurrency::multiple_handles_collected_in_vec::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 542:27-542:40 -/
@[reducible]
def multiple_handles_collected_in_vec.closure := Std.I32

/-- [lt_stateful_concurrency::multiple_handles_collected_in_vec::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::multiple_handles_collected_in_vec::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 542:27-542:40 -/
def
  multiple_handles_collected_in_vec.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : multiple_handles_collected_in_vec.closure) (_ : Unit) :
  Result Std.I32
  := do
  c * 2#i32

/-- Trait implementation: [lt_stateful_concurrency::multiple_handles_collected_in_vec::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::multiple_handles_collected_in_vec::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 542:27-542:40 -/
@[reducible]
def
  multiple_handles_collected_in_vec.closure.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce multiple_handles_collected_in_vec.closure Unit
  Std.I32 := {
  call_once :=
    multiple_handles_collected_in_vec.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::multiple_handles_collected_in_vec]: loop body 0:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 541:4-543:5
    Visibility: public -/
@[rust_loop_body]
def multiple_handles_collected_in_vec_loop0.body
  (iter : alloc.vec.into_iter.IntoIter Std.I32)
  (handles : alloc.vec.Vec (JoinHandle Std.I32)) :
  Result (ControlFlow ((alloc.vec.into_iter.IntoIter Std.I32) × (alloc.vec.Vec
    (JoinHandle Std.I32))) (alloc.vec.Vec (JoinHandle Std.I32)))
  := do
  let (o, iter1) ← alloc.vec.into_iter.IteratorIntoIter.next iter
  match o with
  | none => ok (done handles)
  | some v =>
    let jh ←
      spawn
        multiple_handles_collected_in_vec.closure.Insts.CoreOpsFunctionFnOnceTupleI32
        v
    let handles1 ← alloc.vec.Vec.push handles jh
    ok (cont (iter1, handles1))

/-- [lt_stateful_concurrency::multiple_handles_collected_in_vec]: loop 0:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 541:4-543:5
    Visibility: public -/
@[rust_loop]
def multiple_handles_collected_in_vec_loop0
  (iter : alloc.vec.into_iter.IntoIter Std.I32)
  (handles : alloc.vec.Vec (JoinHandle Std.I32)) :
  Result (alloc.vec.Vec (JoinHandle Std.I32))
  := do
  loop
    (fun (iter1, handles1) => multiple_handles_collected_in_vec_loop0.body
      iter1 handles1)
    (iter, handles)

/-- [lt_stateful_concurrency::multiple_handles_collected_in_vec]: loop body 1:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 545:4-547:5
    Visibility: public -/
@[rust_loop_body]
def multiple_handles_collected_in_vec_loop1.body
  (iter : alloc.vec.into_iter.IntoIter (JoinHandle Std.I32)) (total : Std.I32)
  :
  Result (ControlFlow ((alloc.vec.into_iter.IntoIter (JoinHandle Std.I32)) ×
    Std.I32) Std.I32)
  := do
  let (o, iter1) ← alloc.vec.into_iter.IteratorIntoIter.next iter
  match o with
  | none => ok (done total)
  | some handle =>
    let i ← JoinHandle.join handle
    let total1 ← total + i
    ok (cont (iter1, total1))

/-- [lt_stateful_concurrency::multiple_handles_collected_in_vec]: loop 1:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 545:4-547:5
    Visibility: public -/
@[rust_loop]
def multiple_handles_collected_in_vec_loop1
  (iter : alloc.vec.into_iter.IntoIter (JoinHandle Std.I32)) (total : Std.I32)
  :
  Result Std.I32
  := do
  loop
    (fun (iter1, total1) => multiple_handles_collected_in_vec_loop1.body iter1
      total1)
    (iter, total)

/-- [lt_stateful_concurrency::multiple_handles_collected_in_vec]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 539:0-549:1
    Visibility: public -/
def multiple_handles_collected_in_vec
  (values : alloc.vec.Vec Std.I32) : Result Std.I32 := do
  let iter ← alloc.vec.IntoIteratorVec.into_iter values
  let handles ←
    multiple_handles_collected_in_vec_loop0 iter (alloc.vec.Vec.new (JoinHandle
      Std.I32))
  let iter1 ← alloc.vec.IntoIteratorVec.into_iter handles
  multiple_handles_collected_in_vec_loop1 iter1 0#i32

/-- [lt_stateful_concurrency::container_of_handles_dropped_unjoined::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 562:27-562:40 -/
@[reducible]
def container_of_handles_dropped_unjoined.closure := Std.I32

/-- [lt_stateful_concurrency::container_of_handles_dropped_unjoined::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::container_of_handles_dropped_unjoined::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 562:27-562:40 -/
def
  container_of_handles_dropped_unjoined.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : container_of_handles_dropped_unjoined.closure) (_ : Unit) :
  Result Std.I32
  := do
  c * 2#i32

/-- Trait implementation: [lt_stateful_concurrency::container_of_handles_dropped_unjoined::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::container_of_handles_dropped_unjoined::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 562:27-562:40 -/
@[reducible]
def
  container_of_handles_dropped_unjoined.closure.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce container_of_handles_dropped_unjoined.closure Unit
  Std.I32 := {
  call_once :=
    container_of_handles_dropped_unjoined.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::container_of_handles_dropped_unjoined]: loop body 0:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 561:4-563:5
    Visibility: public -/
@[rust_loop_body]
def container_of_handles_dropped_unjoined_loop.body
  (iter : alloc.vec.into_iter.IntoIter Std.I32)
  (handles : alloc.vec.Vec (JoinHandle Std.I32)) :
  Result (ControlFlow ((alloc.vec.into_iter.IntoIter Std.I32) × (alloc.vec.Vec
    (JoinHandle Std.I32))) Unit)
  := do
  let (o, iter1) ← alloc.vec.into_iter.IteratorIntoIter.next iter
  match o with
  | none => ok (done ())
  | some v =>
    let jh ←
      spawn
        container_of_handles_dropped_unjoined.closure.Insts.CoreOpsFunctionFnOnceTupleI32
        v
    let handles1 ← alloc.vec.Vec.push handles jh
    ok (cont (iter1, handles1))

/-- [lt_stateful_concurrency::container_of_handles_dropped_unjoined]: loop 0:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 561:4-563:5
    Visibility: public -/
@[rust_loop]
def container_of_handles_dropped_unjoined_loop
  (iter : alloc.vec.into_iter.IntoIter Std.I32)
  (handles : alloc.vec.Vec (JoinHandle Std.I32)) :
  Result Unit
  := do
  loop
    (fun (iter1, handles1) => container_of_handles_dropped_unjoined_loop.body
      iter1 handles1)
    (iter, handles)

/-- [lt_stateful_concurrency::container_of_handles_dropped_unjoined]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 559:0-566:1
    Visibility: public -/
def container_of_handles_dropped_unjoined
  (values : alloc.vec.Vec Std.I32) : Result Unit := do
  let iter ← alloc.vec.IntoIteratorVec.into_iter values
  container_of_handles_dropped_unjoined_loop iter (alloc.vec.Vec.new
    (JoinHandle Std.I32))

/-- [lt_stateful_concurrency::join_result_used_in_computation::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 574:23-574:27 -/
@[reducible]
def join_result_used_in_computation.closure := Unit

/-- [lt_stateful_concurrency::join_result_used_in_computation::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::join_result_used_in_computation::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 574:23-574:27 -/
def
  join_result_used_in_computation.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : join_result_used_in_computation.closure) (_ : Unit) :
  Result Std.I32
  := do
  ok 5#i32

/-- Trait implementation: [lt_stateful_concurrency::join_result_used_in_computation::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::join_result_used_in_computation::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 574:23-574:27 -/
@[reducible]
def join_result_used_in_computation.closure.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce join_result_used_in_computation.closure Unit
  Std.I32 := {
  call_once :=
    join_result_used_in_computation.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::join_result_used_in_computation]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 573:0-577:1
    Visibility: public -/
def join_result_used_in_computation : Result Std.I32 := do
  let handle ←
    spawn
      join_result_used_in_computation.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      ()
  let value ← JoinHandle.join handle
  let i ← value * value
  i + 1#i32

/-- [lt_stateful_concurrency::nested_spawn_inside_worker::closure::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 586:26-586:30 -/
@[reducible]
def nested_spawn_inside_worker.closure.closure := Unit

/-- [lt_stateful_concurrency::nested_spawn_inside_worker::closure::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::nested_spawn_inside_worker::closure::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 586:26-586:30 -/
def
  nested_spawn_inside_worker.closure.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : nested_spawn_inside_worker.closure.closure) (_ : Unit) :
  Result Std.I32
  := do
  ok 3#i32

/-- Trait implementation: [lt_stateful_concurrency::nested_spawn_inside_worker::closure::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::nested_spawn_inside_worker::closure::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 586:26-586:30 -/
@[reducible]
def
  nested_spawn_inside_worker.closure.closure.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce nested_spawn_inside_worker.closure.closure Unit
  Std.I32 := {
  call_once :=
    nested_spawn_inside_worker.closure.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::nested_spawn_inside_worker::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 585:22-588:5 -/
@[reducible]
def nested_spawn_inside_worker.closure := Unit

/-- [lt_stateful_concurrency::nested_spawn_inside_worker::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::nested_spawn_inside_worker::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 585:22-588:5 -/
def
  nested_spawn_inside_worker.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : nested_spawn_inside_worker.closure) (_ : Unit) : Result Std.I32 := do
  let inner ←
    spawn
      nested_spawn_inside_worker.closure.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      ()
  let i ← JoinHandle.join inner
  i + 1#i32

/-- Trait implementation: [lt_stateful_concurrency::nested_spawn_inside_worker::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::nested_spawn_inside_worker::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 585:22-588:5 -/
@[reducible]
def nested_spawn_inside_worker.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce nested_spawn_inside_worker.closure Unit Std.I32 := {
  call_once :=
    nested_spawn_inside_worker.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::nested_spawn_inside_worker]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 584:0-590:1
    Visibility: public -/
def nested_spawn_inside_worker : Result Std.I32 := do
  let outer ←
    spawn
      nested_spawn_inside_worker.closure.Insts.CoreOpsFunctionFnOnceTupleI32 ()
  JoinHandle.join outer

/-- [lt_stateful_concurrency::spawn_then_yield_then_join::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 597:23-597:28 -/
@[reducible]
def spawn_then_yield_then_join.closure := Unit

/-- [lt_stateful_concurrency::spawn_then_yield_then_join::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::spawn_then_yield_then_join::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 597:23-597:28 -/
def
  spawn_then_yield_then_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : spawn_then_yield_then_join.closure) (_ : Unit) : Result Std.I32 := do
  ok 11#i32

/-- Trait implementation: [lt_stateful_concurrency::spawn_then_yield_then_join::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::spawn_then_yield_then_join::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 597:23-597:28 -/
@[reducible]
def spawn_then_yield_then_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce spawn_then_yield_then_join.closure Unit Std.I32 := {
  call_once :=
    spawn_then_yield_then_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::spawn_then_yield_then_join]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 596:0-600:1
    Visibility: public -/
def spawn_then_yield_then_join : Result Std.I32 := do
  let handle ←
    spawn
      spawn_then_yield_then_join.closure.Insts.CoreOpsFunctionFnOnceTupleI32 ()
  yield_now
  JoinHandle.join handle

/-- [lt_stateful_concurrency::join_and_double]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 604:0-606:1 -/
def join_and_double (handle : JoinHandle Std.I32) : Result Std.I32 := do
  let i ← JoinHandle.join handle
  i * 2#i32

/-- [lt_stateful_concurrency::join_handle_moved_into_helper::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 614:23-614:28 -/
@[reducible]
def join_handle_moved_into_helper.closure := Unit

/-- [lt_stateful_concurrency::join_handle_moved_into_helper::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::join_handle_moved_into_helper::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 614:23-614:28 -/
def
  join_handle_moved_into_helper.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : join_handle_moved_into_helper.closure) (_ : Unit) : Result Std.I32 := do
  ok 21#i32

/-- Trait implementation: [lt_stateful_concurrency::join_handle_moved_into_helper::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::join_handle_moved_into_helper::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 614:23-614:28 -/
@[reducible]
def join_handle_moved_into_helper.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce join_handle_moved_into_helper.closure Unit Std.I32
  := {
  call_once :=
    join_handle_moved_into_helper.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::join_handle_moved_into_helper]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 613:0-616:1
    Visibility: public -/
def join_handle_moved_into_helper : Result Std.I32 := do
  let handle ←
    spawn
      join_handle_moved_into_helper.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      ()
  join_and_double handle

/-- [lt_stateful_concurrency::drop_handle_early_then_spawn_more::closure#1]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 626:23-626:27 -/
@[reducible]
def drop_handle_early_then_spawn_more.closure_1 := Unit

/-- [lt_stateful_concurrency::drop_handle_early_then_spawn_more::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::drop_handle_early_then_spawn_more::closure#1}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 626:23-626:27 -/
def
  drop_handle_early_then_spawn_more.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : drop_handle_early_then_spawn_more.closure_1) (_ : Unit) :
  Result Std.I32
  := do
  ok 2#i32

/-- Trait implementation: [lt_stateful_concurrency::drop_handle_early_then_spawn_more::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::drop_handle_early_then_spawn_more::closure#1}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 626:23-626:27 -/
@[reducible]
def
  drop_handle_early_then_spawn_more.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce drop_handle_early_then_spawn_more.closure_1 Unit
  Std.I32 := {
  call_once :=
    drop_handle_early_then_spawn_more.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::drop_handle_early_then_spawn_more::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 624:22-624:26 -/
@[reducible]
def drop_handle_early_then_spawn_more.closure := Unit

/-- [lt_stateful_concurrency::drop_handle_early_then_spawn_more::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::drop_handle_early_then_spawn_more::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 624:22-624:26 -/
def
  drop_handle_early_then_spawn_more.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : drop_handle_early_then_spawn_more.closure) (_ : Unit) :
  Result Std.I32
  := do
  ok 1#i32

/-- Trait implementation: [lt_stateful_concurrency::drop_handle_early_then_spawn_more::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency::drop_handle_early_then_spawn_more::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 624:22-624:26 -/
@[reducible]
def
  drop_handle_early_then_spawn_more.closure.Insts.CoreOpsFunctionFnOnceTupleI32
  : core.ops.function.FnOnce drop_handle_early_then_spawn_more.closure Unit
  Std.I32 := {
  call_once :=
    drop_handle_early_then_spawn_more.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency::drop_handle_early_then_spawn_more]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 623:0-628:1
    Visibility: public -/
def drop_handle_early_then_spawn_more : Result Std.I32 := do
  let first ←
    spawn
      drop_handle_early_then_spawn_more.closure.Insts.CoreOpsFunctionFnOnceTupleI32
      ()
  core.mem.drop first
  let second ←
    spawn
      drop_handle_early_then_spawn_more.closure_1.Insts.CoreOpsFunctionFnOnceTupleI32
      ()
  JoinHandle.join second

/-- [lt_stateful_concurrency::concurrent_callback_single::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 638:29-638:38 -/
@[reducible]
def concurrent_callback_single.closure := Unit

/-- [lt_stateful_concurrency::concurrent_callback_single::{impl core::ops::function::FnOnce<(i32,), i32> for lt_stateful_concurrency::concurrent_callback_single::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 638:29-638:38 -/
def
  concurrent_callback_single.closure.Insts.CoreOpsFunctionFnOnceTupleI32I32.call_once
  (c : concurrent_callback_single.closure) (tupled_args : Std.I32) :
  Result Std.I32
  := do
  tupled_args + 1#i32

/-- Trait implementation: [lt_stateful_concurrency::concurrent_callback_single::{impl core::ops::function::FnOnce<(i32,), i32> for lt_stateful_concurrency::concurrent_callback_single::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 638:29-638:38 -/
@[reducible]
def concurrent_callback_single.closure.Insts.CoreOpsFunctionFnOnceTupleI32I32 :
  core.ops.function.FnOnce concurrent_callback_single.closure Std.I32 Std.I32
  := {
  call_once :=
    concurrent_callback_single.closure.Insts.CoreOpsFunctionFnOnceTupleI32I32.call_once
}

/-- [lt_stateful_concurrency::concurrent_callback_single]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 637:0-639:1
    Visibility: public -/
def concurrent_callback_single (input : Std.I32) : Result Std.I32 := do
  run_with_callback
    concurrent_callback_single.closure.Insts.CoreOpsFunctionFnOnceTupleI32I32
    input ()

/-- [lt_stateful_concurrency::concurrent_callback_chained::closure::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 647:54-647:63 -/
@[reducible]
def concurrent_callback_chained.closure.closure := Unit

/-- [lt_stateful_concurrency::concurrent_callback_chained::closure::{impl core::ops::function::FnOnce<(i32,), i32> for lt_stateful_concurrency::concurrent_callback_chained::closure::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 647:54-647:63 -/
def
  concurrent_callback_chained.closure.closure.Insts.CoreOpsFunctionFnOnceTupleI32I32.call_once
  (c : concurrent_callback_chained.closure.closure) (tupled_args : Std.I32) :
  Result Std.I32
  := do
  tupled_args * 2#i32

/-- Trait implementation: [lt_stateful_concurrency::concurrent_callback_chained::closure::{impl core::ops::function::FnOnce<(i32,), i32> for lt_stateful_concurrency::concurrent_callback_chained::closure::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 647:54-647:63 -/
@[reducible]
def
  concurrent_callback_chained.closure.closure.Insts.CoreOpsFunctionFnOnceTupleI32I32
  : core.ops.function.FnOnce concurrent_callback_chained.closure.closure
  Std.I32 Std.I32 := {
  call_once :=
    concurrent_callback_chained.closure.closure.Insts.CoreOpsFunctionFnOnceTupleI32I32.call_once
}

/-- [lt_stateful_concurrency::concurrent_callback_chained::closure]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 647:29-647:64 -/
@[reducible]
def concurrent_callback_chained.closure := Unit

/-- [lt_stateful_concurrency::concurrent_callback_chained::{impl core::ops::function::FnOnce<(i32,), i32> for lt_stateful_concurrency::concurrent_callback_chained::closure}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 647:29-647:64 -/
def
  concurrent_callback_chained.closure.Insts.CoreOpsFunctionFnOnceTupleI32I32.call_once
  (c : concurrent_callback_chained.closure) (tupled_args : Std.I32) :
  Result Std.I32
  := do
  run_with_callback
    concurrent_callback_chained.closure.closure.Insts.CoreOpsFunctionFnOnceTupleI32I32
    tupled_args ()

/-- Trait implementation: [lt_stateful_concurrency::concurrent_callback_chained::{impl core::ops::function::FnOnce<(i32,), i32> for lt_stateful_concurrency::concurrent_callback_chained::closure}]
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 647:29-647:64 -/
@[reducible]
def concurrent_callback_chained.closure.Insts.CoreOpsFunctionFnOnceTupleI32I32
  : core.ops.function.FnOnce concurrent_callback_chained.closure Std.I32
  Std.I32 := {
  call_once :=
    concurrent_callback_chained.closure.Insts.CoreOpsFunctionFnOnceTupleI32I32.call_once
}

/-- [lt_stateful_concurrency::concurrent_callback_chained]:
    Source: 'tests/src/lt-stateful-concurrency.rs', lines 646:0-648:1
    Visibility: public -/
def concurrent_callback_chained (input : Std.I32) : Result Std.I32 := do
  run_with_callback
    concurrent_callback_chained.closure.Insts.CoreOpsFunctionFnOnceTupleI32I32
    input ()

end lt_stateful_concurrency
