-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_clist_client]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_clist_client

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 811:0-811:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- [core::option::{impl core::clone::Clone for core::option::Option<T>}::clone]:
    Source: '/rustc/library/core/src/option.rs', lines 2277:4-2277:27
    Name pattern: [core::option::{core::clone::Clone<core::option::Option<@T>>}::clone]
    Visibility: public -/
@[rust_fun
  "core::option::{core::clone::Clone<core::option::Option<@T>>}::clone"]
axiom core.option.Option.Insts.CoreCloneClone.clone
  {T : Type} (cloneCloneInst : core.clone.Clone T) :
  Option T → Result (Option T)

/-- [lt_stateful_clist_client::my_std::RwLock]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 131:0-133:1
    Visibility: public -/
structure my_std.RwLock (T : Type) where
  marker : core.marker.PhantomData T

/-- [lt_stateful_clist_client::my_std::Arc]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 71:0-73:1
    Visibility: public -/
structure my_std.Arc (T : Type) where
  marker : core.marker.PhantomData T

/-- [lt_stateful_clist_client::clist::Node]
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 44:0-48:1
    Visibility: public -/
inductive clist.Node (T : Type) where
| mk :
  Bool →
  T →
  Option (my_std.Arc (my_std.RwLock (clist.Node T))) →
  clist.Node T

def clist.Node.revoked {T : Type} (x : clist.Node T) :=
  match x with | clist.Node.mk x1 _ _ => x1

def clist.Node.value {T : Type} (x : clist.Node T) :=
  match x with | clist.Node.mk _ x1 _ => x1

def clist.Node.next {T : Type} (x : clist.Node T) :=
  match x with | clist.Node.mk _ _ x1 => x1

@[simp]
theorem clist.Node.revoked._simpLemma_ {T : Type} (revoked : Bool) (value : T)
  (next : Option (my_std.Arc (my_std.RwLock (clist.Node T)))) :
  (clist.Node.mk revoked value next).revoked = revoked := by rfl

@[simp]
theorem clist.Node.value._simpLemma_ {T : Type} (revoked : Bool) (value : T)
  (next : Option (my_std.Arc (my_std.RwLock (clist.Node T)))) :
  (clist.Node.mk revoked value next).value = value := by rfl

@[simp]
theorem clist.Node.next._simpLemma_ {T : Type} (revoked : Bool) (value : T)
  (next : Option (my_std.Arc (my_std.RwLock (clist.Node T)))) :
  (clist.Node.mk revoked value next).next = next := by rfl

/-- [lt_stateful_clist_client::clist::Platform]
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 7:0-9:1
    Visibility: public -/
structure clist.Platform where
  lock : my_std.Arc (my_std.RwLock Unit)

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::RwLock<T>}::new]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 147:4-149:5
    Visibility: public -/
axiom my_std.RwLock.new {T : Type} : T → Result (my_std.RwLock T)

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::Arc<T>}::new]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 81:4-83:5
    Visibility: public -/
axiom my_std.Arc.new {T : Type} : T → Result (my_std.Arc T)

/-- [lt_stateful_clist_client::clist::{lt_stateful_clist_client::clist::Platform}::new]:
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 12:4-16:5
    Visibility: public -/
def clist.Platform.new : Result clist.Platform := do
  let rl ← my_std.RwLock.new ()
  let a ← my_std.Arc.new rl
  ok { lock := a }

/-- [lt_stateful_clist_client::my_std::RwLockReadGuard]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 136:0-138:1
    Visibility: public -/
axiom my_std.RwLockReadGuard (T : Type) : Type

/-- [lt_stateful_clist_client::clist::{lt_stateful_clist_client::clist::Platform}::acquire_shared_lock]:
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 20:4-22:5
    Visibility: public -/
axiom clist.Platform.acquire_shared_lock
  :
  clist.Platform → Result ((my_std.RwLockReadGuard Unit) ×
    (my_std.RwLockReadGuard Unit → Result Unit))

/-- [lt_stateful_clist_client::my_std::RwLockWriteGuard]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 141:0-143:1
    Visibility: public -/
axiom my_std.RwLockWriteGuard (T : Type) : Type

/-- [lt_stateful_clist_client::clist::{lt_stateful_clist_client::clist::Platform}::acquire_exclusive_lock]:
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 26:4-28:5
    Visibility: public -/
axiom clist.Platform.acquire_exclusive_lock
  :
  clist.Platform → Result ((my_std.RwLockWriteGuard Unit) ×
    (my_std.RwLockWriteGuard Unit → Result Unit))

/-- [lt_stateful_clist_client::my_std::{impl core::ops::drop::Drop for lt_stateful_clist_client::my_std::RwLockWriteGuard<'_0, T>}::drop]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 201:4-203:5
    Visibility: public -/
axiom my_std.RwLockWriteGuard.Insts.CoreOpsDropDrop.drop
  {T : Type} :
  my_std.RwLockWriteGuard T → Result ((my_std.RwLockWriteGuard T) ×
    (my_std.RwLockWriteGuard T → Result (my_std.RwLockWriteGuard T)))

/-- [lt_stateful_clist_client::my_std::{impl core::ops::drop::Drop for lt_stateful_clist_client::my_std::RwLockReadGuard<'_0, T>}::drop]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 176:4-178:5
    Visibility: public -/
axiom my_std.RwLockReadGuard.Insts.CoreOpsDropDrop.drop
  {T : Type} :
  my_std.RwLockReadGuard T → Result ((my_std.RwLockReadGuard T) × (Result
    Unit))

/-- [lt_stateful_clist_client::clist::{lt_stateful_clist_client::clist::Platform}::execute]:
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 30:4-41:5
    Visibility: public -/
def clist.Platform.execute
  {R : Type} {F : Type} (coreopsfunctionFnOnceFTupleOptionInst :
  core.ops.function.FnOnce F Unit (Option R)) (self : clist.Platform)
  (exclusive : Bool) (f : F) :
  Result (Option R)
  := do
  if exclusive
  then
    let p ← clist.Platform.acquire_exclusive_lock self
    let (_lock, acquire_exclusive_lock_back) := p
    let o ← coreopsfunctionFnOnceFTupleOptionInst.call_once f ()
    acquire_exclusive_lock_back _lock
    ok o
  else
    let p ← clist.Platform.acquire_shared_lock self
    let (_lock, acquire_shared_lock_back) := p
    let o ← coreopsfunctionFnOnceFTupleOptionInst.call_once f ()
    acquire_shared_lock_back _lock
    ok o

/-- [lt_stateful_clist_client::clist::new]:
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 49:0-55:1
    Visibility: public -/
def clist.new
  {T : Type} (value : T)
  (next : Option (my_std.Arc (my_std.RwLock (clist.Node T)))) :
  Result (my_std.Arc (my_std.RwLock (clist.Node T)))
  := do
  let rl ← my_std.RwLock.new (clist.Node.mk false value next)
  my_std.Arc.new rl

/-- [lt_stateful_clist_client::clist::init]:
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 57:0-59:1
    Visibility: public -/
def clist.init
  {T : Type} (value : T) :
  Result (my_std.Arc (my_std.RwLock (clist.Node T)))
  := do
  clist.new value none

/-- [lt_stateful_clist_client::clist::insert::closure]
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 62:28-70:5 -/
def clist.insert.closure (T : Type) :=
  my_std.Arc (my_std.RwLock (clist.Node T)) × T

/-- [lt_stateful_clist_client::my_std::{impl core::ops::deref::DerefMut<T> for lt_stateful_clist_client::my_std::RwLockWriteGuard<'_0, T>}::deref_mut]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 193:4-195:5
    Visibility: public -/
axiom my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut
  {T : Type} :
  my_std.RwLockWriteGuard T → Result (T × (T → Result
    (my_std.RwLockWriteGuard T)) × (my_std.RwLockWriteGuard T → Result
    (my_std.RwLockWriteGuard T)))

/-- [lt_stateful_clist_client::my_std::{impl core::ops::deref::Deref<T> for lt_stateful_clist_client::my_std::RwLockWriteGuard<'_0, T>}::deref]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 185:4-187:5
    Visibility: public -/
axiom my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref
  {T : Type} : my_std.RwLockWriteGuard T → Result T

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::RwLock<T>}::write]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 159:4-161:5
    Visibility: public -/
axiom my_std.RwLock.write
  {T : Type} :
  my_std.RwLock T → Result ((my_std.RwLockWriteGuard T) ×
    (my_std.RwLockWriteGuard T → Result Unit))

/-- [lt_stateful_clist_client::my_std::{impl core::ops::deref::Deref<T> for lt_stateful_clist_client::my_std::Arc<T>}::deref]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 102:4-104:5
    Visibility: public -/
axiom my_std.Arc.Insts.CoreOpsDerefDeref.deref
  {T : Type} : my_std.Arc T → Result T

/-- [lt_stateful_clist_client::my_std::{impl core::clone::Clone for lt_stateful_clist_client::my_std::Arc<T>}::clone]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 93:4-95:5
    Visibility: public -/
axiom my_std.Arc.Insts.CoreCloneClone.clone
  {T : Type} : my_std.Arc T → Result (my_std.Arc T)

/-- Trait implementation: [lt_stateful_clist_client::my_std::{impl core::clone::Clone for lt_stateful_clist_client::my_std::Arc<T>}]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 91:0-96:1 -/
@[reducible]
def my_std.Arc.Insts.CoreCloneClone (T : Type) : core.clone.Clone (my_std.Arc
  T) := {
  clone := my_std.Arc.Insts.CoreCloneClone.clone
}

/-- [lt_stateful_clist_client::clist::insert::{impl core::ops::function::FnOnce<(), core::option::Option<lt_stateful_clist_client::my_std::Arc<lt_stateful_clist_client::my_std::RwLock<lt_stateful_clist_client::clist::Node<T>>>>> for lt_stateful_clist_client::clist::insert::closure<'_0, T>}::call_once]:
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 62:28-70:5 -/
def
  clist.insert.closure.Insts.CoreOpsFunctionFnOnceTupleOptionArcRwLockNode.call_once
  {T : Type} (c : clist.insert.closure T) (_ : Unit) :
  Result (Option (my_std.Arc (my_std.RwLock (clist.Node T))))
  := do
  let (a, t) := c
  let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref a
  let p ← my_std.RwLock.write rl
  let (ptr, write_back) := p
  let n ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref ptr
  if n.revoked
  then write_back ptr
       ok none
  else
    let o ←
      core.option.Option.Insts.CoreCloneClone.clone
        (my_std.Arc.Insts.CoreCloneClone (my_std.RwLock (clist.Node T))) 
        n.next
    let new_node ← clist.new t o
    let a1 ← my_std.Arc.Insts.CoreCloneClone.clone new_node
    let t1 ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut ptr
    let (n1, deref_mut_back, deref_mut_back1) := t1
    let ptr1 ← deref_mut_back (clist.Node.mk n1.revoked n1.value (some a1))
    let ptr2 ← deref_mut_back1 ptr1
    write_back ptr2
    ok (some new_node)

/-- Trait implementation: [lt_stateful_clist_client::clist::insert::{impl core::ops::function::FnOnce<(), core::option::Option<lt_stateful_clist_client::my_std::Arc<lt_stateful_clist_client::my_std::RwLock<lt_stateful_clist_client::clist::Node<T>>>>> for lt_stateful_clist_client::clist::insert::closure<'_0, T>}]
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 62:28-70:5 -/
@[reducible]
def clist.insert.closure.Insts.CoreOpsFunctionFnOnceTupleOptionArcRwLockNode (T
  : Type) : core.ops.function.FnOnce (clist.insert.closure T) Unit (Option
  (my_std.Arc (my_std.RwLock (clist.Node T)))) := {
  call_once :=
    clist.insert.closure.Insts.CoreOpsFunctionFnOnceTupleOptionArcRwLockNode.call_once
}

/-- [lt_stateful_clist_client::clist::insert]:
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 61:0-71:1
    Visibility: public -/
def clist.insert
  {T : Type} (platform : clist.Platform)
  (node : my_std.Arc (my_std.RwLock (clist.Node T))) (value : T) :
  Result (Option (my_std.Arc (my_std.RwLock (clist.Node T))))
  := do
  clist.Platform.execute
    (clist.insert.closure.Insts.CoreOpsFunctionFnOnceTupleOptionArcRwLockNode
    T) platform false (node, value)

/-- [lt_stateful_clist_client::clist::revoke_suffix]:
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 88:0-97:1 -/
def clist.revoke_suffix
  {T : Type} (current : Option (my_std.Arc (my_std.RwLock (clist.Node T)))) :
  Result Unit
  := do
  match current with
  | none => ok ()
  | some node =>
    let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref node
    let p ← my_std.RwLock.write rl
    let (ptr, write_back) := p
    let t ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut ptr
    let (n, deref_mut_back, deref_mut_back1) := t
    let ptr1 ← deref_mut_back (clist.Node.mk true n.value n.next)
    let t1 ←
      my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut ptr1
    let (n1, deref_mut_back2, deref_mut_back3) := t1
    let (next, o) := core.option.Option.take n1.next
    let ptr2 ← deref_mut_back2 (clist.Node.mk n1.revoked n1.value o)
    let ptr3 ← deref_mut_back3 ptr2
    let ptr4 ← deref_mut_back1 ptr3
    write_back ptr4
    clist.revoke_suffix next
partial_fixpoint

/-- [lt_stateful_clist_client::clist::revoke::closure]
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 74:27-85:5 -/
@[reducible]
def clist.revoke.closure (T : Type) :=
  my_std.Arc (my_std.RwLock (clist.Node T))

/-- [lt_stateful_clist_client::clist::revoke::{impl core::ops::function::FnOnce<(), core::option::Option<()>> for lt_stateful_clist_client::clist::revoke::closure<'_0, T>}::call_once]:
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 74:27-85:5 -/
def clist.revoke.closure.Insts.CoreOpsFunctionFnOnceTupleOptionTuple.call_once
  {T : Type} (c : clist.revoke.closure T) (_ : Unit) :
  Result (Option Unit)
  := do
  let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref c
  let p ← my_std.RwLock.write rl
  let (ptr, write_back) := p
  let n ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref ptr
  if n.revoked
  then write_back ptr
       ok none
  else
    let t ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut ptr
    let (n1, deref_mut_back, deref_mut_back1) := t
    let (next, o) := core.option.Option.take n1.next
    let ptr1 ← deref_mut_back (clist.Node.mk n1.revoked n1.value o)
    let ptr2 ← deref_mut_back1 ptr1
    write_back ptr2
    clist.revoke_suffix next
    ok (some ())

/-- Trait implementation: [lt_stateful_clist_client::clist::revoke::{impl core::ops::function::FnOnce<(), core::option::Option<()>> for lt_stateful_clist_client::clist::revoke::closure<'_0, T>}]
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 74:27-85:5 -/
@[reducible]
def clist.revoke.closure.Insts.CoreOpsFunctionFnOnceTupleOptionTuple (T : Type)
  : core.ops.function.FnOnce (clist.revoke.closure T) Unit (Option Unit) := {
  call_once :=
    clist.revoke.closure.Insts.CoreOpsFunctionFnOnceTupleOptionTuple.call_once
}

/-- [lt_stateful_clist_client::clist::revoke]:
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 73:0-86:1
    Visibility: public -/
def clist.revoke
  {T : Type} (platform : clist.Platform)
  (node : my_std.Arc (my_std.RwLock (clist.Node T))) :
  Result (Option Unit)
  := do
  clist.Platform.execute
    (clist.revoke.closure.Insts.CoreOpsFunctionFnOnceTupleOptionTuple T)
    platform true node

/-- [lt_stateful_clist_client::my_std::{impl core::ops::deref::Deref<T> for lt_stateful_clist_client::my_std::RwLockReadGuard<'_0, T>}::deref]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 168:4-170:5
    Visibility: public -/
axiom my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref
  {T : Type} : my_std.RwLockReadGuard T → Result T

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::RwLock<T>}::read]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 153:4-155:5
    Visibility: public -/
axiom my_std.RwLock.read
  {T : Type} :
  my_std.RwLock T → Result ((my_std.RwLockReadGuard T) ×
    (my_std.RwLockReadGuard T → Result Unit))

/-- [lt_stateful_clist_client::clist::get_child]:
    Source: 'tests/src/.lt-stateful-client/clist.rs', lines 99:0-102:1
    Visibility: public -/
def clist.get_child
  {T : Type} (node : my_std.Arc (my_std.RwLock (clist.Node T))) :
  Result (Option (my_std.Arc (my_std.RwLock (clist.Node T))))
  := do
  let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref node
  let p ← my_std.RwLock.read rl
  let (ptr, read_back) := p
  let n ← my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref ptr
  let o ←
    core.option.Option.Insts.CoreCloneClone.clone
      (my_std.Arc.Insts.CoreCloneClone (my_std.RwLock (clist.Node T))) 
      n.next
  read_back ptr
  ok o

/-- [lt_stateful_clist_client::my_std::Vec]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 5:0-7:1
    Visibility: public -/
structure my_std.Vec (T : Type) where
  marker : core.marker.PhantomData T

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::Vec<T>}::new]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 11:4-13:5
    Visibility: public -/
axiom my_std.Vec.new (T : Type) : Result (my_std.Vec T)

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::Vec<T>}::len]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 16:4-18:5
    Visibility: public -/
axiom my_std.Vec.len {T : Type} : my_std.Vec T → Result Std.Usize

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::Vec<T>}::push]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 21:4-23:5
    Visibility: public -/
axiom my_std.Vec.push {T : Type} : my_std.Vec T → T → Result (my_std.Vec T)

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::Vec<T>}::remove]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 26:4-28:5
    Visibility: public -/
axiom my_std.Vec.remove
  {T : Type} : my_std.Vec T → Std.Usize → Result (T × (my_std.Vec T))

/-- [lt_stateful_clist_client::my_std::{impl core::ops::index::Index<usize, T> for lt_stateful_clist_client::my_std::Vec<T>}::index]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 35:4-37:5
    Visibility: public -/
axiom my_std.Vec.Insts.CoreOpsIndexIndexUsizeT.index
  {T : Type} : my_std.Vec T → Std.Usize → Result T

/-- Trait implementation: [lt_stateful_clist_client::my_std::{impl core::ops::index::Index<usize, T> for lt_stateful_clist_client::my_std::Vec<T>}]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 31:0-38:1 -/
@[reducible]
def my_std.Vec.Insts.CoreOpsIndexIndexUsizeT (T : Type) : core.ops.index.Index
  (my_std.Vec T) Std.Usize T := {
  index := my_std.Vec.Insts.CoreOpsIndexIndexUsizeT.index
}

/-- [lt_stateful_clist_client::my_std::BTreeMap]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 40:0-42:1
    Visibility: public -/
structure my_std.BTreeMap (K : Type) (V : Type) where
  marker : core.marker.PhantomData (K × V)

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::BTreeMap<K, V>}::new]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 46:4-48:5
    Visibility: public -/
axiom my_std.BTreeMap.new (K : Type) (V : Type) : Result (my_std.BTreeMap K V)

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::BTreeMap<K, V>}::get]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 51:4-53:5
    Visibility: public -/
axiom my_std.BTreeMap.get
  {K : Type} {V : Type} : my_std.BTreeMap K V → K → Result (Option V)

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::BTreeMap<K, V>}::contains_key]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 56:4-58:5
    Visibility: public -/
axiom my_std.BTreeMap.contains_key
  {K : Type} {V : Type} : my_std.BTreeMap K V → K → Result Bool

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::BTreeMap<K, V>}::insert]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 61:4-63:5
    Visibility: public -/
axiom my_std.BTreeMap.insert
  {K : Type} {V : Type} :
  my_std.BTreeMap K V → K → V → Result ((Option V) × (my_std.BTreeMap K
    V))

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::BTreeMap<K, V>}::remove]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 66:4-68:5
    Visibility: public -/
axiom my_std.BTreeMap.remove
  {K : Type} {V : Type} :
  my_std.BTreeMap K V → K → Result ((Option V) × (my_std.BTreeMap K V))

/-- [lt_stateful_clist_client::my_std::Weak]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 75:0-77:1
    Visibility: public -/
structure my_std.Weak (T : Type) where
  marker : core.marker.PhantomData T

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::Arc<T>}::downgrade]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 86:4-88:5
    Visibility: public -/
axiom my_std.Arc.downgrade {T : Type} : my_std.Arc T → Result (my_std.Weak T)

/-- Trait implementation: [lt_stateful_clist_client::my_std::{impl core::ops::deref::Deref<T> for lt_stateful_clist_client::my_std::Arc<T>}]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 98:0-105:1 -/
@[reducible]
def my_std.Arc.Insts.CoreOpsDerefDeref (T : Type) : core.ops.deref.Deref
  (my_std.Arc T) T := {
  deref := my_std.Arc.Insts.CoreOpsDerefDeref.deref
}

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::Weak<T>}::new]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 109:4-111:5
    Visibility: public -/
axiom my_std.Weak.new (T : Type) : Result (my_std.Weak T)

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::Weak<T>}::upgrade]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 114:4-116:5
    Visibility: public -/
axiom my_std.Weak.upgrade
  {T : Type} : my_std.Weak T → Result (Option (my_std.Arc T))

/-- [lt_stateful_clist_client::my_std::{lt_stateful_clist_client::my_std::Weak<T>}::strong_count]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 119:4-121:5
    Visibility: public -/
axiom my_std.Weak.strong_count {T : Type} : my_std.Weak T → Result Std.Usize

/-- [lt_stateful_clist_client::my_std::{impl core::clone::Clone for lt_stateful_clist_client::my_std::Weak<T>}::clone]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 126:4-128:5
    Visibility: public -/
axiom my_std.Weak.Insts.CoreCloneClone.clone
  {T : Type} : my_std.Weak T → Result (my_std.Weak T)

/-- Trait implementation: [lt_stateful_clist_client::my_std::{impl core::clone::Clone for lt_stateful_clist_client::my_std::Weak<T>}]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 124:0-129:1 -/
@[reducible]
def my_std.Weak.Insts.CoreCloneClone (T : Type) : core.clone.Clone (my_std.Weak
  T) := {
  clone := my_std.Weak.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lt_stateful_clist_client::my_std::{impl core::ops::deref::Deref<T> for lt_stateful_clist_client::my_std::RwLockReadGuard<'_0, T>}]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 164:0-171:1 -/
@[reducible]
def my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref (T : Type) :
  core.ops.deref.Deref (my_std.RwLockReadGuard T) T := {
  deref := my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref
}

/-- Trait implementation: [lt_stateful_clist_client::my_std::{impl core::ops::deref::Deref<T> for lt_stateful_clist_client::my_std::RwLockWriteGuard<'_0, T>}]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 181:0-188:1 -/
@[reducible]
def my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref (T : Type) :
  core.ops.deref.Deref (my_std.RwLockWriteGuard T) T := {
  deref := my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref
}

end lt_stateful_clist_client
