-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_reborrows]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_reborrows

/-- [lt_stateful_reborrows::Lock]
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 73:0-75:1
    Visibility: public -/
axiom Lock (T : Type) : Type

/-- [lt_stateful_reborrows::ReadGuard]
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 78:0-80:1
    Visibility: public -/
axiom ReadGuard (T : Type) : Type

/-- [lt_stateful_reborrows::WriteGuard]
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 83:0-85:1
    Visibility: public -/
axiom WriteGuard (T : Type) : Type

/-- [lt_stateful_reborrows::{lt_stateful_reborrows::Lock<T>}::new]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 89:4-91:5
    Visibility: public -/
axiom Lock.new {T : Type} : T → Result (Lock T)

/-- [lt_stateful_reborrows::{lt_stateful_reborrows::Lock<T>}::read]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 95:4-97:5
    Visibility: public -/
axiom Lock.read {T : Type} : Lock T → Result (ReadGuard T)

/-- [lt_stateful_reborrows::{lt_stateful_reborrows::Lock<T>}::write]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 101:4-103:5
    Visibility: public -/
axiom Lock.write
  {T : Type} : Lock T → Result ((WriteGuard T) × (WriteGuard T → Unit))

/-- [lt_stateful_reborrows::{lt_stateful_reborrows::ReadGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 108:4-110:5
    Visibility: public -/
axiom ReadGuard.get {T : Type} : ReadGuard T → Result T

/-- [lt_stateful_reborrows::{lt_stateful_reborrows::ReadGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 114:4-114:27
    Visibility: public -/
axiom ReadGuard.release {T : Type} : ReadGuard T → Result Unit

/-- [lt_stateful_reborrows::{lt_stateful_reborrows::WriteGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 119:4-121:5
    Visibility: public -/
axiom WriteGuard.get {T : Type} : WriteGuard T → Result T

/-- [lt_stateful_reborrows::{lt_stateful_reborrows::WriteGuard<'a, T>}::get_mut]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 125:4-127:5
    Visibility: public -/
axiom WriteGuard.get_mut
  {T : Type} :
  WriteGuard T → Result (T × (T → WriteGuard T) × (WriteGuard T →
    WriteGuard T))

/-- [lt_stateful_reborrows::{lt_stateful_reborrows::WriteGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 131:4-131:27
    Visibility: public -/
axiom WriteGuard.release {T : Type} : WriteGuard T → Result (WriteGuard T)

/-- [lt_stateful_reborrows::Pair]
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 136:0-139:1
    Visibility: public -/
structure Pair where
  a : Std.I32
  b : Std.I32

/-- [lt_stateful_reborrows::Nested]
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 143:0-146:1
    Visibility: public -/
structure Nested where
  pair : Pair
  tag : Bool

/-- [lt_stateful_reborrows::Cabinet]
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 150:0-152:1
    Visibility: public -/
structure Cabinet where
  inner : Lock Std.I32

/-- [lt_stateful_reborrows::field_reborrow_write_guard]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 158:0-162:1
    Visibility: public -/
def field_reborrow_write_guard (lock : Lock Pair) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let (p, get_mut_back, _) ← WriteGuard.get_mut guard
  let guard1 := get_mut_back { p with a := 10#i32 }
  let _ ← WriteGuard.release guard1
  ok ()

/-- [lt_stateful_reborrows::disjoint_subfield_setters_single_get_mut]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 171:0-177:1
    Visibility: public -/
def disjoint_subfield_setters_single_get_mut
  (lock : Lock Pair) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let (_, get_mut_back, _) ← WriteGuard.get_mut guard
  let guard1 := get_mut_back { a := 1#i32, b := 2#i32 }
  let _ ← WriteGuard.release guard1
  ok ()

/-- [lt_stateful_reborrows::subfield_reborrow_nested]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 183:0-187:1
    Visibility: public -/
def subfield_reborrow_nested (lock : Lock Nested) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let (n, get_mut_back, _) ← WriteGuard.get_mut guard
  let guard1 := get_mut_back { n with pair := { n.pair with b := 20#i32 } }
  let _ ← WriteGuard.release guard1
  ok ()

/-- [lt_stateful_reborrows::repeated_deref_mut_chain]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 192:0-203:1
    Visibility: public -/
def repeated_deref_mut_chain (lock : Lock Pair) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let (r1, get_mut_back, _) ← WriteGuard.get_mut guard
  let i ← r1.a + 1#i32
  let guard1 := get_mut_back { r1 with a := i }
  let (r2, get_mut_back1, _) ← WriteGuard.get_mut guard1
  let i1 ← r2.b + 1#i32
  let guard2 := get_mut_back1 { r2 with b := i1 }
  let _ ← WriteGuard.release guard2
  ok ()

/-- [lt_stateful_reborrows::peek_pair_via_shared_guard]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 205:0-207:1 -/
def peek_pair_via_shared_guard (guard : WriteGuard Pair) : Result Std.I32 := do
  let p ← WriteGuard.get guard
  ok p.a

/-- [lt_stateful_reborrows::shared_reborrow_then_hoisted_update]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 213:0-221:1
    Visibility: public -/
def shared_reborrow_then_hoisted_update
  (lock : Lock Pair) : Result Std.I32 := do
  let (guard, _) ← Lock.write lock
  let peeked ← peek_pair_via_shared_guard guard
  let updated ← peeked + 1#i32
  let (p, get_mut_back, _) ← WriteGuard.get_mut guard
  let guard1 := get_mut_back { p with b := updated }
  let p1 ← WriteGuard.get guard1
  let _ ← WriteGuard.release guard1
  ok p1.b

/-- [lt_stateful_reborrows::nested_lock_through_guard]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 233:0-240:1
    Visibility: public -/
def nested_lock_through_guard
  (outer_lock : Lock Cabinet) : Result Std.I32 := do
  let (outer_guard, _) ← Lock.write outer_lock
  let (c, get_mut_back, _) ← WriteGuard.get_mut outer_guard
  let inner_guard ← Lock.read c.inner
  let value ← ReadGuard.get inner_guard
  ReadGuard.release inner_guard
  let outer_guard1 := get_mut_back c
  let _ ← WriteGuard.release outer_guard1
  ok value

/-- [lt_stateful_reborrows::returning_mutable_sub_borrow]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 247:0-249:1
    Visibility: public -/
def returning_mutable_sub_borrow
  (pair : Pair) : Result (Std.I32 × (Std.I32 → Pair)) := do
  let back := fun i => { pair with a := i }
  ok (pair.a, back)

/-- [lt_stateful_reborrows::identity_mut]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 252:0-254:1 -/
def identity_mut {T : Type} (x : T) : Result (T × (T → T)) := do
  ok (x, fun x1 => x1)

/-- [lt_stateful_reborrows::reborrow_chain_through_helper]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 261:0-265:1
    Visibility: public -/
def reborrow_chain_through_helper
  (pair : Pair) : Result (Std.I32 × (Std.I32 → Pair)) := do
  let (p1, identity_mut_back) ← identity_mut pair
  let (p2, identity_mut_back1) ← identity_mut p1
  let back :=
    fun i =>
      let p11 := identity_mut_back1 { p2 with a := i }
      identity_mut_back p11
  ok (p2.a, back)

/-- [lt_stateful_reborrows::shared_borrow_during_write_guard]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 272:0-278:1
    Visibility: public -/
def shared_borrow_during_write_guard
  (lock : Lock Pair) (other : Std.I32) : Result Std.I32 := do
  let (guard, _) ← Lock.write lock
  let (p, get_mut_back, _) ← WriteGuard.get_mut guard
  let guard1 := get_mut_back { p with a := other }
  let _ ← WriteGuard.release guard1
  ok other

/-- [lt_stateful_reborrows::outlives_chain]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 304:0-306:1
    Visibility: public -/
def outlives_chain {T : Type} (lock : Lock T) : Result (ReadGuard T) := do
  Lock.read lock

/-- [lt_stateful_reborrows::same_lifetime_read_pair]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 313:0-318:1 -/
def same_lifetime_read_pair
  {T : Type} (g1 : ReadGuard T) (g2 : ReadGuard T) :
  Result ((ReadGuard T) × (ReadGuard T))
  := do
  ok (g1, g2)

/-- [lt_stateful_reborrows::scc_two_guards]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 337:0-346:1
    Visibility: public -/
def scc_two_guards
  {T : Type} (coremarkerCopyInst : core.marker.Copy T) (lock_a : Lock T)
  (lock_b : Lock T) :
  Result (T × T)
  := do
  let ga ← Lock.read lock_a
  let gb ← Lock.read lock_b
  let (ga1, gb1) ← same_lifetime_read_pair ga gb
  let a_val ← ReadGuard.get ga1
  let b_val ← ReadGuard.get gb1
  ReadGuard.release ga1
  ReadGuard.release gb1
  ok (a_val, b_val)

/-- [lt_stateful_reborrows::choose]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 351:0-357:1
    Visibility: public -/
def choose
  {T : Type} (b : Bool) (x : T) (y : T) : Result (T × (T → (T × T))) := do
  if b
  then let back := fun x1 => (x1, y)
       ok (x, back)
  else let back := fun y1 => (x, y1)
       ok (y, back)

/-- [lt_stateful_reborrows::choose_field_projection]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 364:0-370:1
    Visibility: public -/
def choose_field_projection
  (b : Bool) (x : Pair) (y : Pair) :
  Result (Std.I32 × (Std.I32 → (Pair × Pair)))
  := do
  if b
  then let back := fun i => ({ x with a := i }, y)
       ok (x.a, back)
  else let back := fun i => (x, { y with b := i })
       ok (y.b, back)

/-- [lt_stateful_reborrows::local_mut_increment]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 373:0-375:1
    Visibility: public -/
def local_mut_increment (x : Std.I32) : Result Std.I32 := do
  x + 1#i32

/-- [lt_stateful_reborrows::local_reborrow_pure]:
    Source: 'tests/src/lt-stateful-reborrows.rs', lines 382:0-385:1
    Visibility: public -/
def local_reborrow_pure
  (x : Std.I32) : Result (Std.I32 × (Std.I32 → Std.I32)) := do
  let x1 ← local_mut_increment x
  ok (x1, fun x2 => x2)

end lt_stateful_reborrows
