-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_negative]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_negative

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 811:0-811:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- [lt_stateful_negative::Lock]
    Source: 'tests/src/lt-stateful-negative.rs', lines 54:0-56:1
    Visibility: public -/
axiom Lock (T : Type) : Type

/-- [lt_stateful_negative::ReadGuard]
    Source: 'tests/src/lt-stateful-negative.rs', lines 59:0-61:1
    Visibility: public -/
axiom ReadGuard (T : Type) : Type

/-- [lt_stateful_negative::WriteGuard]
    Source: 'tests/src/lt-stateful-negative.rs', lines 64:0-66:1
    Visibility: public -/
axiom WriteGuard (T : Type) : Type

/-- [lt_stateful_negative::{lt_stateful_negative::Lock<T>}::new]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 70:4-72:5
    Visibility: public -/
axiom Lock.new {T : Type} : T → Result (Lock T)

/-- [lt_stateful_negative::{lt_stateful_negative::Lock<T>}::read]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 75:4-77:5
    Visibility: public -/
axiom Lock.read {T : Type} : Lock T → Result (ReadGuard T)

/-- [lt_stateful_negative::{lt_stateful_negative::Lock<T>}::write]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 80:4-82:5
    Visibility: public -/
axiom Lock.write
  {T : Type} : Lock T → Result ((WriteGuard T) × (WriteGuard T → Unit))

/-- [lt_stateful_negative::{lt_stateful_negative::ReadGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 87:4-89:5
    Visibility: public -/
axiom ReadGuard.get {T : Type} : ReadGuard T → Result T

/-- [lt_stateful_negative::{lt_stateful_negative::ReadGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 92:4-92:27
    Visibility: public -/
axiom ReadGuard.release {T : Type} : ReadGuard T → Result Unit

/-- [lt_stateful_negative::{lt_stateful_negative::WriteGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 97:4-99:5
    Visibility: public -/
axiom WriteGuard.get {T : Type} : WriteGuard T → Result T

/-- [lt_stateful_negative::{lt_stateful_negative::WriteGuard<'a, T>}::get_mut]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 102:4-104:5
    Visibility: public -/
axiom WriteGuard.get_mut
  {T : Type} :
  WriteGuard T → Result (T × (T → WriteGuard T) × (WriteGuard T →
    WriteGuard T))

/-- [lt_stateful_negative::{lt_stateful_negative::WriteGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 107:4-107:27
    Visibility: public -/
axiom WriteGuard.release {T : Type} : WriteGuard T → Result (WriteGuard T)

/-- [lt_stateful_negative::unknown_lifetime_name]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 119:0-121:1
    Visibility: public -/
def unknown_lifetime_name
  {T : Type} (lock : Lock T) :
  Result ((WriteGuard T) × (WriteGuard T → Unit))
  := do
  let (wg, _) ← Lock.write lock
  let back := fun wg1 => ()
  ok (wg, back)

/-- [lt_stateful_negative::out_of_range_index]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 135:0-137:1
    Visibility: public -/
def out_of_range_index
  {T : Type} (lock : Lock T) :
  Result ((WriteGuard T) × (WriteGuard T → Unit))
  := do
  let (wg, _) ← Lock.write lock
  let back := fun wg1 => ()
  ok (wg, back)

/-- [lt_stateful_negative::named_lifetime_and_out_of_range_index]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 145:0-147:1
    Visibility: public -/
def named_lifetime_and_out_of_range_index
  {T : Type} (lock : Lock T) :
  Result ((WriteGuard T) × (WriteGuard T → Unit))
  := do
  let (wg, _) ← Lock.write lock
  let back := fun wg1 => ()
  ok (wg, back)

/-- [lt_stateful_negative::duplicate_lifetime_in_one_call]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 158:0-160:1
    Visibility: public -/
def duplicate_lifetime_in_one_call
  {T : Type} (lock : Lock T) :
  Result ((WriteGuard T) × (WriteGuard T → Unit))
  := do
  let (wg, _) ← Lock.write lock
  let back := fun wg1 => ()
  ok (wg, back)

/-- [lt_stateful_negative::duplicate_annotation_repeated]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 169:0-171:1
    Visibility: public -/
def duplicate_annotation_repeated
  {T : Type} (lock : Lock T) :
  Result ((WriteGuard T) × (WriteGuard T → Unit))
  := do
  let (wg, _) ← Lock.write lock
  let back := fun wg1 => ()
  ok (wg, back)

/-- [lt_stateful_negative::marked_with_no_lifetime_at_all]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 182:0-184:1
    Visibility: public -/
def marked_with_no_lifetime_at_all
  (a : Std.I32) (b : Std.I32) : Result Std.I32 := do
  a + b

/-- [lt_stateful_negative::PlainPair]
    Source: 'tests/src/lt-stateful-negative.rs', lines 190:0-193:1
    Visibility: public -/
structure PlainPair where
  a : Std.I32
  b : Std.I32

/-- [lt_stateful_negative::{lt_stateful_negative::PlainPair}::get_a]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 203:4-205:5
    Visibility: public -/
def PlainPair.get_a (self : PlainPair) : Result Std.I32 := do
  ok self.a

/-- [lt_stateful_negative::{lt_stateful_negative::PlainPair}::set_b]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 207:4-209:5
    Visibility: public -/
def PlainPair.set_b (self : PlainPair) (v : Std.I32) : Result PlainPair := do
  ok { self with b := v }

/-- Trait declaration: [lt_stateful_negative::PlainOps]
    Source: 'tests/src/lt-stateful-negative.rs', lines 216:0-218:1
    Visibility: public -/
structure PlainOps (Self : Type) where
  value : Self → Result Std.I32

/-- [lt_stateful_negative::conflicting_annotations]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 232:0-243:1
    Visibility: public -/
def conflicting_annotations
  {T : Type} (coremarkerCopyInst : core.marker.Copy T) (lock_a : Lock T)
  (lock_b : Lock T) :
  Result (T × T)
  := do
  let ga ← Lock.read lock_a
  let gb ← Lock.read lock_b
  let va ← ReadGuard.get ga
  let vb ← ReadGuard.get gb
  ReadGuard.release ga
  ReadGuard.release gb
  ok (va, vb)

/-- [lt_stateful_negative::malformed_identifier_static]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 255:0-257:1
    Visibility: public -/
def malformed_identifier_static
  {T : Type} (lock : Lock T) :
  Result ((WriteGuard T) × (WriteGuard T → Unit))
  := do
  let (wg, _) ← Lock.write lock
  let back := fun wg1 => ()
  ok (wg, back)

/-- [lt_stateful_negative::malformed_identifier_underscore_prefixed]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 266:0-268:1
    Visibility: public -/
def malformed_identifier_underscore_prefixed
  {T : Type} (lock : Lock T) :
  Result ((WriteGuard T) × (WriteGuard T → Unit))
  := do
  let (wg, _) ← Lock.write lock
  let back := fun wg1 => ()
  ok (wg, back)

/-- Trait declaration: [lt_stateful_negative::AmbiguousLockable]
    Source: 'tests/src/lt-stateful-negative.rs', lines 283:0-291:1
    Visibility: public -/
structure AmbiguousLockable (Self : Type) (Self_Item : Type) where
  acquire_write : Self → Result ((WriteGuard Self_Item) × (WriteGuard
    Self_Item → Unit))
  acquire_read : Self → Result (ReadGuard Self_Item)

/-- [lt_stateful_negative::anonymous_lifetime_reference]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 302:0-304:1
    Visibility: public -/
def anonymous_lifetime_reference
  {T : Type} (lock : Lock T) : Result (ReadGuard T) := do
  Lock.read lock

/-- [lt_stateful_negative::anonymous_and_named_mixed]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 313:0-324:1
    Visibility: public -/
def anonymous_and_named_mixed
  {T : Type} {U : Type} (coremarkerCopyInst : core.marker.Copy T)
  (coremarkerCopyInst1 : core.marker.Copy U) (lock_a : Lock T)
  (lock_b : Lock U) :
  Result (T × U)
  := do
  let ga ← Lock.read lock_a
  let gb ← Lock.read lock_b
  let va ← ReadGuard.get ga
  let vb ← ReadGuard.get gb
  ReadGuard.release ga
  ReadGuard.release gb
  ok (va, vb)

/-- [lt_stateful_negative::shared_borrow_marked_stateful]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 337:0-339:1
    Visibility: public -/
def shared_borrow_marked_stateful (x : Std.I32) : Result Std.I32 := do
  ok x

/-- [lt_stateful_negative::guard_may_escape_loop]: loop body 0:
    Source: 'tests/src/lt-stateful-negative.rs', lines 374:4-381:1
    Visibility: public -/
@[rust_loop_body]
def guard_may_escape_loop_loop.body
  {T : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T) (needle : T)
  (guard : WriteGuard T) (iter : core.slice.iter.Iter T) :
  Result (ControlFlow (core.slice.iter.Iter T) (Option T))
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => let _ ← WriteGuard.release guard
            ok (done none)
  | some candidate =>
    let b ← corecmpPartialEqInst.eq candidate needle
    if b
    then let t ← WriteGuard.get guard
         ok (done (some t))
    else ok (cont iter1)

/-- [lt_stateful_negative::guard_may_escape_loop]: loop 0:
    Source: 'tests/src/lt-stateful-negative.rs', lines 374:4-381:1
    Visibility: public -/
@[rust_loop]
def guard_may_escape_loop_loop
  {T : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T)
  (iter : core.slice.iter.Iter T) (needle : T) (guard : WriteGuard T) :
  Result (Option T)
  := do
  loop
    (fun iter1 => guard_may_escape_loop_loop.body corecmpPartialEqInst needle
      guard iter1)
    iter

/-- [lt_stateful_negative::guard_may_escape_loop]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 368:0-381:1
    Visibility: public -/
def guard_may_escape_loop
  {T : Type} (coremarkerCopyInst : core.marker.Copy T) (corecmpPartialEqInst :
  core.cmp.PartialEq T T) (lock : Lock T) (needle : T) (haystack : Slice T) :
  Result (Option T)
  := do
  let (guard, _) ← Lock.write lock
  let iter ←
    SharedSlice.Insts.CoreIterTraitsCollectIntoIteratorSharedIter.into_iter
      haystack
  guard_may_escape_loop_loop corecmpPartialEqInst iter needle guard

/-- [lt_stateful_negative::unannotated_acquire_release]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 397:0-400:1
    Visibility: public -/
def unannotated_acquire_release {T : Type} (lock : Lock T) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let _ ← WriteGuard.release guard
  ok ()

/-- [lt_stateful_negative::Toggle]
    Source: 'tests/src/lt-stateful-negative.rs', lines 408:0-410:1
    Visibility: public -/
structure Toggle (T : Type) where
  inner : Lock T

/-- [lt_stateful_negative::{lt_stateful_negative::Toggle<T>}::acquire_write]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 416:4-418:5
    Visibility: public -/
def Toggle.acquire_write
  {T : Type} (coremarkerCopyInst : core.marker.Copy T) (self : Toggle T) :
  Result ((WriteGuard T) × (WriteGuard T → Unit))
  := do
  let (wg, _) ← Lock.write self.inner
  let back := fun wg1 => ()
  ok (wg, back)

/-- [lt_stateful_negative::{lt_stateful_negative::Toggle<T>}::peek]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 437:4-439:5
    Visibility: public -/
def Toggle.peek
  {T : Type} (coremarkerCopyInst : core.marker.Copy T) (self : Toggle T)
  (flag : Bool) :
  Result Bool
  := do
  ok flag

mutual

/-- [lt_stateful_negative::ping]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 451:0-460:1
    Visibility: public -/
def ping
  {T : Type} (coremarkerCopyInst : core.marker.Copy T) (lock : Lock T)
  (n : Std.U32) :
  Result T
  := do
  let (guard, _) ← Lock.write lock
  let v ← WriteGuard.get guard
  let _ ← WriteGuard.release guard
  if n = 0#u32
  then ok v
  else let i ← n - 1#u32
       pong coremarkerCopyInst lock i
partial_fixpoint

/-- [lt_stateful_negative::pong]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 474:0-483:1
    Visibility: public -/
def pong
  {T : Type} (coremarkerCopyInst : core.marker.Copy T) (lock : Lock T)
  (n : Std.U32) :
  Result T
  := do
  let (guard, _) ← Lock.write lock
  let v ← WriteGuard.get guard
  let _ ← WriteGuard.release guard
  if n = 0#u32
  then ok v
  else let i ← n - 1#u32
       ping coremarkerCopyInst lock i
partial_fixpoint

end

/-- [lt_stateful_negative::PairGuardBox]
    Source: 'tests/src/lt-stateful-negative.rs', lines 491:0-494:1
    Visibility: public -/
structure PairGuardBox (T : Type) where
  first : WriteGuard T
  second : WriteGuard T

/-- [lt_stateful_negative::wrap_collapsed]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 510:0-515:1
    Visibility: public -/
def wrap_collapsed
  {T : Type} (first : WriteGuard T) (second : WriteGuard T) :
  Result ((PairGuardBox T) × (PairGuardBox T → ((WriteGuard T) ×
    (WriteGuard T))))
  := do
  let back := fun pgb => (pgb.first, pgb.second)
  ok ({ first, second }, back)

/-- [lt_stateful_negative::named_form_with_no_lifetime_at_all]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 528:0-530:1
    Visibility: public -/
def named_form_with_no_lifetime_at_all
  (a : Std.I32) (b : Std.I32) : Result Std.I32 := do
  a + b

/-- [lt_stateful_negative::bare_and_named_conflict]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 548:0-550:1
    Visibility: public -/
def bare_and_named_conflict
  {T : Type} (lock : Lock T) :
  Result ((WriteGuard T) × (WriteGuard T → Unit))
  := do
  let (wg, _) ← Lock.write lock
  let back := fun wg1 => ()
  ok (wg, back)

/-- [lt_stateful_negative::empty_parenthesized_list]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 559:0-561:1
    Visibility: public -/
def empty_parenthesized_list
  {T : Type} (lock : Lock T) :
  Result ((WriteGuard T) × (WriteGuard T → Unit))
  := do
  let (wg, _) ← Lock.write lock
  let back := fun wg1 => ()
  ok (wg, back)

/-- [lt_stateful_negative::name_value_attribute_form]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 566:0-568:1
    Visibility: public -/
def name_value_attribute_form
  {T : Type} (lock : Lock T) :
  Result ((WriteGuard T) × (WriteGuard T → Unit))
  := do
  let (wg, _) ← Lock.write lock
  let back := fun wg1 => ()
  ok (wg, back)

/-- [lt_stateful_negative::string_literal_attribute_form]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 573:0-575:1
    Visibility: public -/
def string_literal_attribute_form
  {T : Type} (lock : Lock T) :
  Result ((WriteGuard T) × (WriteGuard T → Unit))
  := do
  let (wg, _) ← Lock.write lock
  let back := fun wg1 => ()
  ok (wg, back)

/-- [lt_stateful_negative::AttributeOnStruct]
    Source: 'tests/src/lt-stateful-negative.rs', lines 580:0-582:1
    Visibility: public -/
structure AttributeOnStruct (T : Type) where
  marker : core.marker.PhantomData T

/-- [lt_stateful_negative::attribute_on_statement]:
    Source: 'tests/src/lt-stateful-negative.rs', lines 591:0-595:1
    Visibility: public -/
def attribute_on_statement {T : Type} (lock : Lock T) : Result Unit := do
  let guard ← Lock.read lock
  ReadGuard.release guard

end lt_stateful_negative
