-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_failures]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_failures

/-- [std::process::abort]:
    Source: '/rustc/library/std/src/process.rs', lines 2604:0-2604:19
    Name pattern: [std::process::abort]
    Visibility: public -/
@[rust_fun "std::process::abort"] axiom std.process.abort : Result Never

/-- [lt_stateful_failures::Lock]
    Source: 'tests/src/lt-stateful-failures.rs', lines 91:0-93:1
    Visibility: public -/
axiom Lock : Type

/-- [lt_stateful_failures::Guard]
    Source: 'tests/src/lt-stateful-failures.rs', lines 98:0-100:1
    Visibility: public -/
axiom Guard : Type

/-- [lt_stateful_failures::acquire]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 104:0-106:1
    Visibility: public -/
axiom acquire : Lock → Result Guard

/-- [lt_stateful_failures::release]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 110:0-112:1
    Visibility: public -/
axiom release : Guard → Result Unit

/-- [lt_stateful_failures::consume_guard]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 116:0-118:1
    Visibility: public -/
axiom consume_guard : Guard → Result Std.U32

/-- [lt_stateful_failures::overflow_add_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 126:0-128:1
    Visibility: public -/
def overflow_add_candidate (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  x + y

/-- [lt_stateful_failures::overflow_mul_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 131:0-133:1
    Visibility: public -/
def overflow_mul_candidate (x : Std.U16) (y : Std.U16) : Result Std.U16 := do
  x * y

/-- [lt_stateful_failures::underflow_sub_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 136:0-138:1
    Visibility: public -/
def underflow_sub_candidate (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  x - y

/-- [lt_stateful_failures::overflow_trio_plain_add]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 149:0-151:1
    Visibility: public -/
def overflow_trio_plain_add (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  x + y

/-- [lt_stateful_failures::overflow_trio_checked_add]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 158:0-160:1
    Visibility: public -/
def overflow_trio_checked_add
  (x : Std.U32) (y : Std.U32) : Result (Option Std.U32) := do
  ok (U32.checked_add x y)

/-- [lt_stateful_failures::overflow_trio_wrapping_add]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 166:0-168:1
    Visibility: public -/
def overflow_trio_wrapping_add
  (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  ok (core.num.U32.wrapping_add x y)

/-- [lt_stateful_failures::div_by_zero_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 175:0-177:1
    Visibility: public -/
def div_by_zero_candidate (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  x / y

/-- [lt_stateful_failures::rem_by_zero_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 180:0-182:1
    Visibility: public -/
def rem_by_zero_candidate (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  x % y

/-- [lt_stateful_failures::assert_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 190:0-193:1
    Visibility: public -/
def assert_candidate (x : Std.U32) : Result Std.U32 := do
  massert (x > 0#u32)
  x - 1#u32

/-- [lt_stateful_failures::debug_assert_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 202:0-205:1
    Visibility: public -/
def debug_assert_candidate (x : Std.U32) : Result Std.U32 := do
  massert (x > 0#u32)
  x - 1#u32

/-- [lt_stateful_failures::panic_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 209:0-215:1
    Visibility: public -/
def panic_candidate (flag : Bool) : Result Std.U32 := do
  massert (¬ flag)
  ok 0#u32

/-- [lt_stateful_failures::abort_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 220:0-225:1
    Visibility: public -/
def abort_candidate (x : Std.U32) : Result Std.U32 := do
  if x = 0#u32
  then let _ ← std.process.abort
       fail panic
  else x - 1#u32

/-- [lt_stateful_failures::index_out_of_bounds_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 233:0-235:1
    Visibility: public -/
def index_out_of_bounds_candidate
  (a : Array Std.U32 4#usize) (i : Std.Usize) : Result Std.U32 := do
  Array.index_usize a i

/-- [lt_stateful_failures::slice_index_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 238:0-240:1
    Visibility: public -/
def slice_index_candidate
  (s : Slice Std.U32) (i : Std.Usize) : Result Std.U32 := do
  Slice.index_usize s i

/-- [lt_stateful_failures::get_unwrap_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 245:0-247:1
    Visibility: public -/
def get_unwrap_candidate
  (s : Slice Std.U32) (i : Std.Usize) : Result Std.U32 := do
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.U32) s i
  core.option.Option.unwrap o

/-- [lt_stateful_failures::err_to_panic_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 255:0-258:1
    Visibility: public -/
def err_to_panic_candidate (x : Std.U32) : Result Std.U32 := do
  let r ←
    if x > 0#u32
    then ok (core.result.Result.Ok x)
    else ok (core.result.Result.Err 0#u32)
  core.result.Result.unwrap core.fmt.DebugU32 r

/-- [lt_stateful_failures::err_or_overflow_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 271:0-277:1
    Visibility: public -/
def err_or_overflow_candidate
  (x : Std.U32) (y : Std.U32) (fail_early : Bool) :
  Result (core.result.Result Std.U32 Std.U32)
  := do
  if fail_early
  then ok (core.result.Result.Err 2989#u32)
  else let i ← x + y
       ok (core.result.Result.Ok i)

/-- [lt_stateful_failures::none_or_overflow_candidate]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 283:0-289:1
    Visibility: public -/
def none_or_overflow_candidate
  (x : Std.U16) (y : Std.U16) (absent : Bool) : Result (Option Std.U16) := do
  if absent
  then ok none
  else let i ← x * y
       ok (some i)

/-- [lt_stateful_failures::fallible_external_call]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 298:0-300:1
    Visibility: public -/
axiom fallible_external_call
  : Std.U32 → Result (core.result.Result Std.U32 Std.U32)

/-- [lt_stateful_failures::call_fallible_external]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 314:0-317:1
    Visibility: public -/
def call_fallible_external
  (x : Std.U32) : Result (core.result.Result Std.U32 Std.U32) := do
  let r ← fallible_external_call x
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← val + 1#u32
    ok (core.result.Result.Ok i)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U32 (core.convert.FromSame Std.U32) residual

/-- [lt_stateful_failures::fallible_external_call_with_guard]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 324:0-326:1
    Visibility: public -/
axiom fallible_external_call_with_guard
  : Guard → Std.U32 → Result (core.result.Result Std.U32 Std.U32)

/-- [lt_stateful_failures::call_fallible_external_with_guard]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 333:0-337:1
    Visibility: public -/
def call_fallible_external_with_guard
  (lock : Lock) (x : Std.U32) :
  Result (core.result.Result Std.U32 Std.U32)
  := do
  let g ← acquire lock
  let r ← fallible_external_call_with_guard g x
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← val + 1#u32
    ok (core.result.Result.Ok i)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U32 (core.convert.FromSame Std.U32) residual

/-- [lt_stateful_failures::WrappedError]
    Source: 'tests/src/lt-stateful-failures.rs', lines 348:0-348:29
    Visibility: public -/
@[reducible]
def WrappedError := Std.U32

/-- [lt_stateful_failures::{impl core::fmt::Debug for lt_stateful_failures::WrappedError}::fmt]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 347:9-347:14
    Visibility: public -/
def WrappedError.Insts.CoreFmtDebug.fmt
  (self : WrappedError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "WrappedError") dyn

/-- Trait implementation: [lt_stateful_failures::{impl core::fmt::Debug for lt_stateful_failures::WrappedError}]
    Source: 'tests/src/lt-stateful-failures.rs', lines 347:9-347:14 -/
@[reducible]
def WrappedError.Insts.CoreFmtDebug : core.fmt.Debug WrappedError := {
  fmt := WrappedError.Insts.CoreFmtDebug.fmt
}

/-- [lt_stateful_failures::{impl core::convert::From<u32> for lt_stateful_failures::WrappedError}::from]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 351:4-353:5
    Visibility: public -/
def WrappedError.Insts.CoreConvertFromU32.from
  (e : Std.U32) : Result WrappedError := do
  ok e

/-- Trait implementation: [lt_stateful_failures::{impl core::convert::From<u32> for lt_stateful_failures::WrappedError}]
    Source: 'tests/src/lt-stateful-failures.rs', lines 350:0-354:1 -/
@[reducible]
def WrappedError.Insts.CoreConvertFromU32 : core.convert.From WrappedError
  Std.U32 := {
  «from» := WrappedError.Insts.CoreConvertFromU32.from
}

/-- [lt_stateful_failures::call_fallible_external_via_from]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 366:0-369:1
    Visibility: public -/
def call_fallible_external_via_from
  (x : Std.U32) : Result (core.result.Result Std.U32 WrappedError) := do
  let r ← fallible_external_call x
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← val + 1#u32
    ok (core.result.Result.Ok i)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U32 WrappedError.Insts.CoreConvertFromU32 residual

/-- [lt_stateful_failures::ScaledError]
    Source: 'tests/src/lt-stateful-failures.rs', lines 375:0-375:28
    Visibility: public -/
@[reducible]
def ScaledError := Std.U32

/-- [lt_stateful_failures::{impl core::fmt::Debug for lt_stateful_failures::ScaledError}::fmt]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 374:9-374:14
    Visibility: public -/
def ScaledError.Insts.CoreFmtDebug.fmt
  (self : ScaledError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self
  core.fmt.Formatter.debug_tuple_field1_finish f (toStr "ScaledError") dyn

/-- Trait implementation: [lt_stateful_failures::{impl core::fmt::Debug for lt_stateful_failures::ScaledError}]
    Source: 'tests/src/lt-stateful-failures.rs', lines 374:9-374:14 -/
@[reducible]
def ScaledError.Insts.CoreFmtDebug : core.fmt.Debug ScaledError := {
  fmt := ScaledError.Insts.CoreFmtDebug.fmt
}

/-- [lt_stateful_failures::{impl core::convert::From<u32> for lt_stateful_failures::ScaledError}::from]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 378:4-380:5
    Visibility: public -/
def ScaledError.Insts.CoreConvertFromU32.from
  (e : Std.U32) : Result ScaledError := do
  let i ← e * 1000000#u32
  ok i

/-- Trait implementation: [lt_stateful_failures::{impl core::convert::From<u32> for lt_stateful_failures::ScaledError}]
    Source: 'tests/src/lt-stateful-failures.rs', lines 377:0-381:1 -/
@[reducible]
def ScaledError.Insts.CoreConvertFromU32 : core.convert.From ScaledError
  Std.U32 := {
  «from» := ScaledError.Insts.CoreConvertFromU32.from
}

/-- [lt_stateful_failures::call_fallible_external_via_fallible_from]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 385:0-388:1
    Visibility: public -/
def call_fallible_external_via_fallible_from
  (x : Std.U32) : Result (core.result.Result Std.U32 ScaledError) := do
  let r ← fallible_external_call x
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    ok (core.result.Result.Ok val)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U32 ScaledError.Insts.CoreConvertFromU32 residual

/-- [lt_stateful_failures::fail_before_acquire]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 410:0-413:1
    Visibility: public -/
def fail_before_acquire (lock : Lock) (divisor : Std.U32) : Result Guard := do
  let _ ← 10#u32 / divisor
  acquire lock

/-- [lt_stateful_failures::fail_after_acquire]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 420:0-425:1
    Visibility: public -/
def fail_after_acquire (lock : Lock) (divisor : Std.U32) : Result Std.U32 := do
  let g ← acquire lock
  let r ← 10#u32 / divisor
  let _ ← consume_guard g
  ok r

/-- [lt_stateful_failures::try_before_acquire]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 444:0-447:1
    Visibility: public -/
def try_before_acquire
  (lock : Lock) (x : Std.U32) : Result (core.result.Result Guard Std.U32) := do
  let r ← fallible_external_call x
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    let g ← acquire lock
    ok (core.result.Result.Ok g)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Guard (core.convert.FromSame Std.U32) residual

/-- [lt_stateful_failures::try_after_acquire]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 454:0-458:1
    Visibility: public -/
def try_after_acquire
  (lock : Lock) (x : Std.U32) :
  Result (core.result.Result Std.U32 Std.U32)
  := do
  let g ← acquire lock
  let r ← fallible_external_call x
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← consume_guard g
    let i1 ← i + val
    ok (core.result.Result.Ok i1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U32 (core.convert.FromSame Std.U32) residual

/-- [lt_stateful_failures::fail_then_work_absorbed]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 492:0-496:1
    Visibility: public -/
def fail_then_work_absorbed (divisor : Std.U32) : Result Std.U32 := do
  let q ← 10#u32 / divisor
  ok (core.num.U32.wrapping_add q q)

/-- [lt_stateful_failures::nested_guard_scope_failure]:
    Source: 'tests/src/lt-stateful-failures.rs', lines 505:0-520:1
    Visibility: public -/
def nested_guard_scope_failure
  (outer_lock : Lock) (inner_lock : Lock) (i : Std.Usize)
  (arr : Array Std.U32 4#usize) :
  Result Std.U32
  := do
  let g_outer ← acquire outer_lock
  let g_inner ← acquire inner_lock
  let x ← Array.index_usize arr i
  let _ ← consume_guard g_inner
  let _ ← consume_guard g_outer
  ok x

end lt_stateful_failures
