-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_trait_known_failures]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace lt_stateful_trait_known_failures

/-- Trait declaration: [lt_stateful_trait_known_failures::StatefulUpdate]
    Source: 'tests/src/lt-stateful-trait-known-failures.rs', lines 10:0-13:1
    Visibility: public -/
structure StatefulUpdate (Self : Type) where
  update : Self → Std.I32 → Result Self

/-- [lt_stateful_trait_known_failures::StatefulCounter]
    Source: 'tests/src/lt-stateful-trait-known-failures.rs', lines 15:0-17:1
    Visibility: public -/
structure StatefulCounter where
  value : Std.I32

/-- [lt_stateful_trait_known_failures::{impl lt_stateful_trait_known_failures::StatefulUpdate for lt_stateful_trait_known_failures::StatefulCounter}::update]:
    Source: 'tests/src/lt-stateful-trait-known-failures.rs', lines 20:4-22:5
    Visibility: public -/
def StatefulCounter.Insts.Lt_stateful_trait_known_failuresStatefulUpdate.update
  (self : StatefulCounter) (value : Std.I32) : Result StatefulCounter := do
  ok { value }

end lt_stateful_trait_known_failures
