-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_optimizer_hostile]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_optimizer_hostile

/-- [lt_stateful_optimizer_hostile::Lock]
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 34:0-36:1
    Visibility: public -/
axiom Lock (T : Type) : Type

/-- [lt_stateful_optimizer_hostile::ReadGuard]
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 39:0-41:1
    Visibility: public -/
axiom ReadGuard (T : Type) : Type

/-- [lt_stateful_optimizer_hostile::WriteGuard]
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 44:0-46:1
    Visibility: public -/
axiom WriteGuard (T : Type) : Type

/-- [lt_stateful_optimizer_hostile::{lt_stateful_optimizer_hostile::Lock<T>}::read]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 51:4-53:5
    Visibility: public -/
axiom Lock.read
  {T : Type} :
  Lock T → Result ((ReadGuard T) × (ReadGuard T → Result Unit))

/-- [lt_stateful_optimizer_hostile::{lt_stateful_optimizer_hostile::Lock<T>}::write]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 57:4-59:5
    Visibility: public -/
axiom Lock.write
  {T : Type} :
  Lock T → Result ((WriteGuard T) × (WriteGuard T → Result Unit))

/-- [lt_stateful_optimizer_hostile::{lt_stateful_optimizer_hostile::ReadGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 64:4-66:5
    Visibility: public -/
axiom ReadGuard.get {T : Type} : ReadGuard T → Result T

/-- [lt_stateful_optimizer_hostile::{lt_stateful_optimizer_hostile::WriteGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 71:4-73:5
    Visibility: public -/
axiom WriteGuard.get {T : Type} : WriteGuard T → Result T

/-- [lt_stateful_optimizer_hostile::{lt_stateful_optimizer_hostile::WriteGuard<'a, T>}::get_mut]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 77:4-79:5
    Visibility: public -/
axiom WriteGuard.get_mut
  {T : Type} :
  WriteGuard T → Result (T × (T → Result (WriteGuard T)) × (WriteGuard T
    → Result (WriteGuard T)))

/-- [lt_stateful_optimizer_hostile::release_result_unused]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 92:0-98:1
    Visibility: public -/
def release_result_unused (lock : Lock Std.I32) : Result Std.I32 := do
  let p ← Lock.read lock
  let (guard, read_back) := p
  let _ ← ReadGuard.get guard
  read_back guard
  ok 7#i32

/-- [lt_stateful_optimizer_hostile::release_after_write_unused]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 105:0-111:1
    Visibility: public -/
def release_after_write_unused (lock : Lock Std.I32) : Result Std.I32 := do
  let p ← Lock.write lock
  let (guard, write_back) := p
  let t ← WriteGuard.get_mut guard
  let (_, get_mut_back, get_mut_back1) := t
  let guard1 ← get_mut_back 5#i32
  let guard2 ← get_mut_back1 guard1
  write_back guard2
  ok 0#i32

/-- [lt_stateful_optimizer_hostile::acquire_same_lock_twice]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 123:0-133:1
    Visibility: public -/
def acquire_same_lock_twice (lock : Lock Std.I32) : Result Std.I32 := do
  let p ← Lock.read lock
  let (guard, read_back) := p
  let first ← ReadGuard.get guard
  read_back guard
  let p1 ← Lock.read lock
  let (guard1, read_back1) := p1
  let second ← ReadGuard.get guard1
  read_back1 guard1
  first + second

/-- [lt_stateful_optimizer_hostile::write_same_constant_twice]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 140:0-149:1
    Visibility: public -/
def write_same_constant_twice (lock : Lock Std.I32) : Result Unit := do
  let p ← Lock.write lock
  let (guard, write_back) := p
  let t ← WriteGuard.get_mut guard
  let (_, get_mut_back, get_mut_back1) := t
  let guard1 ← get_mut_back 1#i32
  let guard2 ← get_mut_back1 guard1
  write_back guard2
  let p1 ← Lock.write lock
  let (guard3, write_back1) := p1
  let t1 ← WriteGuard.get_mut guard3
  let (_, get_mut_back2, get_mut_back3) := t1
  let guard4 ← get_mut_back2 1#i32
  let guard5 ← get_mut_back3 guard4
  write_back1 guard5

/-- [lt_stateful_optimizer_hostile::write_unit_payload]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 160:0-163:1
    Visibility: public -/
def write_unit_payload (lock : Lock Unit) : Result Unit := do
  let p ← Lock.write lock
  let (guard, write_back) := p
  let t ← WriteGuard.get_mut guard
  let (_, get_mut_back, get_mut_back1) := t
  let guard1 ← get_mut_back ()
  let guard2 ← get_mut_back1 guard1
  write_back guard2

/-- [lt_stateful_optimizer_hostile::conditional_acquire]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 173:0-180:1
    Visibility: public -/
def conditional_acquire
  (lock : Lock Std.I32) (take : Bool) : Result Std.I32 := do
  if take
  then
    let p ← Lock.read lock
    let (guard, read_back) := p
    let i ← ReadGuard.get guard
    read_back guard
    ok i
  else ok 0#i32

/-- [lt_stateful_optimizer_hostile::branch_acquires_different_locks]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 186:0-198:1
    Visibility: public -/
def branch_acquires_different_locks
  (first : Lock Std.I32) (second : Lock Std.I32) (use_first : Bool) :
  Result Std.I32
  := do
  if use_first
  then
    let p ← Lock.read first
    let (guard, read_back) := p
    let i ← ReadGuard.get guard
    read_back guard
    ok i
  else
    let p ← Lock.read second
    let (guard, read_back) := p
    let i ← ReadGuard.get guard
    read_back guard
    ok i

/-- [lt_stateful_optimizer_hostile::acquire_in_loop]: loop body 0:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 212:4-217:5
    Visibility: public -/
@[rust_loop_body]
def acquire_in_loop_loop.body
  (lock : Lock Std.I32) (count : Std.U32) (total : Std.U32) (index : Std.U32) :
  Result (ControlFlow (Std.U32 × Std.U32) Std.U32)
  := do
  if index < count
  then
    let p ← Lock.read lock
    let (guard, read_back) := p
    let _ ← ReadGuard.get guard
    let total1 ← total + 1#u32
    let index1 ← index + 1#u32
    read_back guard
    ok (cont (total1, index1))
  else ok (done total)

/-- [lt_stateful_optimizer_hostile::acquire_in_loop]: loop 0:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 212:4-217:5
    Visibility: public -/
@[rust_loop]
def acquire_in_loop_loop
  (lock : Lock Std.I32) (count : Std.U32) (total : Std.U32) (index : Std.U32) :
  Result Std.U32
  := do
  loop
    (fun (total1, index1) => acquire_in_loop_loop.body lock count total1
      index1)
    (total, index)

/-- [lt_stateful_optimizer_hostile::acquire_in_loop]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 209:0-219:1
    Visibility: public -/
@[reducible]
def acquire_in_loop
  (lock : Lock Std.I32) (count : Std.U32) : Result Std.U32 := do
  acquire_in_loop_loop lock count 0#u32 0#u32

/-- [lt_stateful_optimizer_hostile::three_nested_guards]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 229:0-234:1
    Visibility: public -/
def three_nested_guards
  (first : Lock Std.I32) (second : Lock Std.I32) (third : Lock Std.I32) :
  Result Std.I32
  := do
  let p ← Lock.read first
  let (first_guard, read_back) := p
  let p1 ← Lock.read second
  let (second_guard, read_back1) := p1
  let p2 ← Lock.read third
  let (third_guard, read_back2) := p2
  let i ← ReadGuard.get first_guard
  let i1 ← ReadGuard.get second_guard
  let i2 ← i + i1
  let i3 ← ReadGuard.get third_guard
  let i4 ← i2 + i3
  read_back2 third_guard
  read_back1 second_guard
  read_back first_guard
  ok i4

/-- [lt_stateful_optimizer_hostile::inner_scope_releases_first]:
    Source: 'tests/src/lt-stateful-optimizer-hostile.rs', lines 241:0-248:1
    Visibility: public -/
def inner_scope_releases_first
  (outer : Lock Std.I32) (inner : Lock Std.I32) : Result Std.I32 := do
  let p ← Lock.read outer
  let (outer_guard, read_back) := p
  let p1 ← Lock.read inner
  let (inner_guard, read_back1) := p1
  let _ ← ReadGuard.get inner_guard
  read_back1 inner_guard
  let i ← ReadGuard.get outer_guard
  read_back outer_guard
  ok i

end lt_stateful_optimizer_hostile
