-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_mini_themis_client]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_mini_themis_client

/-- [core::cmp::impls::{impl core::cmp::Ord for bool}::cmp]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2050:8-2050:47
    Name pattern: [core::cmp::impls::{core::cmp::Ord<bool>}::cmp]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::Ord<bool>}::cmp"]
axiom Bool.Insts.CoreCmpOrd.cmp : Bool → Bool → Result Ordering

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 811:0-811:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2793:4-2793:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [lt_stateful_mini_themis_client::my_std::RwLock]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 131:0-133:1
    Visibility: public -/
structure my_std.RwLock (T : Type) where
  marker : core.marker.PhantomData T

/-- [lt_stateful_mini_themis_client::my_std::Arc]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 71:0-73:1
    Visibility: public -/
structure my_std.Arc (T : Type) where
  marker : core.marker.PhantomData T

/-- [lt_stateful_mini_themis_client::my_std::Weak]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 75:0-77:1
    Visibility: public -/
structure my_std.Weak (T : Type) where
  marker : core.marker.PhantomData T

/-- [lt_stateful_mini_themis_client::my_std::Vec]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 5:0-7:1
    Visibility: public -/
structure my_std.Vec (T : Type) where
  marker : core.marker.PhantomData T

/-- [lt_stateful_mini_themis_client::mini_themis::Capability]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 8:0-17:1
    Visibility: public -/
inductive mini_themis.Capability (T : Type) where
| mk :
  Std.U64 →
  Std.U64 →
  Std.U64 →
  T →
  my_std.Weak (my_std.RwLock (mini_themis.Capability T)) →
  my_std.Vec (my_std.Arc (my_std.RwLock (mini_themis.Capability T))) →
  mini_themis.Capability T

def mini_themis.Capability.owner {T : Type} (x : mini_themis.Capability T) :=
  match x with | mini_themis.Capability.mk x1 _ _ _ _ _ => x1

def mini_themis.Capability.sub_handle {T : Type} (x : mini_themis.Capability T)
  :=
  match x with | mini_themis.Capability.mk _ x1 _ _ _ _ => x1

def mini_themis.Capability.next_sub_handle {T : Type} (x :
  mini_themis.Capability T) :=
  match x with | mini_themis.Capability.mk _ _ x1 _ _ _ => x1

def mini_themis.Capability.data {T : Type} (x : mini_themis.Capability T) :=
  match x with | mini_themis.Capability.mk _ _ _ x1 _ _ => x1

def mini_themis.Capability.parent {T : Type} (x : mini_themis.Capability T) :=
  match x with | mini_themis.Capability.mk _ _ _ _ x1 _ => x1

def mini_themis.Capability.children {T : Type} (x : mini_themis.Capability T)
  :=
  match x with | mini_themis.Capability.mk _ _ _ _ _ x1 => x1

@[simp]
theorem mini_themis.Capability.owner._simpLemma_ {T : Type} (owner : Std.U64)
  (sub_handle : Std.U64) (next_sub_handle : Std.U64) (data : T) (parent :
  my_std.Weak (my_std.RwLock (mini_themis.Capability T))) (children :
  my_std.Vec (my_std.Arc (my_std.RwLock (mini_themis.Capability T)))) :
  (mini_themis.Capability.mk
    owner
    sub_handle
    next_sub_handle
    data
    parent
    children).owner
    =
    owner := by rfl

@[simp]
theorem mini_themis.Capability.sub_handle._simpLemma_ {T : Type} (owner :
  Std.U64) (sub_handle : Std.U64) (next_sub_handle : Std.U64) (data : T)
  (parent : my_std.Weak (my_std.RwLock (mini_themis.Capability T))) (children :
  my_std.Vec (my_std.Arc (my_std.RwLock (mini_themis.Capability T)))) :
  (mini_themis.Capability.mk
    owner
    sub_handle
    next_sub_handle
    data
    parent
    children).sub_handle
    =
    sub_handle := by rfl

@[simp]
theorem mini_themis.Capability.next_sub_handle._simpLemma_ {T : Type} (owner :
  Std.U64) (sub_handle : Std.U64) (next_sub_handle : Std.U64) (data : T)
  (parent : my_std.Weak (my_std.RwLock (mini_themis.Capability T))) (children :
  my_std.Vec (my_std.Arc (my_std.RwLock (mini_themis.Capability T)))) :
  (mini_themis.Capability.mk
    owner
    sub_handle
    next_sub_handle
    data
    parent
    children).next_sub_handle
    =
    next_sub_handle := by rfl

@[simp]
theorem mini_themis.Capability.data._simpLemma_ {T : Type} (owner : Std.U64)
  (sub_handle : Std.U64) (next_sub_handle : Std.U64) (data : T) (parent :
  my_std.Weak (my_std.RwLock (mini_themis.Capability T))) (children :
  my_std.Vec (my_std.Arc (my_std.RwLock (mini_themis.Capability T)))) :
  (mini_themis.Capability.mk
    owner
    sub_handle
    next_sub_handle
    data
    parent
    children).data
    =
    data := by rfl

@[simp]
theorem mini_themis.Capability.parent._simpLemma_ {T : Type} (owner : Std.U64)
  (sub_handle : Std.U64) (next_sub_handle : Std.U64) (data : T) (parent :
  my_std.Weak (my_std.RwLock (mini_themis.Capability T))) (children :
  my_std.Vec (my_std.Arc (my_std.RwLock (mini_themis.Capability T)))) :
  (mini_themis.Capability.mk
    owner
    sub_handle
    next_sub_handle
    data
    parent
    children).parent
    =
    parent := by rfl

@[simp]
theorem mini_themis.Capability.children._simpLemma_ {T : Type} (owner :
  Std.U64) (sub_handle : Std.U64) (next_sub_handle : Std.U64) (data : T)
  (parent : my_std.Weak (my_std.RwLock (mini_themis.Capability T))) (children :
  my_std.Vec (my_std.Arc (my_std.RwLock (mini_themis.Capability T)))) :
  (mini_themis.Capability.mk
    owner
    sub_handle
    next_sub_handle
    data
    parent
    children).children
    =
    children := by rfl

/-- [lt_stateful_mini_themis_client::my_std::BTreeMap]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 40:0-42:1
    Visibility: public -/
structure my_std.BTreeMap (K : Type) (V : Type) where
  marker : core.marker.PhantomData (K × V)

/-- [lt_stateful_mini_themis_client::mini_themis::RegionStatus]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 161:0-164:1
    Visibility: public -/
@[discriminant isize]
inductive mini_themis.RegionStatus where
| Exclusive : mini_themis.RegionStatus
| Aliased : mini_themis.RegionStatus

/-- [lt_stateful_mini_themis_client::mini_themis::RegionKind]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 155:0-158:1
    Visibility: public -/
@[discriminant isize]
inductive mini_themis.RegionKind where
| Alias : mini_themis.RegionKind
| Carve : mini_themis.RegionKind

/-- [lt_stateful_mini_themis_client::mini_themis::Rights]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 140:0-144:1
    Visibility: public -/
structure mini_themis.Rights where
  read : Bool
  write : Bool
  execute : Bool

/-- [lt_stateful_mini_themis_client::mini_themis::Access]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 102:0-106:1
    Visibility: public -/
structure mini_themis.Access where
  start : Std.U64
  size : Std.U64
  rights : mini_themis.Rights

/-- [lt_stateful_mini_themis_client::mini_themis::MemoryRegion]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 167:0-171:1
    Visibility: public -/
structure mini_themis.MemoryRegion where
  kind : mini_themis.RegionKind
  status : mini_themis.RegionStatus
  access : mini_themis.Access

/-- [lt_stateful_mini_themis_client::mini_themis::DomainPolicy]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 88:0-90:1
    Visibility: public -/
structure mini_themis.DomainPolicy where
  lattice : Bool

/-- [lt_stateful_mini_themis_client::mini_themis::Domain]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 19:0-24:1
    Visibility: public -/
inductive mini_themis.Domain where
| mk :
  Std.U64 →
  mini_themis.DomainPolicy →
  my_std.BTreeMap Std.U64 (my_std.Weak (my_std.RwLock (mini_themis.Capability
    mini_themis.MemoryRegion))) →
  my_std.BTreeMap Std.U64 (my_std.Weak (my_std.RwLock (mini_themis.Capability
    mini_themis.Domain))) →
  mini_themis.Domain

def mini_themis.Domain.id (x : mini_themis.Domain) :=
  match x with | mini_themis.Domain.mk x1 _ _ _ => x1

def mini_themis.Domain.policy (x : mini_themis.Domain) :=
  match x with | mini_themis.Domain.mk _ x1 _ _ => x1

def mini_themis.Domain.memory_capabilities (x : mini_themis.Domain) :=
  match x with | mini_themis.Domain.mk _ _ x1 _ => x1

def mini_themis.Domain.domain_capabilities (x : mini_themis.Domain) :=
  match x with | mini_themis.Domain.mk _ _ _ x1 => x1

@[simp]
theorem mini_themis.Domain.id._simpLemma_ (id : Std.U64) (policy :
  mini_themis.DomainPolicy) (memory_capabilities : my_std.BTreeMap Std.U64
  (my_std.Weak (my_std.RwLock (mini_themis.Capability
  mini_themis.MemoryRegion)))) (domain_capabilities : my_std.BTreeMap Std.U64
  (my_std.Weak (my_std.RwLock (mini_themis.Capability mini_themis.Domain)))) :
  (mini_themis.Domain.mk
    id
    policy
    memory_capabilities
    domain_capabilities).id
    =
    id := by rfl

@[simp]
theorem mini_themis.Domain.policy._simpLemma_ (id : Std.U64) (policy :
  mini_themis.DomainPolicy) (memory_capabilities : my_std.BTreeMap Std.U64
  (my_std.Weak (my_std.RwLock (mini_themis.Capability
  mini_themis.MemoryRegion)))) (domain_capabilities : my_std.BTreeMap Std.U64
  (my_std.Weak (my_std.RwLock (mini_themis.Capability mini_themis.Domain)))) :
  (mini_themis.Domain.mk
    id
    policy
    memory_capabilities
    domain_capabilities).policy
    =
    policy := by rfl

@[simp]
theorem mini_themis.Domain.memory_capabilities._simpLemma_ (id : Std.U64)
  (policy : mini_themis.DomainPolicy) (memory_capabilities : my_std.BTreeMap
  Std.U64 (my_std.Weak (my_std.RwLock (mini_themis.Capability
  mini_themis.MemoryRegion)))) (domain_capabilities : my_std.BTreeMap Std.U64
  (my_std.Weak (my_std.RwLock (mini_themis.Capability mini_themis.Domain)))) :
  (mini_themis.Domain.mk
    id
    policy
    memory_capabilities
    domain_capabilities).memory_capabilities
    =
    memory_capabilities := by rfl

@[simp]
theorem mini_themis.Domain.domain_capabilities._simpLemma_ (id : Std.U64)
  (policy : mini_themis.DomainPolicy) (memory_capabilities : my_std.BTreeMap
  Std.U64 (my_std.Weak (my_std.RwLock (mini_themis.Capability
  mini_themis.MemoryRegion)))) (domain_capabilities : my_std.BTreeMap Std.U64
  (my_std.Weak (my_std.RwLock (mini_themis.Capability mini_themis.Domain)))) :
  (mini_themis.Domain.mk
    id
    policy
    memory_capabilities
    domain_capabilities).domain_capabilities
    =
    domain_capabilities := by rfl

/-- [lt_stateful_mini_themis_client::mini_themis::generate_domain_id]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 26:0-28:1
    Visibility: public -/
def mini_themis.generate_domain_id : Result Std.U64 := do
  fail panic

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::BTreeMap<K, V>}::new]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 46:4-48:5
    Visibility: public -/
axiom my_std.BTreeMap.new (K : Type) (V : Type) : Result (my_std.BTreeMap K V)

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Domain}::new]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 31:4-38:5 -/
def mini_themis.Domain.new
  (policy : mini_themis.DomainPolicy) : Result mini_themis.Domain := do
  let i ← mini_themis.generate_domain_id
  let bm ←
    my_std.BTreeMap.new Std.U64 (my_std.Weak (my_std.RwLock
      (mini_themis.Capability mini_themis.MemoryRegion)))
  let bm1 ←
    my_std.BTreeMap.new Std.U64 (my_std.Weak (my_std.RwLock
      (mini_themis.Capability mini_themis.Domain)))
  ok (mini_themis.Domain.mk i policy bm bm1)

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::BTreeMap<K, V>}::get]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 51:4-53:5
    Visibility: public -/
axiom my_std.BTreeMap.get
  {K : Type} {V : Type} : my_std.BTreeMap K V → K → Result (Option V)

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Domain}::get_domain_capability]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 40:4-42:5
    Visibility: public -/
def mini_themis.Domain.get_domain_capability
  (self : mini_themis.Domain) (handle : Std.U64) :
  Result (Option (my_std.Weak (my_std.RwLock (mini_themis.Capability
    mini_themis.Domain))))
  := do
  my_std.BTreeMap.get self.domain_capabilities handle

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Domain}::get_memory_capability]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 44:4-49:5
    Visibility: public -/
def mini_themis.Domain.get_memory_capability
  (self : mini_themis.Domain) (handle : Std.U64) :
  Result (Option (my_std.Weak (my_std.RwLock (mini_themis.Capability
    mini_themis.MemoryRegion))))
  := do
  my_std.BTreeMap.get self.memory_capabilities handle

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::BTreeMap<K, V>}::contains_key]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 56:4-58:5
    Visibility: public -/
axiom my_std.BTreeMap.contains_key
  {K : Type} {V : Type} : my_std.BTreeMap K V → K → Result Bool

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Domain}::allocate_memory_handle]: loop 0:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 53:8-55:9
    Visibility: public -/
@[rust_loop]
def mini_themis.Domain.allocate_memory_handle_loop
  (self : mini_themis.Domain) (handle : Std.U64) : Result Std.U64 := do
  let b ← my_std.BTreeMap.contains_key self.memory_capabilities handle
  if b
  then
    let handle1 ← handle + 1#u64
    mini_themis.Domain.allocate_memory_handle_loop self handle1
  else ok handle
partial_fixpoint

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Domain}::allocate_memory_handle]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 51:4-57:5
    Visibility: public -/
@[reducible]
def mini_themis.Domain.allocate_memory_handle
  (self : mini_themis.Domain) : Result Std.U64 := do
  mini_themis.Domain.allocate_memory_handle_loop self 1#u64

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::BTreeMap<K, V>}::insert]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 61:4-63:5
    Visibility: public -/
axiom my_std.BTreeMap.insert
  {K : Type} {V : Type} :
  my_std.BTreeMap K V → K → V → Result ((Option V) × (my_std.BTreeMap K
    V))

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Domain}::add_memory_capability]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 59:4-65:5
    Visibility: public -/
def mini_themis.Domain.add_memory_capability
  (self : mini_themis.Domain) (handle : Std.U64)
  (capa : my_std.Weak (my_std.RwLock (mini_themis.Capability
  mini_themis.MemoryRegion))) :
  Result mini_themis.Domain
  := do
  let p ← my_std.BTreeMap.insert self.memory_capabilities handle capa
  let (_, bm) := p
  ok (mini_themis.Domain.mk self.id self.policy bm self.domain_capabilities)

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::BTreeMap<K, V>}::remove]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 66:4-68:5
    Visibility: public -/
axiom my_std.BTreeMap.remove
  {K : Type} {V : Type} :
  my_std.BTreeMap K V → K → Result ((Option V) × (my_std.BTreeMap K V))

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Domain}::remove_memory_capability]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 67:4-73:5
    Visibility: public -/
def mini_themis.Domain.remove_memory_capability
  (self : mini_themis.Domain) (handle : Std.U64) :
  Result ((Option (my_std.Weak (my_std.RwLock (mini_themis.Capability
    mini_themis.MemoryRegion)))) × mini_themis.Domain)
  := do
  let p ← my_std.BTreeMap.remove self.memory_capabilities handle
  let (result, bm) := p
  ok (result, mini_themis.Domain.mk self.id self.policy bm
    self.domain_capabilities)

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Domain}::allocate_domain_handle]: loop 0:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 77:8-79:9
    Visibility: public -/
@[rust_loop]
def mini_themis.Domain.allocate_domain_handle_loop
  (self : mini_themis.Domain) (handle : Std.U64) : Result Std.U64 := do
  let b ← my_std.BTreeMap.contains_key self.domain_capabilities handle
  if b
  then
    let handle1 ← handle + 1#u64
    mini_themis.Domain.allocate_domain_handle_loop self handle1
  else ok handle
partial_fixpoint

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Domain}::allocate_domain_handle]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 75:4-81:5
    Visibility: public -/
@[reducible]
def mini_themis.Domain.allocate_domain_handle
  (self : mini_themis.Domain) : Result Std.U64 := do
  mini_themis.Domain.allocate_domain_handle_loop self 1#u64

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Domain}::add_domain_capability]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 83:4-85:5
    Visibility: public -/
def mini_themis.Domain.add_domain_capability
  (self : mini_themis.Domain) (handle : Std.U64)
  (capa : my_std.Weak (my_std.RwLock (mini_themis.Capability
  mini_themis.Domain))) :
  Result mini_themis.Domain
  := do
  let p ← my_std.BTreeMap.insert self.domain_capabilities handle capa
  let (_, bm) := p
  ok (mini_themis.Domain.mk self.id self.policy self.memory_capabilities bm)

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::DomainPolicy}::is_subset_of]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 93:4-99:5
    Visibility: public -/
def mini_themis.DomainPolicy.is_subset_of
  (self : mini_themis.DomainPolicy) (parent : mini_themis.DomainPolicy) :
  Result (Option Unit)
  := do
  if self.lattice <= parent.lattice
  then ok (some ())
  else ok none

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::fmt::Debug for lt_stateful_mini_themis_client::mini_themis::Rights}::fmt]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:9-139:14
    Visibility: public -/
def mini_themis.Rights.Insts.CoreFmtDebug.fmt
  (self : mini_themis.Rights) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugBool self.read
  let dyn1 := Dyn.mk _ core.fmt.DebugBool self.write
  let dyn2 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool) self.execute
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "Rights") (toStr
    "read") dyn (toStr "write") dyn1 (toStr "execute") dyn2

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::fmt::Debug for lt_stateful_mini_themis_client::mini_themis::Rights}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:9-139:14 -/
@[reducible]
def mini_themis.Rights.Insts.CoreFmtDebug : core.fmt.Debug mini_themis.Rights
  := {
  fmt := mini_themis.Rights.Insts.CoreFmtDebug.fmt
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::fmt::Debug for lt_stateful_mini_themis_client::mini_themis::Access}::fmt]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:9-101:14
    Visibility: public -/
def mini_themis.Access.Insts.CoreFmtDebug.fmt
  (self : mini_themis.Access) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.start
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.size
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared mini_themis.Rights.Insts.CoreFmtDebug)
      self.rights
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "Access") (toStr
    "start") dyn (toStr "size") dyn1 (toStr "rights") dyn2

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::fmt::Debug for lt_stateful_mini_themis_client::mini_themis::Access}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:9-101:14 -/
@[reducible]
def mini_themis.Access.Insts.CoreFmtDebug : core.fmt.Debug mini_themis.Access
  := {
  fmt := mini_themis.Access.Insts.CoreFmtDebug.fmt
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::clone::Clone for lt_stateful_mini_themis_client::mini_themis::Access}::clone]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:16-101:21
    Visibility: public -/
def mini_themis.Access.Insts.CoreCloneClone.clone
  (self : mini_themis.Access) : Result mini_themis.Access := do
  ok self

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::clone::Clone for lt_stateful_mini_themis_client::mini_themis::Access}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:16-101:21 -/
@[reducible]
def mini_themis.Access.Insts.CoreCloneClone : core.clone.Clone
  mini_themis.Access := {
  clone := mini_themis.Access.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::marker::Copy for lt_stateful_mini_themis_client::mini_themis::Access}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:23-101:27 -/
@[reducible]
def mini_themis.Access.Insts.CoreMarkerCopy : core.marker.Copy
  mini_themis.Access := {
  cloneInst := mini_themis.Access.Insts.CoreCloneClone
}

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::marker::StructuralPartialEq for lt_stateful_mini_themis_client::mini_themis::Access}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:29-101:38 -/
@[reducible]
def mini_themis.Access.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq mini_themis.Access := {
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::PartialEq<lt_stateful_mini_themis_client::mini_themis::Rights> for lt_stateful_mini_themis_client::mini_themis::Rights}::eq]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:29-139:38
    Visibility: public -/
def mini_themis.Rights.Insts.CoreCmpPartialEqRights.eq
  (self : mini_themis.Rights) (other : mini_themis.Rights) : Result Bool := do
  if self.read = other.read
  then
    if self.write = other.write
    then ok (self.execute = other.execute)
    else ok false
  else ok false

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::PartialEq<lt_stateful_mini_themis_client::mini_themis::Access> for lt_stateful_mini_themis_client::mini_themis::Access}::eq]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:29-101:38
    Visibility: public -/
def mini_themis.Access.Insts.CoreCmpPartialEqAccess.eq
  (self : mini_themis.Access) (other : mini_themis.Access) : Result Bool := do
  if self.start = other.start
  then
    if self.size = other.size
    then
      mini_themis.Rights.Insts.CoreCmpPartialEqRights.eq self.rights
        other.rights
    else ok false
  else ok false

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::PartialEq<lt_stateful_mini_themis_client::mini_themis::Access> for lt_stateful_mini_themis_client::mini_themis::Access}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:29-101:38 -/
@[reducible]
def mini_themis.Access.Insts.CoreCmpPartialEqAccess : core.cmp.PartialEq
  mini_themis.Access mini_themis.Access := {
  eq := mini_themis.Access.Insts.CoreCmpPartialEqAccess.eq
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::Eq for lt_stateful_mini_themis_client::mini_themis::Access}::assert_fields_are_eq]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:40-101:42
    Visibility: public -/
def mini_themis.Access.Insts.CoreCmpEq.assert_fields_are_eq
  (self : mini_themis.Access) : Result Unit := do
  ok ()

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::Eq for lt_stateful_mini_themis_client::mini_themis::Access}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:40-101:42 -/
@[reducible]
def mini_themis.Access.Insts.CoreCmpEq : core.cmp.Eq mini_themis.Access := {
  partialEqInst := mini_themis.Access.Insts.CoreCmpPartialEqAccess
  assert_fields_are_eq :=
    mini_themis.Access.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::Ord for lt_stateful_mini_themis_client::mini_themis::Rights}::cmp]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:56-139:59
    Visibility: public -/
def mini_themis.Rights.Insts.CoreCmpOrd.cmp
  (self : mini_themis.Rights) (other : mini_themis.Rights) :
  Result Ordering
  := do
  let o ← Bool.Insts.CoreCmpOrd.cmp self.read other.read
  match o with
  | Ordering.lt => ok Ordering.lt
  | Ordering.eq =>
    let o1 ← Bool.Insts.CoreCmpOrd.cmp self.write other.write
    match o1 with
    | Ordering.lt => ok Ordering.lt
    | Ordering.eq => Bool.Insts.CoreCmpOrd.cmp self.execute other.execute
    | Ordering.gt => ok Ordering.gt
  | Ordering.gt => ok Ordering.gt

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::Ord for lt_stateful_mini_themis_client::mini_themis::Access}::cmp]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:56-101:59
    Visibility: public -/
def mini_themis.Access.Insts.CoreCmpOrd.cmp
  (self : mini_themis.Access) (other : mini_themis.Access) :
  Result Ordering
  := do
  let o ← lift (core.cmp.impls.OrdU64.cmp self.start other.start)
  match o with
  | Ordering.lt => ok Ordering.lt
  | Ordering.eq =>
    let o1 ← lift (core.cmp.impls.OrdU64.cmp self.size other.size)
    match o1 with
    | Ordering.lt => ok Ordering.lt
    | Ordering.eq =>
      mini_themis.Rights.Insts.CoreCmpOrd.cmp self.rights other.rights
    | Ordering.gt => ok Ordering.gt
  | Ordering.gt => ok Ordering.gt

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::PartialOrd<lt_stateful_mini_themis_client::mini_themis::Access> for lt_stateful_mini_themis_client::mini_themis::Access}::partial_cmp]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:44-101:54
    Visibility: public -/
def mini_themis.Access.Insts.CoreCmpPartialOrdAccess.partial_cmp
  (self : mini_themis.Access) (other : mini_themis.Access) :
  Result (Option Ordering)
  := do
  let o ← mini_themis.Access.Insts.CoreCmpOrd.cmp self other
  ok (some o)

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::PartialOrd<lt_stateful_mini_themis_client::mini_themis::Access> for lt_stateful_mini_themis_client::mini_themis::Access}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:44-101:54 -/
@[reducible]
def mini_themis.Access.Insts.CoreCmpPartialOrdAccess : core.cmp.PartialOrd
  mini_themis.Access mini_themis.Access := {
  partialEqInst := mini_themis.Access.Insts.CoreCmpPartialEqAccess
  partial_cmp := mini_themis.Access.Insts.CoreCmpPartialOrdAccess.partial_cmp
}

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::Ord for lt_stateful_mini_themis_client::mini_themis::Access}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 101:56-101:59 -/
@[reducible]
def mini_themis.Access.Insts.CoreCmpOrd : core.cmp.Ord mini_themis.Access := {
  eqInst := mini_themis.Access.Insts.CoreCmpEq
  partialOrdInst := mini_themis.Access.Insts.CoreCmpPartialOrdAccess
  cmp := mini_themis.Access.Insts.CoreCmpOrd.cmp
}

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Access}::new]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 110:4-116:5
    Visibility: public -/
def mini_themis.Access.new
  (start : Std.U64) (size : Std.U64) (rights : mini_themis.Rights) :
  Result mini_themis.Access
  := do
  ok { start, size, rights }

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Access}::end]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 118:4-120:5
    Visibility: public -/
def mini_themis.Access.end (self : mini_themis.Access) : Result Std.U64 := do
  self.start + self.size

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Access}::contained_in]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 122:4-124:5
    Visibility: public -/
def mini_themis.Access.contained_in
  (self : mini_themis.Access) (other : mini_themis.Access) : Result Bool := do
  if self.start >= other.start
  then
    let i ← mini_themis.Access.end self
    let i1 ← mini_themis.Access.end other
    ok (i <= i1)
  else ok false

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Access}::overlaps]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 126:4-132:5
    Visibility: public -/
def mini_themis.Access.overlaps
  (self : mini_themis.Access) (other : mini_themis.Access) : Result Bool := do
  let i ← mini_themis.Access.end self
  if i <= other.start
  then ok false
  else let i1 ← mini_themis.Access.end other
       ok (self.start < i1)

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Rights}::is_subset_of]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 147:4-151:5
    Visibility: public -/
def mini_themis.Rights.is_subset_of
  (self : mini_themis.Rights) (other : mini_themis.Rights) : Result Bool := do
  if self.read
  then
    if other.read
    then
      if self.write
      then
        if other.write
        then if self.execute
             then ok other.execute
             else ok true
        else ok false
      else if self.execute
           then ok other.execute
           else ok true
    else ok false
  else
    if self.write
    then
      if other.write
      then if self.execute
           then ok other.execute
           else ok true
      else ok false
    else if self.execute
         then ok other.execute
         else ok true

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Access}::rights_subset_of]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 134:4-136:5
    Visibility: public -/
def mini_themis.Access.rights_subset_of
  (self : mini_themis.Access) (other : mini_themis.Access) : Result Bool := do
  mini_themis.Rights.is_subset_of self.rights other.rights

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::clone::Clone for lt_stateful_mini_themis_client::mini_themis::Rights}::clone]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:16-139:21
    Visibility: public -/
def mini_themis.Rights.Insts.CoreCloneClone.clone
  (self : mini_themis.Rights) : Result mini_themis.Rights := do
  ok self

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::clone::Clone for lt_stateful_mini_themis_client::mini_themis::Rights}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:16-139:21 -/
@[reducible]
def mini_themis.Rights.Insts.CoreCloneClone : core.clone.Clone
  mini_themis.Rights := {
  clone := mini_themis.Rights.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::marker::Copy for lt_stateful_mini_themis_client::mini_themis::Rights}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:23-139:27 -/
@[reducible]
def mini_themis.Rights.Insts.CoreMarkerCopy : core.marker.Copy
  mini_themis.Rights := {
  cloneInst := mini_themis.Rights.Insts.CoreCloneClone
}

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::marker::StructuralPartialEq for lt_stateful_mini_themis_client::mini_themis::Rights}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:29-139:38 -/
@[reducible]
def mini_themis.Rights.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq mini_themis.Rights := {
}

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::PartialEq<lt_stateful_mini_themis_client::mini_themis::Rights> for lt_stateful_mini_themis_client::mini_themis::Rights}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:29-139:38 -/
@[reducible]
def mini_themis.Rights.Insts.CoreCmpPartialEqRights : core.cmp.PartialEq
  mini_themis.Rights mini_themis.Rights := {
  eq := mini_themis.Rights.Insts.CoreCmpPartialEqRights.eq
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::Eq for lt_stateful_mini_themis_client::mini_themis::Rights}::assert_fields_are_eq]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:40-139:42
    Visibility: public -/
def mini_themis.Rights.Insts.CoreCmpEq.assert_fields_are_eq
  (self : mini_themis.Rights) : Result Unit := do
  ok ()

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::Eq for lt_stateful_mini_themis_client::mini_themis::Rights}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:40-139:42 -/
@[reducible]
def mini_themis.Rights.Insts.CoreCmpEq : core.cmp.Eq mini_themis.Rights := {
  partialEqInst := mini_themis.Rights.Insts.CoreCmpPartialEqRights
  assert_fields_are_eq :=
    mini_themis.Rights.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::PartialOrd<lt_stateful_mini_themis_client::mini_themis::Rights> for lt_stateful_mini_themis_client::mini_themis::Rights}::partial_cmp]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:44-139:54
    Visibility: public -/
def mini_themis.Rights.Insts.CoreCmpPartialOrdRights.partial_cmp
  (self : mini_themis.Rights) (other : mini_themis.Rights) :
  Result (Option Ordering)
  := do
  let o ← mini_themis.Rights.Insts.CoreCmpOrd.cmp self other
  ok (some o)

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::PartialOrd<lt_stateful_mini_themis_client::mini_themis::Rights> for lt_stateful_mini_themis_client::mini_themis::Rights}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:44-139:54 -/
@[reducible]
def mini_themis.Rights.Insts.CoreCmpPartialOrdRights : core.cmp.PartialOrd
  mini_themis.Rights mini_themis.Rights := {
  partialEqInst := mini_themis.Rights.Insts.CoreCmpPartialEqRights
  partial_cmp := mini_themis.Rights.Insts.CoreCmpPartialOrdRights.partial_cmp
}

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::Ord for lt_stateful_mini_themis_client::mini_themis::Rights}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 139:56-139:59 -/
@[reducible]
def mini_themis.Rights.Insts.CoreCmpOrd : core.cmp.Ord mini_themis.Rights := {
  eqInst := mini_themis.Rights.Insts.CoreCmpEq
  partialOrdInst := mini_themis.Rights.Insts.CoreCmpPartialOrdRights
  cmp := mini_themis.Rights.Insts.CoreCmpOrd.cmp
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::fmt::Debug for lt_stateful_mini_themis_client::mini_themis::RegionKind}::fmt]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 154:9-154:14
    Visibility: public -/
def mini_themis.RegionKind.Insts.CoreFmtDebug.fmt
  (self : mini_themis.RegionKind) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | mini_themis.RegionKind.Alias =>
    core.fmt.Formatter.write_str f (toStr "Alias")
  | mini_themis.RegionKind.Carve =>
    core.fmt.Formatter.write_str f (toStr "Carve")

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::fmt::Debug for lt_stateful_mini_themis_client::mini_themis::RegionKind}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 154:9-154:14 -/
@[reducible]
def mini_themis.RegionKind.Insts.CoreFmtDebug : core.fmt.Debug
  mini_themis.RegionKind := {
  fmt := mini_themis.RegionKind.Insts.CoreFmtDebug.fmt
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::clone::Clone for lt_stateful_mini_themis_client::mini_themis::RegionKind}::clone]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 154:16-154:21
    Visibility: public -/
def mini_themis.RegionKind.Insts.CoreCloneClone.clone
  (self : mini_themis.RegionKind) : Result mini_themis.RegionKind := do
  ok self

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::clone::Clone for lt_stateful_mini_themis_client::mini_themis::RegionKind}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 154:16-154:21 -/
@[reducible]
def mini_themis.RegionKind.Insts.CoreCloneClone : core.clone.Clone
  mini_themis.RegionKind := {
  clone := mini_themis.RegionKind.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::marker::Copy for lt_stateful_mini_themis_client::mini_themis::RegionKind}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 154:23-154:27 -/
@[reducible]
def mini_themis.RegionKind.Insts.CoreMarkerCopy : core.marker.Copy
  mini_themis.RegionKind := {
  cloneInst := mini_themis.RegionKind.Insts.CoreCloneClone
}

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::marker::StructuralPartialEq for lt_stateful_mini_themis_client::mini_themis::RegionKind}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 154:29-154:38 -/
@[reducible]
def mini_themis.RegionKind.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq mini_themis.RegionKind := {
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::PartialEq<lt_stateful_mini_themis_client::mini_themis::RegionKind> for lt_stateful_mini_themis_client::mini_themis::RegionKind}::eq]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 154:29-154:38
    Visibility: public -/
def mini_themis.RegionKind.Insts.CoreCmpPartialEqRegionKind.eq
  (self : mini_themis.RegionKind) (other : mini_themis.RegionKind) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::PartialEq<lt_stateful_mini_themis_client::mini_themis::RegionKind> for lt_stateful_mini_themis_client::mini_themis::RegionKind}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 154:29-154:38 -/
@[reducible]
def mini_themis.RegionKind.Insts.CoreCmpPartialEqRegionKind :
  core.cmp.PartialEq mini_themis.RegionKind mini_themis.RegionKind := {
  eq := mini_themis.RegionKind.Insts.CoreCmpPartialEqRegionKind.eq
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::Eq for lt_stateful_mini_themis_client::mini_themis::RegionKind}::assert_fields_are_eq]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 154:40-154:42
    Visibility: public -/
def mini_themis.RegionKind.Insts.CoreCmpEq.assert_fields_are_eq
  (self : mini_themis.RegionKind) : Result Unit := do
  ok ()

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::Eq for lt_stateful_mini_themis_client::mini_themis::RegionKind}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 154:40-154:42 -/
@[reducible]
def mini_themis.RegionKind.Insts.CoreCmpEq : core.cmp.Eq mini_themis.RegionKind
  := {
  partialEqInst := mini_themis.RegionKind.Insts.CoreCmpPartialEqRegionKind
  assert_fields_are_eq :=
    mini_themis.RegionKind.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::fmt::Debug for lt_stateful_mini_themis_client::mini_themis::RegionStatus}::fmt]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 160:9-160:14
    Visibility: public -/
def mini_themis.RegionStatus.Insts.CoreFmtDebug.fmt
  (self : mini_themis.RegionStatus) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | mini_themis.RegionStatus.Exclusive =>
    core.fmt.Formatter.write_str f (toStr "Exclusive")
  | mini_themis.RegionStatus.Aliased =>
    core.fmt.Formatter.write_str f (toStr "Aliased")

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::fmt::Debug for lt_stateful_mini_themis_client::mini_themis::RegionStatus}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 160:9-160:14 -/
@[reducible]
def mini_themis.RegionStatus.Insts.CoreFmtDebug : core.fmt.Debug
  mini_themis.RegionStatus := {
  fmt := mini_themis.RegionStatus.Insts.CoreFmtDebug.fmt
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::clone::Clone for lt_stateful_mini_themis_client::mini_themis::RegionStatus}::clone]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 160:16-160:21
    Visibility: public -/
def mini_themis.RegionStatus.Insts.CoreCloneClone.clone
  (self : mini_themis.RegionStatus) : Result mini_themis.RegionStatus := do
  ok self

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::clone::Clone for lt_stateful_mini_themis_client::mini_themis::RegionStatus}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 160:16-160:21 -/
@[reducible]
def mini_themis.RegionStatus.Insts.CoreCloneClone : core.clone.Clone
  mini_themis.RegionStatus := {
  clone := mini_themis.RegionStatus.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::marker::Copy for lt_stateful_mini_themis_client::mini_themis::RegionStatus}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 160:23-160:27 -/
@[reducible]
def mini_themis.RegionStatus.Insts.CoreMarkerCopy : core.marker.Copy
  mini_themis.RegionStatus := {
  cloneInst := mini_themis.RegionStatus.Insts.CoreCloneClone
}

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::marker::StructuralPartialEq for lt_stateful_mini_themis_client::mini_themis::RegionStatus}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 160:29-160:38 -/
@[reducible]
def mini_themis.RegionStatus.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq mini_themis.RegionStatus := {
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::PartialEq<lt_stateful_mini_themis_client::mini_themis::RegionStatus> for lt_stateful_mini_themis_client::mini_themis::RegionStatus}::eq]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 160:29-160:38
    Visibility: public -/
def mini_themis.RegionStatus.Insts.CoreCmpPartialEqRegionStatus.eq
  (self : mini_themis.RegionStatus) (other : mini_themis.RegionStatus) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::PartialEq<lt_stateful_mini_themis_client::mini_themis::RegionStatus> for lt_stateful_mini_themis_client::mini_themis::RegionStatus}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 160:29-160:38 -/
@[reducible]
def mini_themis.RegionStatus.Insts.CoreCmpPartialEqRegionStatus :
  core.cmp.PartialEq mini_themis.RegionStatus mini_themis.RegionStatus := {
  eq := mini_themis.RegionStatus.Insts.CoreCmpPartialEqRegionStatus.eq
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::Eq for lt_stateful_mini_themis_client::mini_themis::RegionStatus}::assert_fields_are_eq]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 160:40-160:42
    Visibility: public -/
def mini_themis.RegionStatus.Insts.CoreCmpEq.assert_fields_are_eq
  (self : mini_themis.RegionStatus) : Result Unit := do
  ok ()

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::cmp::Eq for lt_stateful_mini_themis_client::mini_themis::RegionStatus}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 160:40-160:42 -/
@[reducible]
def mini_themis.RegionStatus.Insts.CoreCmpEq : core.cmp.Eq
  mini_themis.RegionStatus := {
  partialEqInst := mini_themis.RegionStatus.Insts.CoreCmpPartialEqRegionStatus
  assert_fields_are_eq :=
    mini_themis.RegionStatus.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::fmt::Debug for lt_stateful_mini_themis_client::mini_themis::MemoryRegion}::fmt]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 166:9-166:14
    Visibility: public -/
def mini_themis.MemoryRegion.Insts.CoreFmtDebug.fmt
  (self : mini_themis.MemoryRegion) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ mini_themis.RegionKind.Insts.CoreFmtDebug self.kind
  let dyn1 := Dyn.mk _ mini_themis.RegionStatus.Insts.CoreFmtDebug self.status
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared mini_themis.Access.Insts.CoreFmtDebug)
      self.access
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "MemoryRegion") (toStr
    "kind") dyn (toStr "status") dyn1 (toStr "access") dyn2

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::fmt::Debug for lt_stateful_mini_themis_client::mini_themis::MemoryRegion}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 166:9-166:14 -/
@[reducible]
def mini_themis.MemoryRegion.Insts.CoreFmtDebug : core.fmt.Debug
  mini_themis.MemoryRegion := {
  fmt := mini_themis.MemoryRegion.Insts.CoreFmtDebug.fmt
}

/-- [lt_stateful_mini_themis_client::mini_themis::{impl core::clone::Clone for lt_stateful_mini_themis_client::mini_themis::MemoryRegion}::clone]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 166:16-166:21
    Visibility: public -/
def mini_themis.MemoryRegion.Insts.CoreCloneClone.clone
  (self : mini_themis.MemoryRegion) : Result mini_themis.MemoryRegion := do
  let rk ← mini_themis.RegionKind.Insts.CoreCloneClone.clone self.kind
  let rs ← mini_themis.RegionStatus.Insts.CoreCloneClone.clone self.status
  let a ← mini_themis.Access.Insts.CoreCloneClone.clone self.access
  ok { kind := rk, status := rs, access := a }

/-- Trait implementation: [lt_stateful_mini_themis_client::mini_themis::{impl core::clone::Clone for lt_stateful_mini_themis_client::mini_themis::MemoryRegion}]
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 166:16-166:21 -/
@[reducible]
def mini_themis.MemoryRegion.Insts.CoreCloneClone : core.clone.Clone
  mini_themis.MemoryRegion := {
  clone := mini_themis.MemoryRegion.Insts.CoreCloneClone.clone
}

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::MemoryRegion}::alias]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 173:4-189:5
    Visibility: public -/
def mini_themis.MemoryRegion.alias
  (self : mini_themis.MemoryRegion) (access : mini_themis.Access) :
  Result (Option mini_themis.MemoryRegion)
  := do
  let b ← mini_themis.Access.contained_in access self.access
  if b
  then
    let b1 ← mini_themis.Access.rights_subset_of access self.access
    if b1
    then
      ok (some
        {
          kind := mini_themis.RegionKind.Alias,
          status := mini_themis.RegionStatus.Aliased,
          access
        })
    else ok none
  else ok none

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::MemoryRegion}::carve]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 191:4-208:5
    Visibility: public -/
def mini_themis.MemoryRegion.carve
  (self : mini_themis.MemoryRegion) (access : mini_themis.Access) :
  Result (Option mini_themis.MemoryRegion)
  := do
  let b ← mini_themis.Access.contained_in access self.access
  if b
  then
    let b1 ← mini_themis.Access.rights_subset_of access self.access
    if b1
    then ok (some { self with kind := mini_themis.RegionKind.Carve, access })
    else ok none
  else ok none

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::RwLock<T>}::new]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 147:4-149:5
    Visibility: public -/
axiom my_std.RwLock.new {T : Type} : T → Result (my_std.RwLock T)

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::Weak<T>}::new]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 109:4-111:5
    Visibility: public -/
axiom my_std.Weak.new (T : Type) : Result (my_std.Weak T)

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::Arc<T>}::new]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 81:4-83:5
    Visibility: public -/
axiom my_std.Arc.new {T : Type} : T → Result (my_std.Arc T)

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::Vec<T>}::new]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 11:4-13:5
    Visibility: public -/
axiom my_std.Vec.new (T : Type) : Result (my_std.Vec T)

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<T>}::new_root]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 212:4-221:5
    Visibility: public -/
def mini_themis.Capability.new_root
  {T : Type} (owner : Std.U64) (data : T) (handle : Std.U64) :
  Result (my_std.Arc (my_std.RwLock (mini_themis.Capability T)))
  := do
  let w ← my_std.Weak.new (my_std.RwLock (mini_themis.Capability T))
  let v ←
    my_std.Vec.new (my_std.Arc (my_std.RwLock (mini_themis.Capability T)))
  let rl ←
    my_std.RwLock.new (mini_themis.Capability.mk owner handle 1#u64 data w v)
  my_std.Arc.new rl

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<T>}::new_child]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 223:4-237:5
    Visibility: public -/
def mini_themis.Capability.new_child
  {T : Type} (owner : Std.U64) (data : T) (handle : Std.U64)
  (parent : my_std.Weak (my_std.RwLock (mini_themis.Capability T))) :
  Result (my_std.Arc (my_std.RwLock (mini_themis.Capability T)))
  := do
  let v ←
    my_std.Vec.new (my_std.Arc (my_std.RwLock (mini_themis.Capability T)))
  let rl ←
    my_std.RwLock.new (mini_themis.Capability.mk owner handle 1#u64 data parent
      v)
  my_std.Arc.new rl

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::Vec<T>}::push]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 21:4-23:5
    Visibility: public -/
axiom my_std.Vec.push {T : Type} : my_std.Vec T → T → Result (my_std.Vec T)

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<T>}::add_child]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 239:4-241:5
    Visibility: public -/
def mini_themis.Capability.add_child
  {T : Type} (self : mini_themis.Capability T)
  (child : my_std.Arc (my_std.RwLock (mini_themis.Capability T))) :
  Result (mini_themis.Capability T)
  := do
  let v ← my_std.Vec.push self.children child
  ok (mini_themis.Capability.mk self.owner self.sub_handle self.next_sub_handle
    self.data self.parent v)

/-- [lt_stateful_mini_themis_client::my_std::RwLockReadGuard]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 136:0-138:1
    Visibility: public -/
axiom my_std.RwLockReadGuard (T : Type) : Type

/-- [lt_stateful_mini_themis_client::my_std::{impl core::ops::deref::Deref<T> for lt_stateful_mini_themis_client::my_std::RwLockReadGuard<'_0, T>}::deref]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 168:4-170:5
    Visibility: public -/
axiom my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref
  {T : Type} : my_std.RwLockReadGuard T → Result T

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::RwLock<T>}::read]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 153:4-155:5
    Visibility: public -/
axiom my_std.RwLock.read
  {T : Type} :
  my_std.RwLock T → Result ((my_std.RwLockReadGuard T) ×
    (my_std.RwLockReadGuard T → Result Unit))

/-- [lt_stateful_mini_themis_client::my_std::{impl core::ops::drop::Drop for lt_stateful_mini_themis_client::my_std::RwLockReadGuard<'_0, T>}::drop]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 176:4-178:5
    Visibility: public -/
axiom my_std.RwLockReadGuard.Insts.CoreOpsDropDrop.drop
  {T : Type} :
  my_std.RwLockReadGuard T → Result ((my_std.RwLockReadGuard T) × (Result
    Unit))

/-- [lt_stateful_mini_themis_client::my_std::{impl core::ops::deref::Deref<T> for lt_stateful_mini_themis_client::my_std::Arc<T>}::deref]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 102:4-104:5
    Visibility: public -/
axiom my_std.Arc.Insts.CoreOpsDerefDeref.deref
  {T : Type} : my_std.Arc T → Result T

/-- [lt_stateful_mini_themis_client::my_std::{impl core::ops::index::Index<usize, T> for lt_stateful_mini_themis_client::my_std::Vec<T>}::index]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 35:4-37:5
    Visibility: public -/
axiom my_std.Vec.Insts.CoreOpsIndexIndexUsizeT.index
  {T : Type} : my_std.Vec T → Std.Usize → Result T

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::Vec<T>}::remove]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 26:4-28:5
    Visibility: public -/
axiom my_std.Vec.remove
  {T : Type} : my_std.Vec T → Std.Usize → Result (T × (my_std.Vec T))

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::Vec<T>}::len]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 16:4-18:5
    Visibility: public -/
axiom my_std.Vec.len {T : Type} : my_std.Vec T → Result Std.Usize

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<T>}::remove_child]: loop 0:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 245:8-252:5
    Visibility: public -/
@[rust_loop]
def mini_themis.Capability.remove_child_loop
  {T : Type} (self : mini_themis.Capability T) (child_sub : Std.U64)
  (pos : Std.Usize) :
  Result ((Option (my_std.Arc (my_std.RwLock (mini_themis.Capability T)))) ×
    Std.U64 × Std.U64 × Std.U64 × T × (my_std.Weak (my_std.RwLock
    (mini_themis.Capability T))) × (my_std.Vec (my_std.Arc (my_std.RwLock
    (mini_themis.Capability T)))))
  := do
  let i ← my_std.Vec.len self.children
  if pos < i
  then
    let a ← my_std.Vec.Insts.CoreOpsIndexIndexUsizeT.index self.children pos
    let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref a
    let p ← my_std.RwLock.read rl
    let (rlrg, read_back) := p
    let c ← my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref rlrg
    if c.sub_handle = child_sub
    then
      read_back rlrg
      let p1 ← my_std.Vec.remove self.children pos
      let (a1, v) := p1
      ok (some a1, self.owner, self.sub_handle, self.next_sub_handle,
        self.data, self.parent, v)
    else
      read_back rlrg
      let pos1 ← pos + 1#usize
      mini_themis.Capability.remove_child_loop self child_sub pos1
  else
    ok (none, self.owner, self.sub_handle, self.next_sub_handle, self.data,
      self.parent, self.children)
partial_fixpoint

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<T>}::remove_child]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 243:4-252:5
    Visibility: public -/
def mini_themis.Capability.remove_child
  {T : Type} (self : mini_themis.Capability T) (child_sub : Std.U64) :
  Result ((Option (my_std.Arc (my_std.RwLock (mini_themis.Capability T)))) ×
    (mini_themis.Capability T))
  := do
  let t ← mini_themis.Capability.remove_child_loop self child_sub 0#usize
  let (o, i, i1, i2, t1, w, v) := t
  ok (o, mini_themis.Capability.mk i i1 i2 t1 w v)

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::Weak<T>}::upgrade]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 114:4-116:5
    Visibility: public -/
axiom my_std.Weak.upgrade
  {T : Type} : my_std.Weak T → Result (Option (my_std.Arc T))

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<T>}::get_parent]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 254:4-256:5
    Visibility: public -/
def mini_themis.Capability.get_parent
  {T : Type} (self : mini_themis.Capability T) :
  Result (Option (my_std.Arc (my_std.RwLock (mini_themis.Capability T))))
  := do
  my_std.Weak.upgrade self.parent

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::Weak<T>}::strong_count]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 119:4-121:5
    Visibility: public -/
axiom my_std.Weak.strong_count {T : Type} : my_std.Weak T → Result Std.Usize

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<T>}::has_parent]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 258:4-260:5
    Visibility: public -/
def mini_themis.Capability.has_parent
  {T : Type} (self : mini_themis.Capability T) : Result Bool := do
  let i ← my_std.Weak.strong_count self.parent
  ok (i > 0#usize)

/-- [lt_stateful_mini_themis_client::my_std::RwLockWriteGuard]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 141:0-143:1
    Visibility: public -/
axiom my_std.RwLockWriteGuard (T : Type) : Type

/-- [lt_stateful_mini_themis_client::my_std::{impl core::ops::deref::DerefMut<T> for lt_stateful_mini_themis_client::my_std::RwLockWriteGuard<'_0, T>}::deref_mut]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 193:4-195:5
    Visibility: public -/
axiom my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut
  {T : Type} :
  my_std.RwLockWriteGuard T → Result (T × (T → Result
    (my_std.RwLockWriteGuard T)) × (my_std.RwLockWriteGuard T → Result
    (my_std.RwLockWriteGuard T)))

/-- [lt_stateful_mini_themis_client::my_std::{impl core::ops::deref::Deref<T> for lt_stateful_mini_themis_client::my_std::RwLockWriteGuard<'_0, T>}::deref]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 185:4-187:5
    Visibility: public -/
axiom my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref
  {T : Type} : my_std.RwLockWriteGuard T → Result T

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::RwLock<T>}::write]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 159:4-161:5
    Visibility: public -/
axiom my_std.RwLock.write
  {T : Type} :
  my_std.RwLock T → Result ((my_std.RwLockWriteGuard T) ×
    (my_std.RwLockWriteGuard T → Result Unit))

/-- [lt_stateful_mini_themis_client::my_std::{impl core::ops::drop::Drop for lt_stateful_mini_themis_client::my_std::RwLockWriteGuard<'_0, T>}::drop]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 201:4-203:5
    Visibility: public -/
axiom my_std.RwLockWriteGuard.Insts.CoreOpsDropDrop.drop
  {T : Type} :
  my_std.RwLockWriteGuard T → Result ((my_std.RwLockWriteGuard T) ×
    (my_std.RwLockWriteGuard T → Result (my_std.RwLockWriteGuard T)))

/-- [lt_stateful_mini_themis_client::my_std::{impl core::clone::Clone for lt_stateful_mini_themis_client::my_std::Arc<T>}::clone]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 93:4-95:5
    Visibility: public -/
axiom my_std.Arc.Insts.CoreCloneClone.clone
  {T : Type} : my_std.Arc T → Result (my_std.Arc T)

/-- [lt_stateful_mini_themis_client::my_std::{lt_stateful_mini_themis_client::my_std::Arc<T>}::downgrade]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 86:4-88:5
    Visibility: public -/
axiom my_std.Arc.downgrade {T : Type} : my_std.Arc T → Result (my_std.Weak T)

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::MemoryRegion>}::alias_child]: loop 0:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 274:8-293:5
    Visibility: public -/
@[rust_loop]
def mini_themis.CapabilityMemoryRegion.alias_child_loop
  (write_back : my_std.RwLockWriteGuard (mini_themis.Capability
  mini_themis.MemoryRegion) → Result Unit)
  (iter : core.ops.range.Range Std.Usize)
  (parent_ref : my_std.Arc (my_std.RwLock (mini_themis.Capability
  mini_themis.MemoryRegion))) (access : mini_themis.Access) (owner : Std.U64)
  (parent : my_std.RwLockWriteGuard (mini_themis.Capability
  mini_themis.MemoryRegion)) :
  Result (Option (my_std.Arc (my_std.RwLock (mini_themis.Capability
    mini_themis.MemoryRegion))))
  := do
  let p ← core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  let (o, iter1) := p
  match o with
  | none =>
    let c ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref parent
    let o1 ← mini_themis.MemoryRegion.alias c.data access
    let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o1
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let t ←
        my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut parent
      let (c1, deref_mut_back, deref_mut_back1) := t
      let i ← c1.next_sub_handle + 1#u64
      let parent1 ←
        deref_mut_back (mini_themis.Capability.mk c1.owner c1.sub_handle i
          c1.data c1.parent c1.children)
      let w ← my_std.Arc.downgrade parent_ref
      let child ←
        mini_themis.Capability.new_child owner val c.next_sub_handle w
      let t1 ←
        my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut parent1
      let (c2, deref_mut_back2, deref_mut_back3) := t1
      let a ← my_std.Arc.Insts.CoreCloneClone.clone child
      let c3 ← mini_themis.Capability.add_child c2 a
      let parent2 ← deref_mut_back2 c3
      let parent3 ← deref_mut_back3 parent2
      let parent4 ← deref_mut_back1 parent3
      write_back parent4
      ok (some child)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let o2 ←
        core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
          (my_std.Arc (my_std.RwLock (mini_themis.Capability
          mini_themis.MemoryRegion))) residual
      write_back parent
      ok o2
  | some i =>
    let c ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref parent
    let child_ref ←
      my_std.Vec.Insts.CoreOpsIndexIndexUsizeT.index c.children i
    let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref child_ref
    let p1 ← my_std.RwLock.read rl
    let (child, read_back) := p1
    let c1 ← my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref child
    let b ←
      mini_themis.RegionKind.Insts.CoreCmpPartialEqRegionKind.eq c1.data.kind
        mini_themis.RegionKind.Carve
    if b
    then
      let b1 ← mini_themis.Access.overlaps access c1.data.access
      if b1
      then read_back child
           write_back parent
           ok none
      else
        read_back child
        mini_themis.CapabilityMemoryRegion.alias_child_loop write_back iter1
          parent_ref access owner parent
    else
      read_back child
      mini_themis.CapabilityMemoryRegion.alias_child_loop write_back iter1
        parent_ref access owner parent
partial_fixpoint

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::MemoryRegion>}::alias_child]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 264:4-293:5
    Visibility: public -/
def mini_themis.CapabilityMemoryRegion.alias_child
  (parent_ref : my_std.Arc (my_std.RwLock (mini_themis.Capability
  mini_themis.MemoryRegion))) (access : mini_themis.Access) (owner : Std.U64) :
  Result (Option (my_std.Arc (my_std.RwLock (mini_themis.Capability
    mini_themis.MemoryRegion))))
  := do
  let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref parent_ref
  let p ← my_std.RwLock.write rl
  let (parent, write_back) := p
  let c ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref parent
  let i ← my_std.Vec.len c.children
  mini_themis.CapabilityMemoryRegion.alias_child_loop write_back
    { start := 0#usize, «end» := i } parent_ref access owner parent

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::MemoryRegion>}::carve_child]: loop 0:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 303:8-320:5
    Visibility: public -/
@[rust_loop]
def mini_themis.CapabilityMemoryRegion.carve_child_loop
  (write_back : my_std.RwLockWriteGuard (mini_themis.Capability
  mini_themis.MemoryRegion) → Result Unit)
  (parent_ref : my_std.Arc (my_std.RwLock (mini_themis.Capability
  mini_themis.MemoryRegion))) (access : mini_themis.Access) (owner : Std.U64)
  (parent : my_std.RwLockWriteGuard (mini_themis.Capability
  mini_themis.MemoryRegion)) (child_index : Std.Usize) :
  Result (Option (my_std.Arc (my_std.RwLock (mini_themis.Capability
    mini_themis.MemoryRegion))))
  := do
  let c ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref parent
  let i ← my_std.Vec.len c.children
  if child_index < i
  then
    let a ←
      my_std.Vec.Insts.CoreOpsIndexIndexUsizeT.index c.children child_index
    let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref a
    let p ← my_std.RwLock.read rl
    let (child, read_back) := p
    let c1 ← my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref child
    let b ← mini_themis.Access.overlaps access c1.data.access
    if b
    then read_back child
         write_back parent
         ok none
    else
      let child_index1 ← child_index + 1#usize
      read_back child
      mini_themis.CapabilityMemoryRegion.carve_child_loop write_back parent_ref
        access owner parent child_index1
  else
    let o ← mini_themis.MemoryRegion.carve c.data access
    let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let t ←
        my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut parent
      let (c1, deref_mut_back, deref_mut_back1) := t
      let i1 ← c1.next_sub_handle + 1#u64
      let parent1 ←
        deref_mut_back (mini_themis.Capability.mk c1.owner c1.sub_handle i1
          c1.data c1.parent c1.children)
      let w ← my_std.Arc.downgrade parent_ref
      let child ←
        mini_themis.Capability.new_child owner val c.next_sub_handle w
      let t1 ←
        my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut parent1
      let (c2, deref_mut_back2, deref_mut_back3) := t1
      let a ← my_std.Arc.Insts.CoreCloneClone.clone child
      let c3 ← mini_themis.Capability.add_child c2 a
      let parent2 ← deref_mut_back2 c3
      let parent3 ← deref_mut_back3 parent2
      let parent4 ← deref_mut_back1 parent3
      write_back parent4
      ok (some child)
    | core.ops.control_flow.ControlFlow.Break residual =>
      let o1 ←
        core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
          (my_std.Arc (my_std.RwLock (mini_themis.Capability
          mini_themis.MemoryRegion))) residual
      write_back parent
      ok o1
partial_fixpoint

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::MemoryRegion>}::carve_child]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 295:4-320:5
    Visibility: public -/
def mini_themis.CapabilityMemoryRegion.carve_child
  (parent_ref : my_std.Arc (my_std.RwLock (mini_themis.Capability
  mini_themis.MemoryRegion))) (access : mini_themis.Access) (owner : Std.U64) :
  Result (Option (my_std.Arc (my_std.RwLock (mini_themis.Capability
    mini_themis.MemoryRegion))))
  := do
  let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref parent_ref
  let p ← my_std.RwLock.write rl
  let (parent, write_back) := p
  mini_themis.CapabilityMemoryRegion.carve_child_loop write_back parent_ref
    access owner parent 0#usize

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::MemoryRegion>}::subtract_region]: loop 0:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 402:8-423:9 -/
@[rust_loop]
def mini_themis.CapabilityMemoryRegion.subtract_region_loop
  (regions : my_std.Vec mini_themis.Access) (to_subtract : mini_themis.Access)
  (result : my_std.Vec mini_themis.Access) (region_index : Std.Usize) :
  Result (my_std.Vec mini_themis.Access)
  := do
  let i ← my_std.Vec.len regions
  if region_index < i
  then
    let region ←
      my_std.Vec.Insts.CoreOpsIndexIndexUsizeT.index regions region_index
    let b ← mini_themis.Access.overlaps region to_subtract
    let p ←
      if b
      then
        do
        let result1 ←
          if region.start < to_subtract.start
          then
            do
            let i1 ← to_subtract.start - region.start
            let a ← mini_themis.Access.new region.start i1 region.rights
            my_std.Vec.push result a
          else ok result
        let i1 ← mini_themis.Access.end region
        let i2 ← mini_themis.Access.end to_subtract
        let v ←
          if i1 > i2
          then
            do
            let i3 ← i1 - i2
            let a ← mini_themis.Access.new i2 i3 region.rights
            my_std.Vec.push result1 a
          else ok result1
        ok (to_subtract, v)
      else
        do
        let result1 ← my_std.Vec.push result region
        ok (to_subtract, result1)
    let (to_subtract1, result1) := p
    let region_index1 ← region_index + 1#usize
    mini_themis.CapabilityMemoryRegion.subtract_region_loop regions
      to_subtract1 result1 region_index1
  else ok result
partial_fixpoint

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::MemoryRegion>}::subtract_region]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 398:4-426:5 -/
def mini_themis.CapabilityMemoryRegion.subtract_region
  (regions : my_std.Vec mini_themis.Access) (to_subtract : mini_themis.Access)
  :
  Result (my_std.Vec mini_themis.Access)
  := do
  let result ← my_std.Vec.new mini_themis.Access
  mini_themis.CapabilityMemoryRegion.subtract_region_loop regions to_subtract
    result 0#usize

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::MemoryRegion>}::compute_view]: loop 0:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 387:12-390:51
    Visibility: public -/
@[rust_loop]
def mini_themis.CapabilityMemoryRegion.compute_view_loop
  (iter : core.ops.range.Range Std.Usize)
  (v : my_std.Vec (my_std.Arc (my_std.RwLock (mini_themis.Capability
  mini_themis.MemoryRegion)))) (view : my_std.Vec mini_themis.Access) :
  Result (my_std.Vec mini_themis.Access)
  := do
  let p ← core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  let (o, iter1) := p
  match o with
  | none => ok view
  | some i =>
    let a ← my_std.Vec.Insts.CoreOpsIndexIndexUsizeT.index v i
    let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref a
    let p1 ← my_std.RwLock.read rl
    let (child, read_back) := p1
    let c ← my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref child
    let b ←
      mini_themis.RegionKind.Insts.CoreCmpPartialEqRegionKind.eq c.data.kind
        mini_themis.RegionKind.Carve
    if b
    then
      let view1 ←
        mini_themis.CapabilityMemoryRegion.subtract_region view c.data.access
      read_back child
      mini_themis.CapabilityMemoryRegion.compute_view_loop iter1 v view1
    else
      read_back child
      mini_themis.CapabilityMemoryRegion.compute_view_loop iter1 v view
partial_fixpoint

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::MemoryRegion>}::compute_view]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 383:4-396:5
    Visibility: public -/
def mini_themis.CapabilityMemoryRegion.compute_view
  (self : mini_themis.Capability mini_themis.MemoryRegion) :
  Result (my_std.Vec mini_themis.Access)
  := do
  let view ← my_std.Vec.new mini_themis.Access
  let view1 ← my_std.Vec.push view self.data.access
  let i ← my_std.Vec.len self.children
  mini_themis.CapabilityMemoryRegion.compute_view_loop
    { start := 0#usize, «end» := i } self.children view1

/-- [lt_stateful_mini_themis_client::mini_themis::lock_two_domains_ordered]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 458:0-468:1 -/
axiom mini_themis.lock_two_domains_ordered
  :
  my_std.Arc (my_std.RwLock (mini_themis.Capability mini_themis.Domain)) →
    Std.U64 → my_std.Arc (my_std.RwLock (mini_themis.Capability
    mini_themis.Domain)) → Std.U64 → Result (((my_std.RwLockWriteGuard
    (mini_themis.Capability mini_themis.Domain)) × (my_std.RwLockWriteGuard
    (mini_themis.Capability mini_themis.Domain))) × (((my_std.RwLockWriteGuard
    (mini_themis.Capability mini_themis.Domain)) × (my_std.RwLockWriteGuard
    (mini_themis.Capability mini_themis.Domain))) → Result Unit))

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::Domain>}::create_child_domain]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 471:4-491:5
    Visibility: public -/
def mini_themis.CapabilityDomain.create_child_domain
  (parent_cap : mini_themis.Capability mini_themis.Domain)
  (parent_ref : my_std.Arc (my_std.RwLock (mini_themis.Capability
  mini_themis.Domain))) (policy : mini_themis.DomainPolicy) (owner : Std.U64) :
  Result ((Option (my_std.Arc (my_std.RwLock (mini_themis.Capability
    mini_themis.Domain)))) × (mini_themis.Capability mini_themis.Domain))
  := do
  let o ← mini_themis.DomainPolicy.is_subset_of policy parent_cap.data.policy
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    let child_domain ← mini_themis.Domain.new policy
    let i ← parent_cap.next_sub_handle + 1#u64
    let w ← my_std.Arc.downgrade parent_ref
    let child ←
      mini_themis.Capability.new_child owner child_domain
        parent_cap.next_sub_handle w
    let a ← my_std.Arc.Insts.CoreCloneClone.clone child
    let parent_cap1 ←
      mini_themis.Capability.add_child (mini_themis.Capability.mk
        parent_cap.owner parent_cap.sub_handle i (mini_themis.Domain.mk
        parent_cap.data.id parent_cap.data.policy
        parent_cap.data.memory_capabilities
        parent_cap.data.domain_capabilities) parent_cap.parent
        parent_cap.children) a
    ok (some child, parent_cap1)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let o1 ←
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        (my_std.Arc (my_std.RwLock (mini_themis.Capability
        mini_themis.Domain))) residual
    ok (o1, mini_themis.Capability.mk parent_cap.owner parent_cap.sub_handle
      parent_cap.next_sub_handle (mini_themis.Domain.mk parent_cap.data.id
      parent_cap.data.policy parent_cap.data.memory_capabilities
      parent_cap.data.domain_capabilities) parent_cap.parent
      parent_cap.children)

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::Domain>}::carve]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 519:4-540:5
    Visibility: public -/
def mini_themis.CapabilityDomain.carve
  (caller : my_std.Arc (my_std.RwLock (mini_themis.Capability
  mini_themis.Domain))) (region : Std.U64) (access : mini_themis.Access) :
  Result (Option (Std.U64 × Std.U64))
  := do
  let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref caller
  let p ← my_std.RwLock.write rl
  let (w, write_back) := p
  let c ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref w
  let o ← mini_themis.Domain.get_memory_capability c.data region
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let o1 ← my_std.Weak.upgrade val
    let cf1 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let o2 ←
        mini_themis.CapabilityMemoryRegion.carve_child val1 access c.data.id
      let cf2 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o2
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        let rl1 ← my_std.Arc.Insts.CoreOpsDerefDeref.deref val2
        let p1 ← my_std.RwLock.read rl1
        let (rlrg, read_back) := p1
        let c1 ← my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref rlrg
        read_back rlrg
        let new_handle ← mini_themis.Domain.allocate_memory_handle c.data
        let t ←
          my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut w
        let (c2, deref_mut_back, deref_mut_back1) := t
        let w1 ← my_std.Arc.downgrade val2
        let d ←
          mini_themis.Domain.add_memory_capability c2.data new_handle w1
        let w2 ←
          deref_mut_back (mini_themis.Capability.mk c2.owner c2.sub_handle
            c2.next_sub_handle d c2.parent c2.children)
        let w3 ← deref_mut_back1 w2
        write_back w3
        ok (some (new_handle, c1.sub_handle))
      | core.ops.control_flow.ControlFlow.Break residual =>
        let o3 ←
          core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
            (Std.U64 × Std.U64) residual
        write_back w
        ok o3
    | core.ops.control_flow.ControlFlow.Break residual =>
      let o2 ←
        core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
          (Std.U64 × Std.U64) residual
      write_back w
      ok o2
  | core.ops.control_flow.ControlFlow.Break residual =>
    let o1 ←
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        (Std.U64 × Std.U64) residual
    write_back w
    ok o1

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::Domain>}::alias]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 542:4-562:5
    Visibility: public -/
def mini_themis.CapabilityDomain.alias
  (caller : my_std.Arc (my_std.RwLock (mini_themis.Capability
  mini_themis.Domain))) (region : Std.U64) (access : mini_themis.Access) :
  Result (Option (Std.U64 × Std.U64))
  := do
  let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref caller
  let p ← my_std.RwLock.write rl
  let (w, write_back) := p
  let c ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref w
  let o ← mini_themis.Domain.get_memory_capability c.data region
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let o1 ← my_std.Weak.upgrade val
    let cf1 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let o2 ←
        mini_themis.CapabilityMemoryRegion.alias_child val1 access c.data.id
      let cf2 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o2
      match cf2 with
      | core.ops.control_flow.ControlFlow.Continue val2 =>
        let rl1 ← my_std.Arc.Insts.CoreOpsDerefDeref.deref val2
        let p1 ← my_std.RwLock.read rl1
        let (rlrg, read_back) := p1
        let c1 ← my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref rlrg
        read_back rlrg
        let new_handle ← mini_themis.Domain.allocate_memory_handle c.data
        let t ←
          my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut w
        let (c2, deref_mut_back, deref_mut_back1) := t
        let w1 ← my_std.Arc.downgrade val2
        let d ←
          mini_themis.Domain.add_memory_capability c2.data new_handle w1
        let w2 ←
          deref_mut_back (mini_themis.Capability.mk c2.owner c2.sub_handle
            c2.next_sub_handle d c2.parent c2.children)
        let w3 ← deref_mut_back1 w2
        write_back w3
        ok (some (new_handle, c1.sub_handle))
      | core.ops.control_flow.ControlFlow.Break residual =>
        let o3 ←
          core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
            (Std.U64 × Std.U64) residual
        write_back w
        ok o3
    | core.ops.control_flow.ControlFlow.Break residual =>
      let o2 ←
        core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
          (Std.U64 × Std.U64) residual
      write_back w
      ok o2
  | core.ops.control_flow.ControlFlow.Break residual =>
    let o1 ←
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        (Std.U64 × Std.U64) residual
    write_back w
    ok o1

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::Domain>}::send]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 564:4-603:5
    Visibility: public -/
def mini_themis.CapabilityDomain.send
  (caller : my_std.Arc (my_std.RwLock (mini_themis.Capability
  mini_themis.Domain))) (cap : Std.U64) (receiver : Std.U64) :
  Result (Option Unit)
  := do
  let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref caller
  let p ← my_std.RwLock.read rl
  let (r, read_back) := p
  let c ← my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref r
  let o ← mini_themis.Domain.get_domain_capability c.data receiver
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let o1 ← my_std.Weak.upgrade val
    let cf1 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      read_back r
      let rl1 ← my_std.Arc.Insts.CoreOpsDerefDeref.deref val1
      let p1 ← my_std.RwLock.read rl1
      let (rlrg, read_back1) := p1
      let c1 ← my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref rlrg
      read_back1 rlrg
      if c.data.id = c1.data.id
      then ok none
      else
        let p2 ←
          mini_themis.lock_two_domains_ordered caller c.data.id val1 c1.data.id
        let ((caller_w, receiver_w), lock_two_domains_ordered_back) := p2
        let t ←
          my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut caller_w
        let (c2, deref_mut_back, deref_mut_back1) := t
        let p3 ← mini_themis.Domain.remove_memory_capability c2.data cap
        let (o2, d) := p3
        let cf2 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o2
        match cf2 with
        | core.ops.control_flow.ControlFlow.Continue val2 =>
          let caller_w1 ←
            deref_mut_back (mini_themis.Capability.mk c2.owner c2.sub_handle
              c2.next_sub_handle d c2.parent c2.children)
          let o3 ← my_std.Weak.upgrade val2
          let cf3 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o3
          match cf3 with
          | core.ops.control_flow.ControlFlow.Continue val3 =>
            let rl2 ← my_std.Arc.Insts.CoreOpsDerefDeref.deref val3
            let p4 ← my_std.RwLock.write rl2
            let (rlwg, write_back) := p4
            let t1 ←
              my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut rlwg
            let (c3, deref_mut_back2, deref_mut_back3) := t1
            let rlwg1 ←
              deref_mut_back2 (mini_themis.Capability.mk c1.data.id
                c3.sub_handle c3.next_sub_handle c3.data c3.parent c3.children)
            let rlwg2 ← deref_mut_back3 rlwg1
            write_back rlwg2
            let c4 ←
              my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref receiver_w
            let new_handle ←
              mini_themis.Domain.allocate_memory_handle c4.data
            let t2 ←
              my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut
                receiver_w
            let (c5, deref_mut_back4, deref_mut_back5) := t2
            let w ← my_std.Arc.downgrade val3
            let d1 ←
              mini_themis.Domain.add_memory_capability c5.data new_handle w
            let receiver_w1 ←
              deref_mut_back4 (mini_themis.Capability.mk c5.owner c5.sub_handle
                c5.next_sub_handle d1 c5.parent c5.children)
            let receiver_w2 ← deref_mut_back5 receiver_w1
            let caller_w2 ← deref_mut_back1 caller_w1
            lock_two_domains_ordered_back (caller_w2, receiver_w2)
            ok (some ())
          | core.ops.control_flow.ControlFlow.Break residual =>
            let o4 ←
              core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
                Unit residual
            let caller_w2 ← deref_mut_back1 caller_w1
            lock_two_domains_ordered_back (caller_w2, receiver_w)
            ok o4
        | core.ops.control_flow.ControlFlow.Break residual =>
          let o3 ←
            core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
              Unit residual
          let caller_w1 ←
            deref_mut_back (mini_themis.Capability.mk c2.owner c2.sub_handle
              c2.next_sub_handle d c2.parent c2.children)
          let caller_w2 ← deref_mut_back1 caller_w1
          lock_two_domains_ordered_back (caller_w2, receiver_w)
          ok o3
    | core.ops.control_flow.ControlFlow.Break residual =>
      let o2 ←
        core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
          Unit residual
      read_back r
      ok o2
  | core.ops.control_flow.ControlFlow.Break residual =>
    let o1 ←
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        Unit residual
    read_back r
    ok o1

/-- [lt_stateful_mini_themis_client::mini_themis::{lt_stateful_mini_themis_client::mini_themis::Capability<lt_stateful_mini_themis_client::mini_themis::Domain>}::create]:
    Source: 'tests/src/.lt-stateful-client/mini_themis.rs', lines 605:4-614:5
    Visibility: public -/
def mini_themis.CapabilityDomain.create
  (parent : my_std.Arc (my_std.RwLock (mini_themis.Capability
  mini_themis.Domain))) (policy : mini_themis.DomainPolicy) :
  Result (Option Std.U64)
  := do
  let rl ← my_std.Arc.Insts.CoreOpsDerefDeref.deref parent
  let p ← my_std.RwLock.write rl
  let (w, write_back) := p
  let c ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref w
  let new_handler ← mini_themis.Domain.allocate_domain_handle c.data
  let t ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut w
  let (c1, deref_mut_back, deref_mut_back1) := t
  let p1 ←
    mini_themis.CapabilityDomain.create_child_domain c1 parent policy c.data.id
  let (o, c2) := p1
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let w1 ← deref_mut_back c2
    let t1 ← my_std.RwLockWriteGuard.Insts.CoreOpsDerefDerefMut.deref_mut w1
    let (c3, deref_mut_back2, deref_mut_back3) := t1
    let w2 ← my_std.Arc.downgrade val
    let d ← mini_themis.Domain.add_domain_capability c3.data new_handler w2
    let w3 ←
      deref_mut_back2 (mini_themis.Capability.mk c3.owner c3.sub_handle
        c3.next_sub_handle d c3.parent c3.children)
    let w4 ← deref_mut_back3 w3
    let w5 ← deref_mut_back1 w4
    write_back w5
    ok (some new_handler)
  | core.ops.control_flow.ControlFlow.Break residual =>
    let o1 ←
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        Std.U64 residual
    let w1 ← deref_mut_back c2
    let w2 ← deref_mut_back1 w1
    write_back w2
    ok o1

/-- Trait implementation: [lt_stateful_mini_themis_client::my_std::{impl core::ops::index::Index<usize, T> for lt_stateful_mini_themis_client::my_std::Vec<T>}]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 31:0-38:1 -/
@[reducible]
def my_std.Vec.Insts.CoreOpsIndexIndexUsizeT (T : Type) : core.ops.index.Index
  (my_std.Vec T) Std.Usize T := {
  index := my_std.Vec.Insts.CoreOpsIndexIndexUsizeT.index
}

/-- Trait implementation: [lt_stateful_mini_themis_client::my_std::{impl core::clone::Clone for lt_stateful_mini_themis_client::my_std::Arc<T>}]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 91:0-96:1 -/
@[reducible]
def my_std.Arc.Insts.CoreCloneClone (T : Type) : core.clone.Clone (my_std.Arc
  T) := {
  clone := my_std.Arc.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lt_stateful_mini_themis_client::my_std::{impl core::ops::deref::Deref<T> for lt_stateful_mini_themis_client::my_std::Arc<T>}]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 98:0-105:1 -/
@[reducible]
def my_std.Arc.Insts.CoreOpsDerefDeref (T : Type) : core.ops.deref.Deref
  (my_std.Arc T) T := {
  deref := my_std.Arc.Insts.CoreOpsDerefDeref.deref
}

/-- [lt_stateful_mini_themis_client::my_std::{impl core::clone::Clone for lt_stateful_mini_themis_client::my_std::Weak<T>}::clone]:
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 126:4-128:5
    Visibility: public -/
axiom my_std.Weak.Insts.CoreCloneClone.clone
  {T : Type} : my_std.Weak T → Result (my_std.Weak T)

/-- Trait implementation: [lt_stateful_mini_themis_client::my_std::{impl core::clone::Clone for lt_stateful_mini_themis_client::my_std::Weak<T>}]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 124:0-129:1 -/
@[reducible]
def my_std.Weak.Insts.CoreCloneClone (T : Type) : core.clone.Clone (my_std.Weak
  T) := {
  clone := my_std.Weak.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [lt_stateful_mini_themis_client::my_std::{impl core::ops::deref::Deref<T> for lt_stateful_mini_themis_client::my_std::RwLockReadGuard<'_0, T>}]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 164:0-171:1 -/
@[reducible]
def my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref (T : Type) :
  core.ops.deref.Deref (my_std.RwLockReadGuard T) T := {
  deref := my_std.RwLockReadGuard.Insts.CoreOpsDerefDeref.deref
}

/-- Trait implementation: [lt_stateful_mini_themis_client::my_std::{impl core::ops::deref::Deref<T> for lt_stateful_mini_themis_client::my_std::RwLockWriteGuard<'_0, T>}]
    Source: 'tests/src/.lt-stateful-client/my_std.rs', lines 181:0-188:1 -/
@[reducible]
def my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref (T : Type) :
  core.ops.deref.Deref (my_std.RwLockWriteGuard T) T := {
  deref := my_std.RwLockWriteGuard.Insts.CoreOpsDerefDeref.deref
}

end lt_stateful_mini_themis_client
