-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_drop]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_drop

/-- [core::mem::forget]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 189:0-189:28
    Name pattern: [core::mem::forget]
    Visibility: public -/
@[rust_fun "core::mem::forget"]
axiom core.mem.forget {T : Type} : T → Result Unit

/-- [core::mem::drop]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 1000:0-1002:24
    Name pattern: [core::mem::drop]
    Visibility: public -/
@[rust_fun "core::mem::drop"]
axiom core.mem.drop {T : Type} : T → Result Unit

/-- [core::option::{core::option::Option<T>}::replace]:
    Source: '/rustc/library/core/src/option.rs', lines 1959:4-1959:58
    Name pattern: [core::option::{core::option::Option<@T>}::replace]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::replace"]
axiom core.option.Option.replace
  {T : Type} : Option T → T → Result ((Option T) × (Option T))

/-- [lt_stateful_drop::Lock]
    Source: 'tests/src/lt-stateful-drop.rs', lines 56:0-56:16
    Visibility: public -/
axiom Lock : Type

/-- [lt_stateful_drop::Guard]
    Source: 'tests/src/lt-stateful-drop.rs', lines 62:0-64:1
    Visibility: public -/
axiom Guard : Type

/-- [lt_stateful_drop::{impl core::ops::drop::Drop for lt_stateful_drop::Guard<'a>}::drop]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 102:4-104:5
    Visibility: public -/
axiom Guard.Insts.CoreOpsDropDrop.drop : Guard → Result Guard

/-- [lt_stateful_drop::ReadGuard]
    Source: 'tests/src/lt-stateful-drop.rs', lines 69:0-71:1
    Visibility: public -/
axiom ReadGuard : Type

/-- [lt_stateful_drop::{impl core::ops::drop::Drop for lt_stateful_drop::ReadGuard<'a>}::drop]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 110:4-112:5
    Visibility: public -/
axiom ReadGuard.Insts.CoreOpsDropDrop.drop : ReadGuard → Result ReadGuard

/-- [lt_stateful_drop::{lt_stateful_drop::Lock}::acquire]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 79:4-81:5
    Visibility: public -/
axiom Lock.acquire : Lock → Result Guard

/-- [lt_stateful_drop::{lt_stateful_drop::Lock}::read]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 86:4-88:5
    Visibility: public -/
axiom Lock.read : Lock → Result ReadGuard

/-- Trait implementation: [lt_stateful_drop::{impl core::ops::drop::Drop for lt_stateful_drop::Guard<'a>}]
    Source: 'tests/src/lt-stateful-drop.rs', lines 100:0-105:1 -/
@[reducible]
def Guard.Insts.CoreOpsDropDrop : core.ops.drop.Drop Guard := {
  drop := Guard.Insts.CoreOpsDropDrop.drop
}

/-- Trait implementation: [lt_stateful_drop::{impl core::ops::drop::Drop for lt_stateful_drop::ReadGuard<'a>}]
    Source: 'tests/src/lt-stateful-drop.rs', lines 108:0-113:1 -/
@[reducible]
def ReadGuard.Insts.CoreOpsDropDrop : core.ops.drop.Drop ReadGuard := {
  drop := ReadGuard.Insts.CoreOpsDropDrop.drop
}

/-- [lt_stateful_drop::GuardPair]
    Source: 'tests/src/lt-stateful-drop.rs', lines 118:0-121:1
    Visibility: public -/
structure GuardPair where
  first : Guard
  second : Guard

/-- [lt_stateful_drop::GuardTuplePair]
    Source: 'tests/src/lt-stateful-drop.rs', lines 127:0-127:52
    Visibility: public -/
def GuardTuplePair := Guard × Guard

/-- [lt_stateful_drop::touch]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 134:0-134:27 -/
def touch (_g : Guard) : Result Unit := do
  ok ()

/-- [lt_stateful_drop::touch_read]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 135:0-135:36 -/
def touch_read (_r : ReadGuard) : Result Unit := do
  ok ()

/-- [lt_stateful_drop::touch_option]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 136:0-136:42 -/
def touch_option (_o : Option Guard) : Result Unit := do
  ok ()

/-- [lt_stateful_drop::do_other_work]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 137:0-137:21 -/
def do_other_work : Result Unit := do
  ok ()

/-- [lt_stateful_drop::do_something]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 138:0-138:20 -/
def do_something : Result Unit := do
  ok ()

/-- [lt_stateful_drop::guard_condition]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 142:0-144:1 -/
def guard_condition (_g : Guard) : Result Bool := do
  ok true

/-- [lt_stateful_drop::explicit_drop]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 153:0-158:1
    Visibility: public -/
def explicit_drop (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  touch g
  core.mem.drop g
  do_other_work

/-- [lt_stateful_drop::nested_scope]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 168:0-174:1
    Visibility: public -/
def nested_scope (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  touch g
  do_other_work

/-- [lt_stateful_drop::implicit_function_scope]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 183:0-187:1
    Visibility: public -/
def implicit_function_scope (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  touch g
  do_other_work

/-- [lt_stateful_drop::let_underscore_immediate_drop]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 200:0-203:1
    Visibility: public -/
def let_underscore_immediate_drop (lock : Lock) : Result Unit := do
  let _ ← Lock.acquire lock
  do_other_work

/-- [lt_stateful_drop::unused_named_guard]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 215:0-218:1
    Visibility: public -/
def unused_named_guard (lock : Lock) : Result Unit := do
  let _ ← Lock.acquire lock
  do_other_work

/-- [lt_stateful_drop::statement_end_drop]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 229:0-232:1
    Visibility: public -/
def statement_end_drop (lock : Lock) : Result Unit := do
  let _ ← Lock.acquire lock
  do_other_work

/-- [lt_stateful_drop::shadowing_same_lock]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 252:0-257:1
    Visibility: public -/
def shadowing_same_lock (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  touch g
  touch g

/-- [lt_stateful_drop::assign_overwrite_same_lock]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 274:0-279:1
    Visibility: public -/
def assign_overwrite_same_lock (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  touch g
  touch g

/-- [lt_stateful_drop::assign_overwrite_different_locks]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 285:0-290:1
    Visibility: public -/
def assign_overwrite_different_locks
  (lock_a : Lock) (lock_b : Lock) : Result Unit := do
  let g ← Lock.acquire lock_a
  touch g
  let g1 ← Lock.acquire lock_b
  touch g1

/-- [lt_stateful_drop::destructure_tuple]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 304:0-308:1
    Visibility: public -/
def destructure_tuple (lock : Lock) : Result Unit := do
  let g1 ← Lock.acquire lock
  touch g1
  touch g1

/-- [lt_stateful_drop::destructure_struct]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 317:0-325:1
    Visibility: public -/
def destructure_struct (lock : Lock) : Result Unit := do
  let first ← Lock.acquire lock
  touch first
  touch first

/-- [lt_stateful_drop::nested_two_guards_reverse_order]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 335:0-340:1
    Visibility: public -/
def nested_two_guards_reverse_order
  (lock_a : Lock) (lock_b : Lock) : Result Unit := do
  let g1 ← Lock.acquire lock_a
  let g2 ← Lock.acquire lock_b
  touch g1
  touch g2

/-- [lt_stateful_drop::nested_three_guards_reverse_order]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 346:0-353:1
    Visibility: public -/
def nested_three_guards_reverse_order
  (lock_a : Lock) (lock_b : Lock) (lock_c : Lock) : Result Unit := do
  let g1 ← Lock.acquire lock_a
  let g2 ← Lock.acquire lock_b
  let g3 ← Lock.acquire lock_c
  touch g1
  touch g2
  touch g3

/-- [lt_stateful_drop::conditional_initialization]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 366:0-374:1
    Visibility: public -/
def conditional_initialization (lock : Lock) (cond : Bool) : Result Unit := do
  let g ← if cond
            then Lock.acquire lock
            else Lock.acquire lock
  touch g

/-- [lt_stateful_drop::conditional_guard_one_branch]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 381:0-387:1
    Visibility: public -/
def conditional_guard_one_branch
  (lock : Lock) (cond : Bool) : Result Unit := do
  let _ ←
    if cond
    then do
         let g ← Lock.acquire lock
         touch g
         ok true
    else ok false
  do_other_work

/-- [lt_stateful_drop::guard_in_option]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 399:0-405:1
    Visibility: public -/
def guard_in_option (lock : Lock) (cond : Bool) : Result Unit := do
  let maybe_guard ←
    if cond
    then do
         let g ← Lock.acquire lock
         ok (some g)
    else ok none
  touch_option maybe_guard

/-- [lt_stateful_drop::guard_take]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 416:0-421:1
    Visibility: public -/
def guard_take (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  let (taken, _) := core.option.Option.take (some g)
  core.mem.drop taken
  do_other_work

/-- [lt_stateful_drop::guard_replace]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 432:0-437:1
    Visibility: public -/
def guard_replace (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  let (old, maybe_guard) ← core.option.Option.replace (some g) g
  core.mem.drop old
  touch_option maybe_guard

/-- [lt_stateful_drop::guard_swap]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 450:0-456:1
    Visibility: public -/
def guard_swap (lock_a : Lock) (lock_b : Lock) : Result Unit := do
  let g1 ← Lock.acquire lock_a
  let g2 ← Lock.acquire lock_b
  let (g11, g21) := core.mem.swap g1 g2
  touch g11
  touch g21

/-- [lt_stateful_drop::guard_moved_between_locals]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 467:0-471:1
    Visibility: public -/
def guard_moved_between_locals (lock : Lock) : Result Unit := do
  let g1 ← Lock.acquire lock
  touch g1

/-- [lt_stateful_drop::block_expr_returns_guard]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 484:0-490:1
    Visibility: public -/
def block_expr_returns_guard (lock : Lock) : Result Unit := do
  do_something
  let g ← Lock.acquire lock
  touch g

/-- [lt_stateful_drop::multiple_read_guards]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 503:0-510:1
    Visibility: public -/
def multiple_read_guards (lock : Lock) : Result Unit := do
  let r1 ← Lock.read lock
  touch_read r1
  touch_read r1
  touch_read r1

/-- [lt_stateful_drop::read_then_write_same_lock]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 520:0-525:1
    Visibility: public -/
def read_then_write_same_lock (lock : Lock) : Result Unit := do
  let r ← Lock.read lock
  touch_read r
  let w ← Lock.acquire lock
  touch w

/-- [lt_stateful_drop::partial_aggregate_move]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 544:0-552:1
    Visibility: public -/
def partial_aggregate_move (lock : Lock) : Result Unit := do
  let moved_first ← Lock.acquire lock
  touch moved_first
  touch moved_first

/-- [lt_stateful_drop::tuple_struct_partial_move]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 566:0-571:1
    Visibility: public -/
def tuple_struct_partial_move (lock : Lock) : Result Unit := do
  let moved0 ← Lock.acquire lock
  touch moved0
  touch moved0

/-- [lt_stateful_drop::destructuring_assignment]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 591:0-599:1
    Visibility: public -/
def destructuring_assignment (lock : Lock) : Result Unit := do
  let a ← Lock.acquire lock
  touch a
  touch a
  touch a
  touch a

/-- [lt_stateful_drop::destructure_struct_reversed_pattern]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 618:0-626:1
    Visibility: public -/
def destructure_struct_reversed_pattern (lock : Lock) : Result Unit := do
  let first ← Lock.acquire lock
  touch first
  touch first

/-- [lt_stateful_drop::let_else_binding]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 643:0-650:1
    Visibility: public -/
def let_else_binding (lock : Lock) (cond : Bool) : Result Unit := do
  let o ←
    if cond
    then do
         let g ← Lock.acquire lock
         ok (some g)
    else ok none
  match o with
  | none => do_other_work
  | some g => touch g
              do_something

/-- [lt_stateful_drop::match_arm_with_guard_clause]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 666:0-673:1
    Visibility: public -/
def match_arm_with_guard_clause (lock : Lock) (cond : Bool) : Result Unit := do
  let g ← Lock.acquire lock
  let _ ←
    if cond
    then
      do
      let b ← guard_condition g
      if b
      then touch g
      else touch g
      ok (true, ())
    else do
         touch g
         ok (false, ())
  do_other_work

/-- [lt_stateful_drop::nested_closure_capture::closure]
    Source: 'tests/src/lt-stateful-drop.rs', lines 696:17-699:5 -/
@[reducible]
def nested_closure_capture.closure := Guard

/-- [lt_stateful_drop::nested_closure_capture::{impl core::ops::function::Fn<(), bool> for lt_stateful_drop::nested_closure_capture::closure<'_0>}::call]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 696:17-699:5 -/
def nested_closure_capture.closure.Insts.CoreOpsFunctionFnTupleBool.call
  (c : nested_closure_capture.closure) (_ : Unit) : Result Bool := do
  touch c
  ok true

/-- [lt_stateful_drop::nested_closure_capture]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 694:0-702:1
    Visibility: public -/
def nested_closure_capture (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  let _ ←
    nested_closure_capture.closure.Insts.CoreOpsFunctionFnTupleBool.call g ()
  do_other_work

/-- [lt_stateful_drop::nested_closure_capture::{impl core::ops::function::FnMut<(), bool> for lt_stateful_drop::nested_closure_capture::closure<'_0>}::call_mut]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 696:17-699:5 -/
def nested_closure_capture.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
  (state : nested_closure_capture.closure) (_ : Unit) :
  Result (Bool × nested_closure_capture.closure)
  := do
  let b ←
    nested_closure_capture.closure.Insts.CoreOpsFunctionFnTupleBool.call state
      ()
  ok (b, state)

/-- [lt_stateful_drop::nested_closure_capture::{impl core::ops::function::FnOnce<(), bool> for lt_stateful_drop::nested_closure_capture::closure<'_0>}::call_once]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 696:17-699:5 -/
def
  nested_closure_capture.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
  (c : nested_closure_capture.closure) (_ : Unit) : Result Bool := do
  let (b, _) ←
    nested_closure_capture.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
      c ()
  ok b

/-- Trait implementation: [lt_stateful_drop::nested_closure_capture::{impl core::ops::function::FnOnce<(), bool> for lt_stateful_drop::nested_closure_capture::closure<'_0>}]
    Source: 'tests/src/lt-stateful-drop.rs', lines 696:17-699:5 -/
@[reducible]
def nested_closure_capture.closure.Insts.CoreOpsFunctionFnOnceTupleBool :
  core.ops.function.FnOnce nested_closure_capture.closure Unit Bool := {
  call_once :=
    nested_closure_capture.closure.Insts.CoreOpsFunctionFnOnceTupleBool.call_once
}

/-- Trait implementation: [lt_stateful_drop::nested_closure_capture::{impl core::ops::function::FnMut<(), bool> for lt_stateful_drop::nested_closure_capture::closure<'_0>}]
    Source: 'tests/src/lt-stateful-drop.rs', lines 696:17-699:5 -/
@[reducible]
def nested_closure_capture.closure.Insts.CoreOpsFunctionFnMutTupleBool :
  core.ops.function.FnMut nested_closure_capture.closure Unit Bool := {
  FnOnceInst :=
    nested_closure_capture.closure.Insts.CoreOpsFunctionFnOnceTupleBool
  call_mut :=
    nested_closure_capture.closure.Insts.CoreOpsFunctionFnMutTupleBool.call_mut
}

/-- Trait implementation: [lt_stateful_drop::nested_closure_capture::{impl core::ops::function::Fn<(), bool> for lt_stateful_drop::nested_closure_capture::closure<'_0>}]
    Source: 'tests/src/lt-stateful-drop.rs', lines 696:17-699:5 -/
@[reducible]
def nested_closure_capture.closure.Insts.CoreOpsFunctionFnTupleBool :
  core.ops.function.Fn nested_closure_capture.closure Unit Bool := {
  FnMutInst :=
    nested_closure_capture.closure.Insts.CoreOpsFunctionFnMutTupleBool
  call := nested_closure_capture.closure.Insts.CoreOpsFunctionFnTupleBool.call
}

/-- [lt_stateful_drop::aggregate_fields_drop_in_declaration_order]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 712:0-719:1
    Visibility: public -/
def aggregate_fields_drop_in_declaration_order
  (lock_a : Lock) (lock_b : Lock) : Result Unit := do
  let g ← Lock.acquire lock_a
  let g1 ← Lock.acquire lock_b
  touch g
  touch g1

/-- [lt_stateful_drop::array_elements_drop_in_index_order]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 723:0-728:1
    Visibility: public -/
def array_elements_drop_in_index_order
  (lock_a : Lock) (lock_b : Lock) (lock_c : Lock) : Result Unit := do
  let g ← Lock.acquire lock_a
  let g1 ← Lock.acquire lock_b
  let g2 ← Lock.acquire lock_c
  let g3 ← Array.index_usize (Array.make 3#usize [ g, g1, g2 ]) 0#usize
  touch g3
  let g4 ← Array.index_usize (Array.make 3#usize [ g, g1, g2 ]) 1#usize
  touch g4
  let g5 ← Array.index_usize (Array.make 3#usize [ g, g1, g2 ]) 2#usize
  touch g5

/-- [lt_stateful_drop::forgotten_guard_has_no_release]:
    Source: 'tests/src/lt-stateful-drop.rs', lines 733:0-737:1
    Visibility: public -/
def forgotten_guard_has_no_release (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  core.mem.forget g
  do_other_work

end lt_stateful_drop
