-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_core]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_core

/-- [core::mem::drop]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 1000:0-1002:24
    Name pattern: [core::mem::drop]
    Visibility: public -/
@[rust_fun "core::mem::drop"]
axiom core.mem.drop {T : Type} : T → Result Unit

/-- [lt_stateful_core::Lock]
    Source: 'tests/src/lt-stateful-core.rs', lines 9:0-11:1
    Visibility: public -/
axiom Lock (T : Type) : Type

/-- [lt_stateful_core::ReadGuard]
    Source: 'tests/src/lt-stateful-core.rs', lines 14:0-16:1
    Visibility: public -/
axiom ReadGuard (T : Type) : Type

/-- [lt_stateful_core::WriteGuard]
    Source: 'tests/src/lt-stateful-core.rs', lines 19:0-21:1
    Visibility: public -/
axiom WriteGuard (T : Type) : Type

/-- [lt_stateful_core::{lt_stateful_core::Lock<T>}::read]:
    Source: 'tests/src/lt-stateful-core.rs', lines 26:4-28:5
    Visibility: public -/
axiom Lock.read
  {T : Type} :
  Lock T → Result ((ReadGuard T) × (ReadGuard T → Result Unit))

/-- [lt_stateful_core::{lt_stateful_core::Lock<T>}::write]:
    Source: 'tests/src/lt-stateful-core.rs', lines 32:4-34:5
    Visibility: public -/
axiom Lock.write
  {T : Type} :
  Lock T → Result ((WriteGuard T) × (WriteGuard T → Result Unit))

/-- [lt_stateful_core::{lt_stateful_core::ReadGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-core.rs', lines 39:4-41:5
    Visibility: public -/
axiom ReadGuard.get {T : Type} : ReadGuard T → Result T

/-- [lt_stateful_core::{lt_stateful_core::ReadGuard<'a, T>}::refresh]:
    Source: 'tests/src/lt-stateful-core.rs', lines 45:4-47:5
    Visibility: public -/
axiom ReadGuard.refresh
  {T : Type} : ReadGuard T → Result ((ReadGuard T) × (Result Unit))

/-- [lt_stateful_core::{lt_stateful_core::WriteGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-core.rs', lines 52:4-54:5
    Visibility: public -/
axiom WriteGuard.get {T : Type} : WriteGuard T → Result T

/-- [lt_stateful_core::{lt_stateful_core::WriteGuard<'a, T>}::get_mut]:
    Source: 'tests/src/lt-stateful-core.rs', lines 58:4-60:5
    Visibility: public -/
axiom WriteGuard.get_mut
  {T : Type} :
  WriteGuard T → Result (T × (T → Result (WriteGuard T)) × (WriteGuard T
    → Result (WriteGuard T)))

/-- [lt_stateful_core::read_copy]:
    Source: 'tests/src/lt-stateful-core.rs', lines 63:0-66:1
    Visibility: public -/
def read_copy (lock : Lock Std.I32) : Result Std.I32 := do
  let p ← Lock.read lock
  let (guard, read_back) := p
  let i ← ReadGuard.get guard
  read_back guard
  ok i

/-- [lt_stateful_core::write_set]:
    Source: 'tests/src/lt-stateful-core.rs', lines 68:0-71:1
    Visibility: public -/
def write_set (lock : Lock Std.I32) : Result Unit := do
  let p ← Lock.write lock
  let (guard, write_back) := p
  let t ← WriteGuard.get_mut guard
  let (_, get_mut_back, get_mut_back1) := t
  let guard1 ← get_mut_back 42#i32
  let guard2 ← get_mut_back1 guard1
  write_back guard2

/-- [lt_stateful_core::Cell]
    Source: 'tests/src/lt-stateful-core.rs', lines 73:0-75:1
    Visibility: public -/
structure Cell where
  value : Std.I32

/-- [lt_stateful_core::{lt_stateful_core::Cell}::set]:
    Source: 'tests/src/lt-stateful-core.rs', lines 78:4-80:5
    Visibility: public -/
def Cell.set (self : Cell) (value : Std.I32) : Result Cell := do
  ok { value }

/-- [lt_stateful_core::write_method]:
    Source: 'tests/src/lt-stateful-core.rs', lines 83:0-86:1
    Visibility: public -/
def write_method (lock : Lock Cell) : Result Unit := do
  let p ← Lock.write lock
  let (guard, write_back) := p
  let t ← WriteGuard.get_mut guard
  let (c, get_mut_back, get_mut_back1) := t
  let c1 ← Cell.set c 42#i32
  let guard1 ← get_mut_back c1
  let guard2 ← get_mut_back1 guard1
  write_back guard2

/-- [lt_stateful_core::read_then_write]:
    Source: 'tests/src/lt-stateful-core.rs', lines 88:0-93:1
    Visibility: public -/
def read_then_write
  (read_lock : Lock Std.I32) (write_lock : Lock Std.I32) : Result Unit := do
  let p ← Lock.read read_lock
  let (read_guard, read_back) := p
  let _ ← ReadGuard.get read_guard
  core.mem.drop read_guard
  read_back read_guard
  let p1 ← Lock.write write_lock
  let (_write_guard, write_back) := p1
  write_back _write_guard

/-- [lt_stateful_core::scoped_read_then_write]:
    Source: 'tests/src/lt-stateful-core.rs', lines 95:0-101:1
    Visibility: public -/
def scoped_read_then_write
  (read_lock : Lock Std.I32) (write_lock : Lock Std.I32) : Result Unit := do
  let p ← Lock.read read_lock
  let (read_guard, read_back) := p
  let _ ← ReadGuard.get read_guard
  read_back read_guard
  let p1 ← Lock.write write_lock
  let (_write_guard, write_back) := p1
  write_back _write_guard

/-- [lt_stateful_core::write_two]:
    Source: 'tests/src/lt-stateful-core.rs', lines 103:0-108:1
    Visibility: public -/
def write_two
  (first : Lock Std.I32) (second : Lock Std.I32) : Result Unit := do
  let p ← Lock.write first
  let (first_guard, write_back) := p
  let p1 ← Lock.write second
  let (second_guard, write_back1) := p1
  let t ← WriteGuard.get_mut first_guard
  let (_, get_mut_back, get_mut_back1) := t
  let first_guard1 ← get_mut_back 1#i32
  let t1 ← WriteGuard.get_mut second_guard
  let (_, get_mut_back2, get_mut_back3) := t1
  let second_guard1 ← get_mut_back2 2#i32
  let second_guard2 ← get_mut_back3 second_guard1
  write_back1 second_guard2
  let first_guard2 ← get_mut_back1 first_guard1
  write_back first_guard2

/-- [lt_stateful_core::update_external_and_lock]:
    Source: 'tests/src/lt-stateful-core.rs', lines 110:0-114:1
    Visibility: public -/
def update_external_and_lock
  (value : Std.I32) (lock : Lock Std.I32) : Result Std.I32 := do
  let p ← Lock.write lock
  let (guard, write_back) := p
  let t ← WriteGuard.get_mut guard
  let (_, get_mut_back, get_mut_back1) := t
  let guard1 ← get_mut_back 7#i32
  let guard2 ← get_mut_back1 guard1
  write_back guard2
  ok 99#i32

/-- [lt_stateful_core::call_update_external]:
    Source: 'tests/src/lt-stateful-core.rs', lines 116:0-120:1
    Visibility: public -/
def call_update_external (lock : Lock Std.I32) : Result Std.I32 := do
  update_external_and_lock 0#i32 lock

/-- [lt_stateful_core::choose]:
    Source: 'tests/src/lt-stateful-core.rs', lines 122:0-126:1
    Visibility: public -/
def choose
  (value : Std.I32) (lock : Lock Std.I32) :
  Result (Std.I32 × (Std.I32 → Result Std.I32))
  := do
  let p ← Lock.write lock
  let (guard, write_back) := p
  let t ← WriteGuard.get_mut guard
  let (_, get_mut_back, get_mut_back1) := t
  let guard1 ← get_mut_back 1#i32
  let guard2 ← get_mut_back1 guard1
  write_back guard2
  ok (value, ok)

/-- [lt_stateful_core::call_choose]:
    Source: 'tests/src/lt-stateful-core.rs', lines 128:0-135:1
    Visibility: public -/
def call_choose (lock : Lock Std.I32) : Result Std.I32 := do
  let p ← choose 0#i32 lock
  let (_, choose_back) := p
  choose_back 5#i32

/-- [lt_stateful_core::write_branch]:
    Source: 'tests/src/lt-stateful-core.rs', lines 137:0-145:1
    Visibility: public -/
def write_branch
  (lock : Lock Std.I32) (choose_first : Bool) : Result Unit := do
  let p ← Lock.write lock
  let (guard, write_back) := p
  let p1 ←
    if choose_first
    then
      do
      let t ← WriteGuard.get_mut guard
      let (_, get_mut_back, get_mut_back1) := t
      let guard1 ← get_mut_back 1#i32
      ok (guard1, get_mut_back1)
    else
      do
      let t ← WriteGuard.get_mut guard
      let (_, get_mut_back, get_mut_back1) := t
      let guard1 ← get_mut_back 2#i32
      ok (guard1, get_mut_back1)
  let (guard1, back) := p1
  let _ ← WriteGuard.get guard1
  let wg ← back guard1
  write_back wg

/-- [lt_stateful_core::refresh_one]:
    Source: 'tests/src/lt-stateful-core.rs', lines 147:0-151:1
    Visibility: public -/
def refresh_one (lock : Lock Std.I32) : Result Unit := do
  let p ← Lock.read lock
  let (guard, read_back) := p
  let p1 ← ReadGuard.refresh guard
  let (guard1, r) := p1
  r
  let _ ← ReadGuard.get guard1
  read_back guard1

/-- [lt_stateful_core::refresh_cross]:
    Source: 'tests/src/lt-stateful-core.rs', lines 153:0-161:1
    Visibility: public -/
def refresh_cross
  (first : Lock Std.I32) (second : Lock Std.I32) : Result Unit := do
  let p ← Lock.read first
  let (first_guard, read_back) := p
  let p1 ← Lock.read second
  let (second_guard, read_back1) := p1
  let p2 ← ReadGuard.refresh first_guard
  let (first_guard1, r) := p2
  r
  let _ ← ReadGuard.get second_guard
  read_back1 second_guard
  let _ ← ReadGuard.get first_guard1
  read_back first_guard1

/-- [lt_stateful_core::refresh_branch]:
    Source: 'tests/src/lt-stateful-core.rs', lines 163:0-169:1
    Visibility: public -/
def refresh_branch
  (lock : Lock Std.I32) (refresh : Bool) : Result Std.I32 := do
  let p ← Lock.read lock
  let (guard, read_back) := p
  let guard1 ←
    if refresh
    then
      do
      let p1 ← ReadGuard.refresh guard
      let (guard2, r) := p1
      r
      ok guard2
    else ok guard
  let i ← ReadGuard.get guard1
  read_back guard1
  ok i

/-- [lt_stateful_core::refresh_first_loop]: loop body 0:
    Source: 'tests/src/lt-stateful-core.rs', lines 175:4-178:5
    Visibility: public -/
@[rust_loop_body]
def refresh_first_loop_loop.body
  (count : Std.U32) (first_guard : ReadGuard Std.I32) (index : Std.U32) :
  Result (ControlFlow ((ReadGuard Std.I32) × Std.U32) (ReadGuard Std.I32))
  := do
  if index < count
  then
    let p ← ReadGuard.refresh first_guard
    let (first_guard1, r) := p
    r
    let index1 ← index + 1#u32
    ok (cont (first_guard1, index1))
  else ok (done first_guard)

/-- [lt_stateful_core::refresh_first_loop]: loop 0:
    Source: 'tests/src/lt-stateful-core.rs', lines 175:4-178:5
    Visibility: public -/
@[rust_loop]
def refresh_first_loop_loop
  (count : Std.U32) (first_guard : ReadGuard Std.I32) (index : Std.U32) :
  Result (ReadGuard Std.I32)
  := do
  loop
    (fun (first_guard1, index1) => refresh_first_loop_loop.body count
      first_guard1 index1)
    (first_guard, index)

/-- [lt_stateful_core::refresh_first_loop]:
    Source: 'tests/src/lt-stateful-core.rs', lines 171:0-180:1
    Visibility: public -/
def refresh_first_loop
  (first : Lock Std.I32) (second : Lock Std.I32) (count : Std.U32) :
  Result Std.I32
  := do
  let p ← Lock.read first
  let (first_guard, read_back) := p
  let p1 ← Lock.read second
  let (second_guard, read_back1) := p1
  let first_guard1 ← refresh_first_loop_loop count first_guard 0#u32
  let i ← ReadGuard.get first_guard1
  let i1 ← ReadGuard.get second_guard
  let i2 ← i + i1
  read_back1 second_guard
  read_back first_guard1
  ok i2

/-- [lt_stateful_core::observe]:
    Source: 'tests/src/lt-stateful-core.rs', lines 183:0-186:1
    Visibility: public -/
def observe (lock : Lock Std.I32) : Result (Std.I32 × (Result Unit)) := do
  let p ← Lock.read lock
  let (guard, read_back) := p
  let i ← ReadGuard.get guard
  read_back guard
  ok (i, ok ())

end lt_stateful_core
