-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_control]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_control

/-- [lt_stateful_control::Lock]
    Source: 'tests/src/lt-stateful-control.rs', lines 83:0-85:1
    Visibility: public -/
axiom Lock (T : Type) : Type

/-- [lt_stateful_control::ReadGuard]
    Source: 'tests/src/lt-stateful-control.rs', lines 90:0-92:1
    Visibility: public -/
axiom ReadGuard (T : Type) : Type

/-- [lt_stateful_control::WriteGuard]
    Source: 'tests/src/lt-stateful-control.rs', lines 97:0-99:1
    Visibility: public -/
axiom WriteGuard (T : Type) : Type

/-- [lt_stateful_control::{lt_stateful_control::Lock<T>}::new]:
    Source: 'tests/src/lt-stateful-control.rs', lines 103:4-105:5
    Visibility: public -/
axiom Lock.new {T : Type} : T → Result (Lock T)

/-- [lt_stateful_control::{lt_stateful_control::Lock<T>}::read]:
    Source: 'tests/src/lt-stateful-control.rs', lines 109:4-111:5
    Visibility: public -/
axiom Lock.read {T : Type} : Lock T → Result (ReadGuard T)

/-- [lt_stateful_control::{lt_stateful_control::Lock<T>}::write]:
    Source: 'tests/src/lt-stateful-control.rs', lines 115:4-117:5
    Visibility: public -/
axiom Lock.write
  {T : Type} : Lock T → Result ((WriteGuard T) × (WriteGuard T → Unit))

/-- [lt_stateful_control::{lt_stateful_control::Lock<T>}::try_read]:
    Source: 'tests/src/lt-stateful-control.rs', lines 121:4-123:5
    Visibility: public -/
axiom Lock.try_read {T : Type} : Lock T → Result (Option (ReadGuard T))

/-- [lt_stateful_control::{lt_stateful_control::Lock<T>}::try_write]:
    Source: 'tests/src/lt-stateful-control.rs', lines 127:4-129:5
    Visibility: public -/
axiom Lock.try_write
  {T : Type} :
  Lock T → Result ((Option (WriteGuard T)) × (Option (WriteGuard T) →
    Unit))

/-- [lt_stateful_control::{lt_stateful_control::ReadGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-control.rs', lines 135:4-137:5
    Visibility: public -/
axiom ReadGuard.get {T : Type} : ReadGuard T → Result T

/-- [lt_stateful_control::{lt_stateful_control::ReadGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-control.rs', lines 143:4-143:27
    Visibility: public -/
axiom ReadGuard.release {T : Type} : ReadGuard T → Result Unit

/-- [lt_stateful_control::{lt_stateful_control::WriteGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-control.rs', lines 149:4-151:5
    Visibility: public -/
axiom WriteGuard.get {T : Type} : WriteGuard T → Result T

/-- [lt_stateful_control::{lt_stateful_control::WriteGuard<'a, T>}::get_mut]:
    Source: 'tests/src/lt-stateful-control.rs', lines 156:4-158:5
    Visibility: public -/
axiom WriteGuard.get_mut
  {T : Type} :
  WriteGuard T → Result (T × (T → WriteGuard T) × (WriteGuard T →
    WriteGuard T))

/-- [lt_stateful_control::{lt_stateful_control::WriteGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-control.rs', lines 162:4-162:27
    Visibility: public -/
axiom WriteGuard.release {T : Type} : WriteGuard T → Result (WriteGuard T)

/-- [lt_stateful_control::Pair]
    Source: 'tests/src/lt-stateful-control.rs', lines 168:0-171:1
    Visibility: public -/
structure Pair where
  a : Std.I32
  b : Std.I32

/-- [lt_stateful_control::if_both_branches_acquire_write_release]:
    Source: 'tests/src/lt-stateful-control.rs', lines 181:0-195:1
    Visibility: public -/
def if_both_branches_acquire_write_release
  (lock : Lock Std.I32) (b : Bool) : Result Std.I32 := do
  if b
  then
    let (guard, _) ← Lock.write lock
    let (i, get_mut_back, _) ← WriteGuard.get_mut guard
    let i1 ← i + 1#i32
    let guard1 := get_mut_back i1
    let v ← WriteGuard.get guard1
    let _ ← WriteGuard.release guard1
    ok v
  else
    let (guard, _) ← Lock.write lock
    let (i, get_mut_back, _) ← WriteGuard.get_mut guard
    let i1 ← i + 2#i32
    let guard1 := get_mut_back i1
    let v ← WriteGuard.get guard1
    let _ ← WriteGuard.release guard1
    ok v

/-- [lt_stateful_control::if_both_branches_acquire_read_release]:
    Source: 'tests/src/lt-stateful-control.rs', lines 201:0-214:1
    Visibility: public -/
def if_both_branches_acquire_read_release
  (lock : Lock Std.I32) (b : Bool) (extra : Std.I32) : Result Std.I32 := do
  let base ←
    if b
    then
      do
      let guard ← Lock.read lock
      let v ← ReadGuard.get guard
      ReadGuard.release guard
      ok v
    else
      do
      let guard ← Lock.read lock
      let v ← ReadGuard.get guard
      ReadGuard.release guard
      ok v
  base + extra

/-- [lt_stateful_control::if_only_one_branch_acquires]:
    Source: 'tests/src/lt-stateful-control.rs', lines 220:0-229:1
    Visibility: public -/
def if_only_one_branch_acquires
  (lock : Lock Std.I32) (b : Bool) (fallback : Std.I32) : Result Std.I32 := do
  if b
  then
    let guard ← Lock.read lock
    let v ← ReadGuard.get guard
    ReadGuard.release guard
    ok v
  else ok fallback

/-- [lt_stateful_control::if_only_one_branch_acquires_asymmetric_use]:
    Source: 'tests/src/lt-stateful-control.rs', lines 235:0-245:1
    Visibility: public -/
def if_only_one_branch_acquires_asymmetric_use
  (lock : Lock Std.I32) (b : Bool) (fallback : Std.I32) : Result Std.I32 := do
  if b
  then
    let (guard, _) ← Lock.write lock
    let (i, get_mut_back, _) ← WriteGuard.get_mut guard
    let i1 ← i + 10#i32
    let guard1 := get_mut_back i1
    let v ← WriteGuard.get guard1
    let _ ← WriteGuard.release guard1
    ok v
  else let i ← fallback * 2#i32
       i + 1#i32

/-- [lt_stateful_control::else_if_chain_independent_guards]:
    Source: 'tests/src/lt-stateful-control.rs', lines 254:0-272:1
    Visibility: public -/
def else_if_chain_independent_guards
  (lock : Lock Std.I32) (selector : Std.I32) : Result Std.I32 := do
  if selector = 0#i32
  then
    let guard ← Lock.read lock
    let v ← ReadGuard.get guard
    ReadGuard.release guard
    ok v
  else
    if selector = 1#i32
    then
      let (guard, _) ← Lock.write lock
      let (i, get_mut_back, _) ← WriteGuard.get_mut guard
      let i1 ← i + 1#i32
      let guard1 := get_mut_back i1
      let v ← WriteGuard.get guard1
      let _ ← WriteGuard.release guard1
      ok v
    else
      let guard ← Lock.read lock
      let v ← ReadGuard.get guard
      ReadGuard.release guard
      v * 2#i32

/-- [lt_stateful_control::if_asymmetric_branches_return_open_guard]:
    Source: 'tests/src/lt-stateful-control.rs', lines 290:0-301:1
    Visibility: public -/
def if_asymmetric_branches_return_open_guard
  (lock : Lock Std.I32) (b : Bool) (bias : Std.I32) :
  Result ((WriteGuard Std.I32) × (WriteGuard Std.I32 → Unit))
  := do
  if b
  then let (wg, _) ← Lock.write lock
       let back := fun wg1 => ()
       ok (wg, back)
  else
    let i ← bias * 2#i32
    let _ ← i + 1#i32
    let (wg, _) ← Lock.write lock
    let back := fun wg1 => ()
    ok (wg, back)

/-- [lt_stateful_control::GuardKind]
    Source: 'tests/src/lt-stateful-control.rs', lines 306:0-309:1
    Visibility: public -/
@[discriminant isize]
inductive GuardKind (T : Type) where
| Read : ReadGuard T → GuardKind T
| Write : WriteGuard T → GuardKind T

/-- [lt_stateful_control::match_join_returns_guard_enum]:
    Source: 'tests/src/lt-stateful-control.rs', lines 322:0-328:1
    Visibility: public -/
def match_join_returns_guard_enum
  (lock : Lock Std.I32) (selector : Std.I32) :
  Result ((GuardKind Std.I32) × (GuardKind Std.I32 → Unit))
  := do
  match selector with
  | 0#iscalar =>
    let rg ← Lock.read lock
    let back := fun gk => ()
    ok (GuardKind.Read rg, back)
  | 1#iscalar =>
    let (wg, _) ← Lock.write lock
    let back := fun gk => ()
    ok (GuardKind.Write wg, back)
  | _ =>
    let rg ← Lock.read lock
    let back := fun gk => ()
    ok (GuardKind.Read rg, back)

/-- [lt_stateful_control::early_return_after_release]:
    Source: 'tests/src/lt-stateful-control.rs', lines 338:0-346:1
    Visibility: public -/
def early_return_after_release
  (lock : Lock Std.I32) (b : Bool) : Result Std.I32 := do
  let guard ← Lock.read lock
  let v ← ReadGuard.get guard
  ReadGuard.release guard
  if b
  then ok v
  else v + 1#i32

/-- [lt_stateful_control::early_return_without_release]:
    Source: 'tests/src/lt-stateful-control.rs', lines 355:0-364:1
    Visibility: public -/
def early_return_without_release
  (lock : Lock Std.I32) (b : Bool) : Result Std.I32 := do
  let (guard, _) ← Lock.write lock
  if b
  then ok (-1)#i32
  else let v ← WriteGuard.get guard
       let _ ← WriteGuard.release guard
       ok v

/-- [lt_stateful_control::match_three_arms_independent_guards]:
    Source: 'tests/src/lt-stateful-control.rs', lines 374:0-396:1
    Visibility: public -/
def match_three_arms_independent_guards
  (lock : Lock Std.I32) (selector : Std.I32) : Result Std.I32 := do
  match selector with
  | 0#iscalar =>
    let guard ← Lock.read lock
    let v ← ReadGuard.get guard
    ReadGuard.release guard
    ok v
  | 1#iscalar =>
    let (guard, _) ← Lock.write lock
    let (i, get_mut_back, _) ← WriteGuard.get_mut guard
    let i1 ← i + 1#i32
    let guard1 := get_mut_back i1
    let v ← WriteGuard.get guard1
    let _ ← WriteGuard.release guard1
    ok v
  | _ =>
    let guard ← Lock.read lock
    let v ← ReadGuard.get guard
    ReadGuard.release guard
    v * 2#i32

/-- [lt_stateful_control::guard_before_match_released_in_each_arm]:
    Source: 'tests/src/lt-stateful-control.rs', lines 404:0-419:1
    Visibility: public -/
def guard_before_match_released_in_each_arm
  (lock : Lock Std.I32) (selector : Std.I32) : Result Std.I32 := do
  let (guard, _) ← Lock.write lock
  let (guard1, result) ←
    match selector with
    | 0#iscalar => do
                   let result1 ← WriteGuard.get guard
                   ok (guard, result1)
    | 1#iscalar =>
      do
      let (i, get_mut_back, _) ← WriteGuard.get_mut guard
      let i1 ← i + 1#i32
      let guard2 := get_mut_back i1
      let result1 ← WriteGuard.get guard2
      ok (guard2, result1)
    | _ =>
      do
      let (i, get_mut_back, _) ← WriteGuard.get_mut guard
      let i1 ← i + 2#i32
      let guard2 := get_mut_back i1
      let i2 ← WriteGuard.get guard2
      let result1 ← i2 * 2#i32
      ok (guard2, result1)
  let _ ← WriteGuard.release guard1
  ok result

/-- [lt_stateful_control::guard_before_match_one_arm_forgets_release]:
    Source: 'tests/src/lt-stateful-control.rs', lines 429:0-449:1
    Visibility: public -/
def guard_before_match_one_arm_forgets_release
  (lock : Lock Std.I32) (selector : Std.I32) : Result Std.I32 := do
  let (guard, _) ← Lock.write lock
  match selector with
  | 0#iscalar =>
    let v ← WriteGuard.get guard
    let _ ← WriteGuard.release guard
    ok v
  | 1#iscalar =>
    let (i, get_mut_back, _) ← WriteGuard.get_mut guard
    let i1 ← i + 1#i32
    let guard1 := get_mut_back i1
    let v ← WriteGuard.get guard1
    let _ ← WriteGuard.release guard1
    ok v
  | _ =>
    let (i, get_mut_back, _) ← WriteGuard.get_mut guard
    let i1 ← i + 2#i32
    let guard1 := get_mut_back i1
    WriteGuard.get guard1

/-- [lt_stateful_control::nested_match_guard_threading]:
    Source: 'tests/src/lt-stateful-control.rs', lines 456:0-476:1
    Visibility: public -/
def nested_match_guard_threading
  (lock : Lock Std.I32) (outer_sel : Bool) (inner_sel : Bool) :
  Result Std.I32
  := do
  let (guard, _) ← Lock.write lock
  let (guard1, result) ←
    if outer_sel
    then
      if inner_sel
      then
        do
        let (i, get_mut_back, _) ← WriteGuard.get_mut guard
        let i1 ← i + 1#i32
        let guard2 := get_mut_back i1
        let result1 ← WriteGuard.get guard2
        ok (guard2, result1)
      else do
           let result1 ← WriteGuard.get guard
           ok (guard, result1)
    else
      if inner_sel
      then do
           let result1 ← WriteGuard.get guard
           ok (guard, result1)
      else
        do
        let (i, get_mut_back, _) ← WriteGuard.get_mut guard
        let i1 ← i - 1#i32
        let guard2 := get_mut_back i1
        let result1 ← WriteGuard.get guard2
        ok (guard2, result1)
  let _ ← WriteGuard.release guard1
  ok result

/-- [lt_stateful_control::match_with_guard_clauses]:
    Source: 'tests/src/lt-stateful-control.rs', lines 486:0-508:1
    Visibility: public -/
def match_with_guard_clauses
  (lock : Lock Std.I32) (selector : Std.I32) (threshold : Std.I32) :
  Result Std.I32
  := do
  if selector > threshold
  then
    let guard ← Lock.read lock
    let v ← ReadGuard.get guard
    ReadGuard.release guard
    ok v
  else
    let i ← -. threshold
    if selector < i
    then
      let (guard, _) ← Lock.write lock
      let (i1, get_mut_back, _) ← WriteGuard.get_mut guard
      let i2 ← i1 - 1#i32
      let guard1 := get_mut_back i2
      let v ← WriteGuard.get guard1
      let _ ← WriteGuard.release guard1
      ok v
    else
      let guard ← Lock.read lock
      let v ← ReadGuard.get guard
      ReadGuard.release guard
      -. v

/-- [lt_stateful_control::short_circuit_and_guard_condition]:
    Source: 'tests/src/lt-stateful-control.rs', lines 518:0-525:1
    Visibility: public -/
def short_circuit_and_guard_condition
  (lock : Lock Std.I32) (b : Bool) : Result Bool := do
  if b
  then
    let guard ← Lock.read lock
    let v ← ReadGuard.get guard
    ReadGuard.release guard
    ok (v > 0#i32)
  else ok false

/-- [lt_stateful_control::short_circuit_or_guard_fallback]:
    Source: 'tests/src/lt-stateful-control.rs', lines 532:0-539:1
    Visibility: public -/
def short_circuit_or_guard_fallback
  (lock : Lock Std.I32) (b : Bool) : Result Bool := do
  if b
  then ok true
  else
    let guard ← Lock.read lock
    let v ← ReadGuard.get guard
    ReadGuard.release guard
    ok (v > 0#i32)

/-- [lt_stateful_control::if_let_try_write_no_else]:
    Source: 'tests/src/lt-stateful-control.rs', lines 549:0-554:1
    Visibility: public -/
def if_let_try_write_no_else (lock : Lock Std.I32) : Result Unit := do
  let (o, _) ← Lock.try_write lock
  match o with
  | none => ok ()
  | some guard =>
    let (i, get_mut_back, _) ← WriteGuard.get_mut guard
    let i1 ← i + 1#i32
    let guard1 := get_mut_back i1
    let _ ← WriteGuard.release guard1
    ok ()

/-- [lt_stateful_control::if_let_else_try_read_with_fallback]:
    Source: 'tests/src/lt-stateful-control.rs', lines 560:0-568:1
    Visibility: public -/
def if_let_else_try_read_with_fallback
  (lock : Lock Std.I32) (fallback : Std.I32) : Result Std.I32 := do
  let o ← Lock.try_read lock
  match o with
  | none => ok fallback
  | some guard => let v ← ReadGuard.get guard
                  ReadGuard.release guard
                  ok v

/-- [lt_stateful_control::let_else_try_read_or_return]:
    Source: 'tests/src/lt-stateful-control.rs', lines 579:0-586:1
    Visibility: public -/
def let_else_try_read_or_return
  (lock : Lock Std.I32) (fallback : Std.I32) : Result Std.I32 := do
  let o ← Lock.try_read lock
  match o with
  | none => ok fallback
  | some guard => let v ← ReadGuard.get guard
                  ReadGuard.release guard
                  ok v

/-- [lt_stateful_control::guard_around_callback_read]:
    Source: 'tests/src/lt-stateful-control.rs', lines 604:0-609:1
    Visibility: public -/
def guard_around_callback_read
  {T : Type} {F : Type} (coreopsfunctionFnOnceFTupleShared0TI32Inst :
  core.ops.function.FnOnce F T Std.I32) (lock : Lock T) (f : F) :
  Result Std.I32
  := do
  let guard ← Lock.read lock
  let t ← ReadGuard.get guard
  let result ← coreopsfunctionFnOnceFTupleShared0TI32Inst.call_once f t
  ReadGuard.release guard
  ok result

/-- [lt_stateful_control::guard_around_callback_with_internal_branch]:
    Source: 'tests/src/lt-stateful-control.rs', lines 617:0-630:1
    Visibility: public -/
def guard_around_callback_with_internal_branch
  {T : Type} {F : Type} (coreopsfunctionFnFPairShared0TBoolI32Inst :
  core.ops.function.Fn F (T × Bool) Std.I32) (lock : Lock T) (f : F)
  (branch : Bool) :
  Result Std.I32
  := do
  let guard ← Lock.read lock
  let result ←
    if branch
    then
      do
      let t ← ReadGuard.get guard
      coreopsfunctionFnFPairShared0TBoolI32Inst.call f (t, true)
    else
      do
      let t ← ReadGuard.get guard
      coreopsfunctionFnFPairShared0TBoolI32Inst.call f (t, false)
  ReadGuard.release guard
  ok result

/-- [lt_stateful_control::guard_around_panicking_callback]:
    Source: 'tests/src/lt-stateful-control.rs', lines 641:0-651:1
    Visibility: public -/
def guard_around_panicking_callback
  (lock : Lock Std.I32) (panic_now : Bool) (x : Std.I32) : Result Std.I32 := do
  let (guard, _) ← Lock.write lock
  let v ← WriteGuard.get guard
  massert (¬ panic_now)
  let result ← v + x
  let _ ← WriteGuard.release guard
  ok result

/-- [lt_stateful_control::maybe_fail]:
    Source: 'tests/src/lt-stateful-control.rs', lines 654:0-656:1
    Visibility: public -/
axiom maybe_fail : Std.I32 → Result (core.result.Result Std.I32 Std.U32)

/-- [lt_stateful_control::guard_branch_with_try]:
    Source: 'tests/src/lt-stateful-control.rs', lines 662:0-667:1
    Visibility: public -/
def guard_branch_with_try
  (lock : Lock Std.I32) (take_fallible : Bool) (x : Std.I32) :
  Result (core.result.Result Std.I32 Std.U32)
  := do
  let (guard, _) ← Lock.write lock
  if take_fallible
  then
    let r ← maybe_fail x
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let _ ← WriteGuard.release guard
      ok (core.result.Result.Ok val)
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.I32 (core.convert.FromSame Std.U32) residual
  else let _ ← WriteGuard.release guard
       ok (core.result.Result.Ok x)

/-- [lt_stateful_control::choose]:
    Source: 'tests/src/lt-stateful-control.rs', lines 678:0-684:1
    Visibility: public -/
def choose
  {T : Type} (b : Bool) (x : T) (y : T) : Result (T × (T → (T × T))) := do
  if b
  then let back := fun x1 => (x1, y)
       ok (x, back)
  else let back := fun y1 => (x, y1)
       ok (y, back)

/-- [lt_stateful_control::match_field_projection_no_lock]:
    Source: 'tests/src/lt-stateful-control.rs', lines 694:0-704:1
    Visibility: public -/
def match_field_projection_no_lock
  (selector : Std.I32) (x : Pair) (y : Pair) :
  Result (Std.I32 × (Std.I32 → (Pair × Pair)))
  := do
  match selector with
  | 0#iscalar => let back := fun i => ({ x with a := i }, y)
                 ok (x.a, back)
  | 1#iscalar => let back := fun i => ({ x with b := i }, y)
                 ok (x.b, back)
  | _ => let back := fun i => (x, { y with a := i })
         ok (y.a, back)

end lt_stateful_control
