-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_temporaries]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_temporaries

/-- [lt_stateful_temporaries::Lock]
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 66:0-66:16
    Visibility: public -/
axiom Lock : Type

/-- [lt_stateful_temporaries::Guard]
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 70:0-72:1
    Visibility: public -/
axiom Guard : Type

/-- [lt_stateful_temporaries::{impl core::ops::drop::Drop for lt_stateful_temporaries::Guard<'a>}::drop]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 116:4-118:5
    Visibility: public -/
axiom Guard.Insts.CoreOpsDropDrop.drop : Guard → Result Guard

/-- [lt_stateful_temporaries::{lt_stateful_temporaries::Lock}::acquire]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 78:4-80:5
    Visibility: public -/
axiom Lock.acquire : Lock → Result Guard

/-- [lt_stateful_temporaries::{lt_stateful_temporaries::Lock}::try_acquire]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 86:4-88:5
    Visibility: public -/
axiom Lock.try_acquire : Lock → Result (Option Guard)

/-- [lt_stateful_temporaries::{lt_stateful_temporaries::Guard<'a>}::is_valid]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 95:4-97:5
    Visibility: public -/
axiom Guard.is_valid : Guard → Result Bool

/-- [lt_stateful_temporaries::{lt_stateful_temporaries::Guard<'a>}::is_valid_with]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 103:4-105:5
    Visibility: public -/
axiom Guard.is_valid_with : Guard → Guard → Result Bool

/-- Trait implementation: [lt_stateful_temporaries::{impl core::ops::drop::Drop for lt_stateful_temporaries::Guard<'a>}]
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 114:0-119:1 -/
@[reducible]
def Guard.Insts.CoreOpsDropDrop : core.ops.drop.Drop Guard := {
  drop := Guard.Insts.CoreOpsDropDrop.drop
}

/-- [lt_stateful_temporaries::touch]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 123:0-123:27 -/
def touch (_g : Guard) : Result Unit := do
  ok ()

/-- [lt_stateful_temporaries::touch_bool]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 124:0-124:26 -/
def touch_bool (_b : Bool) : Result Unit := do
  ok ()

/-- [lt_stateful_temporaries::touch_item]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 125:0-125:25 -/
def touch_item (_x : Std.U32) : Result Unit := do
  ok ()

/-- [lt_stateful_temporaries::do_other_work]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 126:0-126:21 -/
def do_other_work : Result Unit := do
  ok ()

/-- [lt_stateful_temporaries::do_something]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 127:0-127:20 -/
def do_something : Result Unit := do
  ok ()

/-- [lt_stateful_temporaries::touch_owned]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 131:0-131:32 -/
def touch_owned (_g : Guard) : Result Unit := do
  ok ()

/-- [lt_stateful_temporaries::combine]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 136:0-138:1 -/
axiom combine : Guard → Guard → Result Bool

/-- [lt_stateful_temporaries::call_arg_temporary]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 151:0-154:1
    Visibility: public -/
def call_arg_temporary (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  touch g
  do_other_work

/-- [lt_stateful_temporaries::chained_call_temporary]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 166:0-168:1
    Visibility: public -/
def chained_call_temporary (lock : Lock) : Result Bool := do
  let g ← Lock.acquire lock
  Guard.is_valid g

/-- [lt_stateful_temporaries::temporary_in_return_position]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 179:0-181:1
    Visibility: public -/
def temporary_in_return_position (lock : Lock) : Result Bool := do
  let g ← Lock.acquire lock
  Guard.is_valid g

/-- [lt_stateful_temporaries::if_condition_temporary]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 193:0-199:1
    Visibility: public -/
def if_condition_temporary (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  let b ← Guard.is_valid g
  if b
  then do_something
  else do_other_work

/-- [lt_stateful_temporaries::while_condition_temporary]: loop body 0:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 1:0-213:5
    Visibility: public -/
@[rust_loop_body]
def while_condition_temporary_loop.body
  (lock : Lock) (n : Std.U32) : Result (ControlFlow Std.U32 Unit) := do
  let g ← Lock.acquire lock
  let b ← Guard.is_valid g
  if b
  then if n > 0#u32
       then let n1 ← n - 1#u32
            ok (cont n1)
       else ok (done ())
  else ok (done ())

/-- [lt_stateful_temporaries::while_condition_temporary]: loop 0:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 1:0-213:5
    Visibility: public -/
@[rust_loop]
def while_condition_temporary_loop
  (lock : Lock) (n : Std.U32) : Result Unit := do
  loop
    (fun n1 => while_condition_temporary_loop.body lock n1)
    n

/-- [lt_stateful_temporaries::while_condition_temporary]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 210:0-214:1
    Visibility: public -/
@[reducible]
def while_condition_temporary (lock : Lock) (n : Std.U32) : Result Unit := do
  while_condition_temporary_loop lock n

/-- [lt_stateful_temporaries::compound_expression_temporaries]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 229:0-232:1
    Visibility: public -/
def compound_expression_temporaries
  (lock_a : Lock) (lock_b : Lock) : Result Unit := do
  let g ← Lock.acquire lock_a
  let b ← Guard.is_valid g
  let ok1 ←
    if b
    then do
         let g1 ← Lock.acquire lock_b
         Guard.is_valid g1
    else ok false
  touch_bool ok1

/-- [lt_stateful_temporaries::match_arm_move_binding_temporary]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 244:0-248:1
    Visibility: public -/
def match_arm_move_binding_temporary (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  touch g

/-- [lt_stateful_temporaries::match_scrutinee_is_not_a_temporary_scope]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 265:0-269:1
    Visibility: public -/
def match_scrutinee_is_not_a_temporary_scope (lock : Lock) : Result Unit := do
  let _ ← Lock.acquire lock
  ok ()

/-- [lt_stateful_temporaries::if_let_some_temporary]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 282:0-286:1
    Visibility: public -/
def if_let_some_temporary (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  touch g

/-- [lt_stateful_temporaries::if_let_else_temporary]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 318:0-324:1
    Visibility: public -/
def if_let_else_temporary (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  let b ← Guard.is_valid g
  if b
  then do_something
  else do_other_work

/-- [lt_stateful_temporaries::for_loop_body_guard_per_iteration]: loop body 0:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 347:4-351:5
    Visibility: public -/
@[rust_loop_body]
def for_loop_body_guard_per_iteration_loop.body
  (lock : Lock) (iter : core.ops.range.Range Std.U32) :
  Result (ControlFlow (core.ops.range.Range Std.U32) Unit)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32 iter
  match o with
  | none => ok (done ())
  | some i => let g ← Lock.acquire lock
              touch g
              touch_item i
              ok (cont iter1)

/-- [lt_stateful_temporaries::for_loop_body_guard_per_iteration]: loop 0:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 347:4-351:5
    Visibility: public -/
@[rust_loop]
def for_loop_body_guard_per_iteration_loop
  (iter : core.ops.range.Range Std.U32) (lock : Lock) : Result Unit := do
  loop
    (fun iter1 => for_loop_body_guard_per_iteration_loop.body lock iter1)
    iter

/-- [lt_stateful_temporaries::for_loop_body_guard_per_iteration]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 346:0-352:1
    Visibility: public -/
@[reducible]
def for_loop_body_guard_per_iteration
  (lock : Lock) (n : Std.U32) : Result Unit := do
  for_loop_body_guard_per_iteration_loop { start := 0#u32, «end» := n } lock

/-- [lt_stateful_temporaries::temporary_lifetime_extension]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 367:0-370:1
    Visibility: public -/
def temporary_lifetime_extension (lock : Lock) : Result Unit := do
  let g_ref ← Lock.acquire lock
  touch g_ref

/-- [lt_stateful_temporaries::temporary_lifetime_extension_through_option]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 379:0-384:1
    Visibility: public -/
def temporary_lifetime_extension_through_option
  (lock : Lock) : Result Unit := do
  let g_ref ← Lock.acquire lock
  touch g_ref

/-- [lt_stateful_temporaries::let_underscore_is_a_plain_temporary]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 397:0-400:1
    Visibility: public -/
def let_underscore_is_a_plain_temporary (lock : Lock) : Result Unit := do
  let _ ← Lock.acquire lock
  do_other_work

/-- [lt_stateful_temporaries::let_underscore_extending_borrow]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 407:0-410:1
    Visibility: public -/
def let_underscore_extending_borrow (lock : Lock) : Result Unit := do
  let _ ← Lock.acquire lock
  do_other_work

/-- [lt_stateful_temporaries::call_arg_by_value_ownership]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 424:0-427:1
    Visibility: public -/
def call_arg_by_value_ownership (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  touch_owned g
  do_other_work

/-- [lt_stateful_temporaries::two_by_ref_arg_temporaries]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 440:0-443:1
    Visibility: public -/
def two_by_ref_arg_temporaries
  (lock_a : Lock) (lock_b : Lock) : Result Unit := do
  let g ← Lock.acquire lock_a
  let g1 ← Lock.acquire lock_b
  let _ ← combine g g1
  do_other_work

/-- [lt_stateful_temporaries::chained_receiver_with_trailing_code]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 455:0-458:1
    Visibility: public -/
def chained_receiver_with_trailing_code (lock : Lock) : Result Unit := do
  let g ← Lock.acquire lock
  let _ ← Guard.is_valid g
  do_other_work

/-- [lt_stateful_temporaries::receiver_and_arg_temporaries]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 472:0-475:1
    Visibility: public -/
def receiver_and_arg_temporaries
  (lock_a : Lock) (lock_b : Lock) : Result Unit := do
  let g ← Lock.acquire lock_a
  let g1 ← Lock.acquire lock_b
  let _ ← Guard.is_valid_with g g1
  do_other_work

/-- [lt_stateful_temporaries::tuple_temporary_field_projection]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 493:0-497:1
    Visibility: public -/
def tuple_temporary_field_projection (lock : Lock) : Result Bool := do
  let g ← Lock.acquire lock
  let ok1 ← Guard.is_valid g
  do_other_work
  ok ok1

/-- [lt_stateful_temporaries::return_some_temporary]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 513:0-515:1
    Visibility: public -/
def return_some_temporary (lock : Lock) : Result (Option Guard) := do
  let g ← Lock.acquire lock
  ok (some g)

/-- [lt_stateful_temporaries::while_let_temporary]: loop body 0:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 534:4-536:5
    Visibility: public -/
@[rust_loop_body]
def while_let_temporary_loop.body
  (lock : Lock) : Result (ControlFlow Unit Unit) := do
  let o ← Lock.try_acquire lock
  match o with
  | none => ok (done ())
  | some g => touch g
              ok (cont ())

/-- [lt_stateful_temporaries::while_let_temporary]: loop 0:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 534:4-536:5
    Visibility: public -/
@[rust_loop]
def while_let_temporary_loop (lock : Lock) : Result Unit := do
  loop
    (fun () => while_let_temporary_loop.body lock)
    ()

/-- [lt_stateful_temporaries::while_let_temporary]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 533:0-537:1
    Visibility: public -/
@[reducible]
def while_let_temporary (lock : Lock) : Result Unit := do
  while_let_temporary_loop lock

/-- [lt_stateful_temporaries::temporary_in_match_guard]:
    Source: 'tests/src/lt-stateful-temporaries.rs', lines 554:0-563:1
    Visibility: public -/
def temporary_in_match_guard
  (lock : Lock) (selector : Std.I32) : Result Unit := do
  let g ← Lock.acquire lock
  let b ← Guard.is_valid g
  if b
  then do_something
  else do_other_work

end lt_stateful_temporaries
