-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_loops]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_loops

/-- [lt_stateful_loops::Lock]
    Source: 'tests/src/lt-stateful-loops.rs', lines 91:0-93:1
    Visibility: public -/
axiom Lock (T : Type) : Type

/-- [lt_stateful_loops::ReadGuard]
    Source: 'tests/src/lt-stateful-loops.rs', lines 98:0-100:1
    Visibility: public -/
axiom ReadGuard (T : Type) : Type

/-- [lt_stateful_loops::WriteGuard]
    Source: 'tests/src/lt-stateful-loops.rs', lines 105:0-107:1
    Visibility: public -/
axiom WriteGuard (T : Type) : Type

/-- [lt_stateful_loops::{lt_stateful_loops::Lock<T>}::new]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 111:4-113:5
    Visibility: public -/
axiom Lock.new {T : Type} : T → Result (Lock T)

/-- [lt_stateful_loops::{lt_stateful_loops::Lock<T>}::read]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 117:4-119:5
    Visibility: public -/
axiom Lock.read {T : Type} : Lock T → Result (ReadGuard T)

/-- [lt_stateful_loops::{lt_stateful_loops::Lock<T>}::write]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 123:4-125:5
    Visibility: public -/
axiom Lock.write
  {T : Type} : Lock T → Result ((WriteGuard T) × (WriteGuard T → Unit))

/-- [lt_stateful_loops::{lt_stateful_loops::Lock<T>}::try_write]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 129:4-131:5
    Visibility: public -/
axiom Lock.try_write
  {T : Type} :
  Lock T → Result ((Option (WriteGuard T)) × (Option (WriteGuard T) →
    Unit))

/-- [lt_stateful_loops::{lt_stateful_loops::ReadGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 137:4-139:5
    Visibility: public -/
axiom ReadGuard.get {T : Type} : ReadGuard T → Result T

/-- [lt_stateful_loops::{lt_stateful_loops::ReadGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 145:4-145:27
    Visibility: public -/
axiom ReadGuard.release {T : Type} : ReadGuard T → Result Unit

/-- [lt_stateful_loops::{lt_stateful_loops::WriteGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 151:4-153:5
    Visibility: public -/
axiom WriteGuard.get {T : Type} : WriteGuard T → Result T

/-- [lt_stateful_loops::{lt_stateful_loops::WriteGuard<'a, T>}::get_mut]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 159:4-161:5
    Visibility: public -/
axiom WriteGuard.get_mut
  {T : Type} :
  WriteGuard T → Result (T × (T → WriteGuard T) × (WriteGuard T →
    WriteGuard T))

/-- [lt_stateful_loops::{lt_stateful_loops::WriteGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 165:4-165:27
    Visibility: public -/
axiom WriteGuard.release {T : Type} : WriteGuard T → Result (WriteGuard T)

/-- [lt_stateful_loops::acquire_release_each_iteration_for]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 183:4-187:5
    Visibility: public -/
@[rust_loop]
def acquire_release_each_iteration_for_loop
  (iter : core.ops.range.Range Std.U32) (lock : Lock Std.I32) (total : Std.I32)
  :
  Result Std.I32
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32 iter
  match o with
  | none => ok total
  | some _ =>
    let guard ← Lock.read lock
    let i ← ReadGuard.get guard
    let total1 ← total + i
    ReadGuard.release guard
    acquire_release_each_iteration_for_loop iter1 lock total1
partial_fixpoint

/-- [lt_stateful_loops::acquire_release_each_iteration_for]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 181:0-189:1
    Visibility: public -/
@[reducible]
def acquire_release_each_iteration_for
  (lock : Lock Std.I32) (n : Std.U32) : Result Std.I32 := do
  acquire_release_each_iteration_for_loop { start := 0#u32, «end» := n } lock
    0#i32

/-- [lt_stateful_loops::loop_with_break_after_release]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 1:0-207:5
    Visibility: public -/
@[rust_loop]
def loop_with_break_after_release_loop
  (lock : Lock Std.I32) (n : Std.U32) (stop_value : Std.I32) (i : Std.U32) :
  Result Std.U32
  := do
  if i >= n
  then ok i
  else
    let guard ← Lock.read lock
    let v ← ReadGuard.get guard
    ReadGuard.release guard
    if v = stop_value
    then ok i
    else
      let i1 ← i + 1#u32
      loop_with_break_after_release_loop lock n stop_value i1
partial_fixpoint

/-- [lt_stateful_loops::loop_with_break_after_release]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 194:0-209:1
    Visibility: public -/
@[reducible]
def loop_with_break_after_release
  (lock : Lock Std.I32) (n : Std.U32) (stop_value : Std.I32) :
  Result Std.U32
  := do
  loop_with_break_after_release_loop lock n stop_value 0#u32

/-- [lt_stateful_loops::while_loop_conditional_acquire_then_break]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 1:0-228:5
    Visibility: public -/
@[rust_loop]
def while_loop_conditional_acquire_then_break_loop
  (lock : Lock Std.I32) (n : Std.U32) (stop_at : Std.I32) (i : Std.U32) :
  Result Std.U32
  := do
  if i < n
  then
    let i1 ← i % 2#u32
    if i1 = 0#u32
    then
      let (guard, _) ← Lock.write lock
      let v ← WriteGuard.get guard
      let _ ← WriteGuard.release guard
      if v = stop_at
      then ok i
      else
        let i2 ← i + 1#u32
        while_loop_conditional_acquire_then_break_loop lock n stop_at i2
    else
      let i2 ← i + 1#u32
      while_loop_conditional_acquire_then_break_loop lock n stop_at i2
  else ok i
partial_fixpoint

/-- [lt_stateful_loops::while_loop_conditional_acquire_then_break]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 216:0-230:1
    Visibility: public -/
def while_loop_conditional_acquire_then_break
  (lock : Lock Std.I32) (n : Std.U32) (stop_at : Std.I32) : Result Bool := do
  let i ← while_loop_conditional_acquire_then_break_loop lock n stop_at 0#u32
  ok (i < n)

/-- [lt_stateful_loops::loop_with_continue_after_release]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 1:0-248:5
    Visibility: public -/
@[rust_loop]
def loop_with_continue_after_release_loop
  (lock : Lock Std.I32) (n : Std.U32) (i : Std.U32) (total : Std.I32) :
  Result Std.I32
  := do
  if i < n
  then
    let guard ← Lock.read lock
    let v ← ReadGuard.get guard
    ReadGuard.release guard
    let i1 ← i + 1#u32
    if v < 0#i32
    then loop_with_continue_after_release_loop lock n i1 total
    else
      let total1 ← total + v
      loop_with_continue_after_release_loop lock n i1 total1
  else ok total
partial_fixpoint

/-- [lt_stateful_loops::loop_with_continue_after_release]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 236:0-250:1
    Visibility: public -/
@[reducible]
def loop_with_continue_after_release
  (lock : Lock Std.I32) (n : Std.U32) : Result Std.I32 := do
  loop_with_continue_after_release_loop lock n 0#u32 0#i32

/-- [lt_stateful_loops::loop_with_continue_skip_acquire]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 1:0-268:5
    Visibility: public -/
@[rust_loop]
def loop_with_continue_skip_acquire_loop
  (lock : Lock Std.I32) (n : Std.U32) (i : Std.U32) (total : Std.I32) :
  Result Std.I32
  := do
  if i < n
  then
    let i1 ← i + 1#u32
    let i2 ← i1 % 2#u32
    if i2 = 0#u32
    then loop_with_continue_skip_acquire_loop lock n i1 total
    else
      let (guard, _) ← Lock.write lock
      let i3 ← WriteGuard.get guard
      let total1 ← total + i3
      let _ ← WriteGuard.release guard
      loop_with_continue_skip_acquire_loop lock n i1 total1
  else ok total
partial_fixpoint

/-- [lt_stateful_loops::loop_with_continue_skip_acquire]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 257:0-270:1
    Visibility: public -/
@[reducible]
def loop_with_continue_skip_acquire
  (lock : Lock Std.I32) (n : Std.U32) : Result Std.I32 := do
  loop_with_continue_skip_acquire_loop lock n 0#u32 0#i32

/-- [lt_stateful_loops::for_loop_varying_lock_identity]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 284:4-288:5
    Visibility: public -/
@[rust_loop]
def for_loop_varying_lock_identity_loop
  (iter : core.slice.iter.Iter (Lock Std.I32)) (total : Std.I32) :
  Result Std.I32
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok total
  | some lock =>
    let guard ← Lock.read lock
    let i ← ReadGuard.get guard
    let total1 ← total + i
    ReadGuard.release guard
    for_loop_varying_lock_identity_loop iter1 total1
partial_fixpoint

/-- [lt_stateful_loops::for_loop_varying_lock_identity]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 282:0-290:1
    Visibility: public -/
def for_loop_varying_lock_identity
  (locks : Slice (Lock Std.I32)) : Result Std.I32 := do
  let iter ←
    SharedSlice.Insts.CoreIterTraitsCollectIntoIteratorSharedIter.into_iter
      locks
  for_loop_varying_lock_identity_loop iter 0#i32

/-- [lt_stateful_loops::return_from_loop_after_release]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 306:4-316:1
    Visibility: public -/
@[rust_loop]
def return_from_loop_after_release_loop
  (lock : Lock Std.I32) (n : Std.U32) (bail_at : Std.I32) (i : Std.U32) :
  Result Std.I32
  := do
  if i < n
  then
    let (guard, _) ← Lock.write lock
    let v ← WriteGuard.get guard
    let _ ← WriteGuard.release guard
    if v = bail_at
    then ok v
    else
      let i1 ← i + 1#u32
      return_from_loop_after_release_loop lock n bail_at i1
  else ok 0#i32
partial_fixpoint

/-- [lt_stateful_loops::return_from_loop_after_release]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 304:0-316:1
    Visibility: public -/
@[reducible]
def return_from_loop_after_release
  (lock : Lock Std.I32) (n : Std.U32) (bail_at : Std.I32) :
  Result Std.I32
  := do
  return_from_loop_after_release_loop lock n bail_at 0#u32

/-- [lt_stateful_loops::return_from_loop_without_release]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 328:4-338:1
    Visibility: public -/
@[rust_loop]
def return_from_loop_without_release_loop
  (lock : Lock Std.I32) (n : Std.U32) (bail_at : Std.I32) (i : Std.U32) :
  Result Std.I32
  := do
  if i < n
  then
    let (guard, _) ← Lock.write lock
    let i1 ← WriteGuard.get guard
    if i1 = bail_at
    then ok (-1)#i32
    else
      let _ ← WriteGuard.release guard
      let i2 ← i + 1#u32
      return_from_loop_without_release_loop lock n bail_at i2
  else ok 0#i32
partial_fixpoint

/-- [lt_stateful_loops::return_from_loop_without_release]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 326:0-338:1
    Visibility: public -/
@[reducible]
def return_from_loop_without_release
  (lock : Lock Std.I32) (n : Std.U32) (bail_at : Std.I32) :
  Result Std.I32
  := do
  return_from_loop_without_release_loop lock n bail_at 0#u32

/-- [lt_stateful_loops::loop_with_three_way_exit_consistent_release]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 1:0-371:1
    Visibility: public -/
@[rust_loop]
def loop_with_three_way_exit_consistent_release_loop
  (lock : Lock Std.I32) (n : Std.U32) (sentinel : Std.I32) (i : Std.U32) :
  Result Std.I32
  := do
  if i < n
  then
    let guard ← Lock.read lock
    let v ← ReadGuard.get guard
    ReadGuard.release guard
    if v = sentinel
    then ok v
    else
      let i1 ← i + 1#u32
      let i2 ← n / 2#u32
      if i1 = i2
      then ok 0#i32
      else loop_with_three_way_exit_consistent_release_loop lock n sentinel i1
  else ok 0#i32
partial_fixpoint

/-- [lt_stateful_loops::loop_with_three_way_exit_consistent_release]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 351:0-371:1
    Visibility: public -/
@[reducible]
def loop_with_three_way_exit_consistent_release
  (lock : Lock Std.I32) (n : Std.U32) (sentinel : Std.I32) :
  Result Std.I32
  := do
  loop_with_three_way_exit_consistent_release_loop lock n sentinel 0#u32

/-- [lt_stateful_loops::nested_loops_independent_guards]: loop 1:
    Source: 'tests/src/lt-stateful-loops.rs', lines 388:8-392:9
    Visibility: public -/
@[rust_loop]
def nested_loops_independent_guards_loop0_loop0
  (iter : core.ops.range.Range Std.U32) (lock : Lock Std.I32) (total : Std.I32)
  (outer_v : Std.I32) :
  Result Std.I32
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32 iter
  match o with
  | none => ok total
  | some _ =>
    let inner_guard ← Lock.read lock
    let i ← ReadGuard.get inner_guard
    let i1 ← i + outer_v
    let total1 ← total + i1
    ReadGuard.release inner_guard
    nested_loops_independent_guards_loop0_loop0 iter1 lock total1 outer_v
partial_fixpoint

/-- [lt_stateful_loops::nested_loops_independent_guards]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 384:4-393:5
    Visibility: public -/
@[rust_loop]
def nested_loops_independent_guards_loop0
  (iter : core.ops.range.Range Std.U32) (lock : Lock Std.I32)
  (inner_n : Std.U32) (total : Std.I32) :
  Result Std.I32
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32 iter
  match o with
  | none => ok total
  | some _ =>
    let outer_guard ← Lock.read lock
    let outer_v ← ReadGuard.get outer_guard
    ReadGuard.release outer_guard
    let total1 ←
      nested_loops_independent_guards_loop0_loop0
        { start := 0#u32, «end» := inner_n } lock total outer_v
    nested_loops_independent_guards_loop0 iter1 lock inner_n total1
partial_fixpoint

/-- [lt_stateful_loops::nested_loops_independent_guards]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 382:0-395:1
    Visibility: public -/
@[reducible]
def nested_loops_independent_guards
  (lock : Lock Std.I32) (outer_n : Std.U32) (inner_n : Std.U32) :
  Result Std.I32
  := do
  nested_loops_independent_guards_loop0 { start := 0#u32, «end» := outer_n }
    lock inner_n 0#i32

/-- [lt_stateful_loops::nested_loops_shared_outer_guard]: loop 1:
    Source: 'tests/src/lt-stateful-loops.rs', lines 403:8-405:9
    Visibility: public -/
@[rust_loop]
def nested_loops_shared_outer_guard_loop0_loop0
  (iter : core.ops.range.Range Std.U32)
  (back : WriteGuard Std.I32 → WriteGuard Std.I32)
  (guard : WriteGuard Std.I32) :
  Result ((WriteGuard Std.I32) × (WriteGuard Std.I32 → WriteGuard Std.I32))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32 iter
  match o with
  | none => ok (guard, back)
  | some _ =>
    let (i, get_mut_back, get_mut_back1) ← WriteGuard.get_mut guard
    let i1 ← i + 1#i32
    let guard1 := get_mut_back i1
    nested_loops_shared_outer_guard_loop0_loop0 iter1
      (fun wg => let wg1 := get_mut_back1 wg
                 back wg1) guard1
partial_fixpoint

/-- [lt_stateful_loops::nested_loops_shared_outer_guard]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 402:4-406:5
    Visibility: public -/
@[rust_loop]
def nested_loops_shared_outer_guard_loop0
  (iter : core.ops.range.Range Std.U32)
  (back : WriteGuard Std.I32 → WriteGuard Std.I32) (inner_n : Std.U32)
  (guard : WriteGuard Std.I32) :
  Result (WriteGuard Std.I32)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32 iter
  match o with
  | none => ok guard
  | some _ =>
    let (guard1, back1) ←
      nested_loops_shared_outer_guard_loop0_loop0
        { start := 0#u32, «end» := inner_n } (fun wg => wg) guard
    nested_loops_shared_outer_guard_loop0 iter1
      (fun wg => let wg1 := back1 wg
                 back wg1) inner_n guard1
partial_fixpoint

/-- [lt_stateful_loops::nested_loops_shared_outer_guard]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 400:0-408:1
    Visibility: public -/
def nested_loops_shared_outer_guard
  (lock : Lock Std.I32) (outer_n : Std.U32) (inner_n : Std.U32) :
  Result Unit
  := do
  let (guard, _) ← Lock.write lock
  let guard1 ←
    nested_loops_shared_outer_guard_loop0
      { start := 0#u32, «end» := outer_n } (fun wg => wg) inner_n guard
  let _ ← WriteGuard.release guard1
  ok ()

/-- [lt_stateful_loops::loop_carried_guard_acquired_before_loop]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 420:4-423:5
    Visibility: public -/
@[rust_loop]
def loop_carried_guard_acquired_before_loop_loop
  (back : WriteGuard Std.I32 → WriteGuard Std.I32) (n : Std.U32)
  (guard : WriteGuard Std.I32) (i : Std.U32) :
  Result (WriteGuard Std.I32)
  := do
  if i < n
  then
    let (i1, get_mut_back, get_mut_back1) ← WriteGuard.get_mut guard
    let i2 ← i1 + 1#i32
    let i3 ← i + 1#u32
    let guard1 := get_mut_back i2
    loop_carried_guard_acquired_before_loop_loop
      (fun wg => let wg1 := get_mut_back1 wg
                 back wg1) n guard1 i3
  else ok guard
partial_fixpoint

/-- [lt_stateful_loops::loop_carried_guard_acquired_before_loop]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 417:0-427:1
    Visibility: public -/
def loop_carried_guard_acquired_before_loop
  (lock : Lock Std.I32) (n : Std.U32) : Result Std.I32 := do
  let (guard, _) ← Lock.write lock
  let guard1 ←
    loop_carried_guard_acquired_before_loop_loop (fun wg => wg) n guard 0#u32
  let result ← WriteGuard.get guard1
  let _ ← WriteGuard.release guard1
  ok result

/-- [lt_stateful_loops::recurse_holding_guard_across_call]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 476:0-484:1
    Visibility: public -/
def recurse_holding_guard_across_call
  (lock : Lock Std.I32) (depth : Std.U32) : Result Unit := do
  if depth = 0#u32
  then ok ()
  else
    let (guard, _) ← Lock.write lock
    let (i, get_mut_back, _) ← WriteGuard.get_mut guard
    let i1 ← i + 1#i32
    let i2 ← depth - 1#u32
    recurse_holding_guard_across_call lock i2
    let guard1 := get_mut_back i1
    let _ ← WriteGuard.release guard1
    ok ()
partial_fixpoint

/-- [lt_stateful_loops::recurse_moving_same_guard_forward]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 497:0-506:1
    Visibility: public -/
def recurse_moving_same_guard_forward
  (guard : WriteGuard Std.I32) (depth : Std.U32) :
  Result ((WriteGuard Std.I32) × (WriteGuard Std.I32 → WriteGuard Std.I32))
  := do
  if depth = 0#u32
  then ok (guard, fun guard1 => guard1)
  else
    let (i, get_mut_back, get_mut_back1) ← WriteGuard.get_mut guard
    let i1 ← i + 1#i32
    let guard1 := get_mut_back i1
    let i2 ← depth - 1#u32
    let (guard2, recurse_moving_same_guard_forward_back) ←
      recurse_moving_same_guard_forward guard1 i2
    let back :=
      fun wg =>
        let guard3 := recurse_moving_same_guard_forward_back wg
        get_mut_back1 guard3
    ok (guard2, back)
partial_fixpoint

/-- [lt_stateful_loops::recurse_moving_same_guard]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 513:0-519:1
    Visibility: public -/
def recurse_moving_same_guard
  (lock : Lock Std.I32) (depth : Std.U32) : Result Std.I32 := do
  let (guard, _) ← Lock.write lock
  let (guard1, _) ← recurse_moving_same_guard_forward guard depth
  let v ← WriteGuard.get guard1
  let _ ← WriteGuard.release guard1
  ok v

/-- [lt_stateful_loops::no_regression_plain_sum_loop]: loop 0:
    Source: 'tests/src/lt-stateful-loops.rs', lines 556:4-558:5
    Visibility: public -/
@[rust_loop]
def no_regression_plain_sum_loop_loop
  (iter : core.ops.range.Range Std.Usize) (acc : Std.I32) (xs : Slice Std.I32)
  :
  Result Std.I32
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok acc
  | some i =>
    let i1 ← Slice.index_usize xs i
    let acc1 ← acc + i1
    no_regression_plain_sum_loop_loop iter1 acc1 xs
partial_fixpoint

/-- [lt_stateful_loops::no_regression_plain_sum_loop]:
    Source: 'tests/src/lt-stateful-loops.rs', lines 555:0-559:1
    Visibility: public -/
def no_regression_plain_sum_loop
  (acc : Std.I32) (xs : Slice Std.I32) : Result Std.I32 := do
  let i := Slice.len xs
  no_regression_plain_sum_loop_loop { start := 0#usize, «end» := i } acc xs

end lt_stateful_loops
