-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_purity_off]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace lt_stateful_purity_off

/-- [lt_stateful_purity_off::incr]:
    Source: 'tests/src/lt-stateful-purity-off.rs', lines 30:0-32:1
    Visibility: public -/
def incr (x : Std.U32) : Result Std.U32 := do
  x + 1#u32

/-- [lt_stateful_purity_off::choose_mut]:
    Source: 'tests/src/lt-stateful-purity-off.rs', lines 36:0-42:1
    Visibility: public -/
def choose_mut
  (b : Bool) (x : Std.U32) (y : Std.U32) :
  Result (Std.U32 × (Std.U32 → (Std.U32 × Std.U32)))
  := do
  if b
  then let back := fun x1 => (x1, y)
       ok (x, back)
  else let back := fun y1 => (x, y1)
       ok (y, back)

/-- [lt_stateful_purity_off::use_choose]:
    Source: 'tests/src/lt-stateful-purity-off.rs', lines 45:0-53:1
    Visibility: public -/
def use_choose (b : Bool) : Result Std.U32 := do
  let (r, choose_mut_back) ← choose_mut b 1#u32 2#u32
  let r1 ← r + 10#u32
  let (x, y) := choose_mut_back r1
  x + y

/-- [lt_stateful_purity_off::loop_incr]: loop body 0:
    Source: 'tests/src/lt-stateful-purity-off.rs', lines 58:4-61:5
    Visibility: public -/
@[rust_loop_body]
def loop_incr_loop.body
  (count : Std.U32) (x : Std.U32) (index : Std.U32) :
  Result (ControlFlow (Std.U32 × Std.U32) Std.U32)
  := do
  if index < count
  then let x1 ← incr x
       let index1 ← index + 1#u32
       ok (cont (x1, index1))
  else ok (done x)

/-- [lt_stateful_purity_off::loop_incr]: loop 0:
    Source: 'tests/src/lt-stateful-purity-off.rs', lines 58:4-61:5
    Visibility: public -/
@[rust_loop]
def loop_incr_loop
  (x : Std.U32) (count : Std.U32) (index : Std.U32) : Result Std.U32 := do
  loop
    (fun (x1, index1) => loop_incr_loop.body count x1 index1)
    (x, index)

/-- [lt_stateful_purity_off::loop_incr]:
    Source: 'tests/src/lt-stateful-purity-off.rs', lines 56:0-62:1
    Visibility: public -/
@[reducible]
def loop_incr (x : Std.U32) (count : Std.U32) : Result Std.U32 := do
  loop_incr_loop x count 0#u32

/-- [lt_stateful_purity_off::duplicate_calls]:
    Source: 'tests/src/lt-stateful-purity-off.rs', lines 66:0-70:1
    Visibility: public -/
def duplicate_calls (x : Std.U32) : Result Std.U32 := do
  let first ← x + 1#u32
  first + first

/-- [lt_stateful_purity_off::unit_result]:
    Source: 'tests/src/lt-stateful-purity-off.rs', lines 74:0-76:1
    Visibility: public -/
def unit_result (x : Std.U32) : Result Std.U32 := do
  ok 0#u32

/-- [lt_stateful_purity_off::swap_pair]:
    Source: 'tests/src/lt-stateful-purity-off.rs', lines 81:0-85:1
    Visibility: public -/
def swap_pair (p : (Std.U32 × Std.U32)) : Result (Std.U32 × Std.U32) := do
  let (tmp, i) := p
  ok (i, tmp)

/-- [lt_stateful_purity_off::field_mut]:
    Source: 'tests/src/lt-stateful-purity-off.rs', lines 88:0-90:1
    Visibility: public -/
def field_mut
  (p : (Std.U32 × Std.U32)) :
  Result (Std.U32 × (Std.U32 → (Std.U32 × Std.U32)))
  := do
  let (i, i1) := p
  let back := fun i2 => (i2, i1)
  ok (i, back)

/-- [lt_stateful_purity_off::bump_field]:
    Source: 'tests/src/lt-stateful-purity-off.rs', lines 93:0-99:1
    Visibility: public -/
def bump_field
  (p : (Std.U32 × Std.U32)) : Result (Std.U32 × (Std.U32 × Std.U32)) := do
  let (f, field_mut_back) ← field_mut p
  let f1 ← f + 3#u32
  let (i, _) := field_mut_back f1
  ok (i, field_mut_back f1)

end lt_stateful_purity_off
