-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_arc]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_arc

/-- [core::mem::drop]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 1000:0-1002:24
    Name pattern: [core::mem::drop]
    Visibility: public -/
@[rust_fun "core::mem::drop"]
axiom core.mem.drop {T : Type} : T → Result Unit

/-- [alloc::vec::{alloc::vec::Vec<T>}::swap_remove]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2257:4-2257:52
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::swap_remove]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::swap_remove"]
axiom alloc.vec.Vec.swap_remove
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Std.Usize → Result (T × (alloc.vec.Vec T))

/-- [alloc::vec::{alloc::vec::Vec<T>}::remove]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2401:4-2401:47
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::remove]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::remove"]
axiom alloc.vec.Vec.remove
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Std.Usize → Result (T × (alloc.vec.Vec T))

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3085:4-3085:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
axiom alloc.vec.Vec.is_empty
  {T : Type} (A : Type) : alloc.vec.Vec T → Result Bool

/-- [lt_stateful_arc::Arc]
    Source: 'tests/src/lt-stateful-arc.rs', lines 83:0-85:1
    Visibility: public -/
axiom Arc (T : Type) : Type

/-- [lt_stateful_arc::{impl core::ops::drop::Drop for lt_stateful_arc::Arc<T>}::drop]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 150:4-152:5
    Visibility: public -/
axiom Arc.Insts.CoreOpsDropDrop.drop {T : Type} : Arc T → Result (Arc T)

/-- [lt_stateful_arc::Weak]
    Source: 'tests/src/lt-stateful-arc.rs', lines 92:0-94:1
    Visibility: public -/
axiom Weak (T : Type) : Type

/-- [lt_stateful_arc::{impl core::ops::drop::Drop for lt_stateful_arc::Weak<T>}::drop]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 185:4-187:5
    Visibility: public -/
axiom Weak.Insts.CoreOpsDropDrop.drop {T : Type} : Weak T → Result (Weak T)

/-- [lt_stateful_arc::{lt_stateful_arc::Arc<T>}::new]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 100:4-102:5
    Visibility: public -/
axiom Arc.new {T : Type} : T → Result (Arc T)

/-- [lt_stateful_arc::{lt_stateful_arc::Arc<T>}::get]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 108:4-110:5
    Visibility: public -/
axiom Arc.get {T : Type} : Arc T → Result T

/-- [lt_stateful_arc::{lt_stateful_arc::Arc<T>}::clone_arc]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 116:4-118:5
    Visibility: public -/
axiom Arc.clone_arc {T : Type} : Arc T → Result (Arc T)

/-- [lt_stateful_arc::{lt_stateful_arc::Arc<T>}::strong_count]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 124:4-126:5
    Visibility: public -/
axiom Arc.strong_count {T : Type} : Arc T → Result Std.Usize

/-- [lt_stateful_arc::{lt_stateful_arc::Arc<T>}::weak_count]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 131:4-133:5
    Visibility: public -/
axiom Arc.weak_count {T : Type} : Arc T → Result Std.Usize

/-- [lt_stateful_arc::{lt_stateful_arc::Arc<T>}::downgrade]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 139:4-141:5
    Visibility: public -/
axiom Arc.downgrade {T : Type} : Arc T → Result (Weak T)

/-- Trait implementation: [lt_stateful_arc::{impl core::ops::drop::Drop for lt_stateful_arc::Arc<T>}]
    Source: 'tests/src/lt-stateful-arc.rs', lines 148:0-153:1 -/
@[reducible]
def Arc.Insts.CoreOpsDropDrop (T : Type) : core.ops.drop.Drop (Arc T) := {
  drop := Arc.Insts.CoreOpsDropDrop.drop
}

/-- [lt_stateful_arc::{lt_stateful_arc::Weak<T>}::new]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 159:4-161:5
    Visibility: public -/
axiom Weak.new (T : Type) : Result (Weak T)

/-- [lt_stateful_arc::{lt_stateful_arc::Weak<T>}::clone_weak]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 166:4-168:5
    Visibility: public -/
axiom Weak.clone_weak {T : Type} : Weak T → Result (Weak T)

/-- [lt_stateful_arc::{lt_stateful_arc::Weak<T>}::upgrade]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 176:4-178:5
    Visibility: public -/
axiom Weak.upgrade {T : Type} : Weak T → Result (Option (Arc T))

/-- Trait implementation: [lt_stateful_arc::{impl core::ops::drop::Drop for lt_stateful_arc::Weak<T>}]
    Source: 'tests/src/lt-stateful-arc.rs', lines 183:0-188:1 -/
@[reducible]
def Weak.Insts.CoreOpsDropDrop (T : Type) : core.ops.drop.Drop (Weak T) := {
  drop := Weak.Insts.CoreOpsDropDrop.drop
}

/-- [lt_stateful_arc::Lock]
    Source: 'tests/src/lt-stateful-arc.rs', lines 200:0-202:1
    Visibility: public -/
axiom Lock (T : Type) : Type

/-- [lt_stateful_arc::ReadGuard]
    Source: 'tests/src/lt-stateful-arc.rs', lines 205:0-207:1
    Visibility: public -/
axiom ReadGuard (T : Type) : Type

/-- [lt_stateful_arc::WriteGuard]
    Source: 'tests/src/lt-stateful-arc.rs', lines 210:0-212:1
    Visibility: public -/
axiom WriteGuard (T : Type) : Type

/-- [lt_stateful_arc::{lt_stateful_arc::Lock<T>}::new]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 216:4-218:5
    Visibility: public -/
axiom Lock.new {T : Type} : T → Result (Lock T)

/-- [lt_stateful_arc::{lt_stateful_arc::Lock<T>}::read]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 221:4-223:5
    Visibility: public -/
axiom Lock.read {T : Type} : Lock T → Result (ReadGuard T)

/-- [lt_stateful_arc::{lt_stateful_arc::Lock<T>}::write]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 226:4-228:5
    Visibility: public -/
axiom Lock.write
  {T : Type} : Lock T → Result ((WriteGuard T) × (WriteGuard T → Unit))

/-- [lt_stateful_arc::{lt_stateful_arc::ReadGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 233:4-235:5
    Visibility: public -/
axiom ReadGuard.get {T : Type} : ReadGuard T → Result T

/-- [lt_stateful_arc::{lt_stateful_arc::ReadGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 238:4-238:27
    Visibility: public -/
axiom ReadGuard.release {T : Type} : ReadGuard T → Result Unit

/-- [lt_stateful_arc::{lt_stateful_arc::WriteGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 243:4-245:5
    Visibility: public -/
axiom WriteGuard.get {T : Type} : WriteGuard T → Result T

/-- [lt_stateful_arc::{lt_stateful_arc::WriteGuard<'a, T>}::get_mut]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 248:4-250:5
    Visibility: public -/
axiom WriteGuard.get_mut
  {T : Type} :
  WriteGuard T → Result (T × (T → WriteGuard T) × (WriteGuard T →
    WriteGuard T))

/-- [lt_stateful_arc::{lt_stateful_arc::WriteGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 253:4-253:27
    Visibility: public -/
axiom WriteGuard.release {T : Type} : WriteGuard T → Result (WriteGuard T)

/-- [lt_stateful_arc::Node]
    Source: 'tests/src/lt-stateful-arc.rs', lines 266:0-269:1
    Visibility: public -/
axiom Node : Type

/-- [lt_stateful_arc::{lt_stateful_arc::Node}::new]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 273:4-275:5
    Visibility: public -/
axiom Node.new : Std.I32 → Option (Arc Node) → Result Node

/-- [lt_stateful_arc::{lt_stateful_arc::Node}::value]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 278:4-280:5
    Visibility: public -/
axiom Node.value : Node → Result Std.I32

/-- [lt_stateful_arc::Parent]
    Source: 'tests/src/lt-stateful-arc.rs', lines 284:0-286:1
    Visibility: public -/
structure Parent where
  «name» : Std.I32

/-- [lt_stateful_arc::Child]
    Source: 'tests/src/lt-stateful-arc.rs', lines 290:0-292:1
    Visibility: public -/
structure Child where
  parent : Weak Parent

/-- [lt_stateful_arc::arc_new_basic]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 302:0-305:1
    Visibility: public -/
def arc_new_basic (value : Std.I32) : Result Std.I32 := do
  let a ← Arc.new value
  Arc.get a

/-- [lt_stateful_arc::arc_clone_once]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 311:0-315:1
    Visibility: public -/
def arc_clone_once (value : Std.I32) : Result (Std.I32 × Std.I32) := do
  let a ← Arc.new value
  let b ← Arc.clone_arc a
  let i ← Arc.get a
  let i1 ← Arc.get b
  ok (i, i1)

/-- [lt_stateful_arc::arc_clone_twice]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 322:0-327:1
    Visibility: public -/
def arc_clone_twice
  (value : Std.I32) : Result (Std.I32 × Std.I32 × Std.I32) := do
  let a ← Arc.new value
  let b ← Arc.clone_arc a
  let c ← Arc.clone_arc b
  let i ← Arc.get a
  let i1 ← Arc.get b
  let i2 ← Arc.get c
  ok (i, i1, i2)

/-- [lt_stateful_arc::arc_drop_implicit_end_of_scope]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 337:0-343:1
    Visibility: public -/
def arc_drop_implicit_end_of_scope (value : Std.I32) : Result Unit := do
  let a ← Arc.new value
  let _ ← Arc.get a
  ok ()

/-- [lt_stateful_arc::arc_drop_explicit_via_std_drop]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 348:0-351:1
    Visibility: public -/
def arc_drop_explicit_via_std_drop (value : Std.I32) : Result Unit := do
  let a ← Arc.new value
  core.mem.drop a

/-- [lt_stateful_arc::arc_last_strong_drop_order]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 359:0-364:1
    Visibility: public -/
def arc_last_strong_drop_order (value : Std.I32) : Result Unit := do
  let a ← Arc.new value
  let b ← Arc.clone_arc a
  core.mem.drop a
  core.mem.drop b

/-- [lt_stateful_arc::arc_overwrite_binding]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 371:0-376:1
    Visibility: public -/
def arc_overwrite_binding : Result Unit := do
  let a ← Arc.new 1#i32
  let _ ← Arc.get a
  let a1 ← Arc.new 2#i32
  let _ ← Arc.get a1
  ok ()

/-- [lt_stateful_arc::arc_in_option_some_and_take]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 387:0-395:1
    Visibility: public -/
def arc_in_option_some_and_take (value : Std.I32) : Result Bool := do
  let a ← Arc.new value
  let (taken, _) := core.option.Option.take (some a)
  let was_some := core.option.Option.is_some taken
  match taken with
  | none => ok was_some
  | some a1 => core.mem.drop a1
               ok was_some

/-- [lt_stateful_arc::arc_in_option_implicit_drop]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 404:0-409:1
    Visibility: public -/
def arc_in_option_implicit_drop (value : Std.I32) : Result Bool := do
  let a ← Arc.new value
  ok (core.option.Option.is_some (some a))

/-- [lt_stateful_arc::arc_in_vec_pushed_and_dropped]: loop body 0:
    Source: 'tests/src/lt-stateful-arc.rs', lines 417:4-419:5
    Visibility: public -/
@[rust_loop_body]
def arc_in_vec_pushed_and_dropped_loop.body
  (iter : alloc.vec.into_iter.IntoIter Std.I32)
  (owners : alloc.vec.Vec (Arc Std.I32)) :
  Result (ControlFlow ((alloc.vec.into_iter.IntoIter Std.I32) × (alloc.vec.Vec
    (Arc Std.I32))) Unit)
  := do
  let (o, iter1) ← alloc.vec.into_iter.IteratorIntoIter.next iter
  match o with
  | none => ok (done ())
  | some v =>
    let a ← Arc.new v
    let owners1 ← alloc.vec.Vec.push owners a
    ok (cont (iter1, owners1))

/-- [lt_stateful_arc::arc_in_vec_pushed_and_dropped]: loop 0:
    Source: 'tests/src/lt-stateful-arc.rs', lines 417:4-419:5
    Visibility: public -/
@[rust_loop]
def arc_in_vec_pushed_and_dropped_loop
  (iter : alloc.vec.into_iter.IntoIter Std.I32)
  (owners : alloc.vec.Vec (Arc Std.I32)) :
  Result Unit
  := do
  loop
    (fun (iter1, owners1) => arc_in_vec_pushed_and_dropped_loop.body iter1
      owners1)
    (iter, owners)

/-- [lt_stateful_arc::arc_in_vec_pushed_and_dropped]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 415:0-421:1
    Visibility: public -/
def arc_in_vec_pushed_and_dropped
  (values : alloc.vec.Vec Std.I32) : Result Unit := do
  let iter ← alloc.vec.IntoIteratorVec.into_iter values
  arc_in_vec_pushed_and_dropped_loop iter (alloc.vec.Vec.new (Arc Std.I32))

/-- [lt_stateful_arc::arc_vec_remove_preserves_order]: loop body 0:
    Source: 'tests/src/lt-stateful-arc.rs', lines 432:4-434:5
    Visibility: public -/
@[rust_loop_body]
def arc_vec_remove_preserves_order_loop.body
  (iter : alloc.vec.into_iter.IntoIter Std.I32)
  (owners : alloc.vec.Vec (Arc Std.I32)) :
  Result (ControlFlow ((alloc.vec.into_iter.IntoIter Std.I32) × (alloc.vec.Vec
    (Arc Std.I32))) (alloc.vec.Vec (Arc Std.I32)))
  := do
  let (o, iter1) ← alloc.vec.into_iter.IteratorIntoIter.next iter
  match o with
  | none => ok (done owners)
  | some v =>
    let a ← Arc.new v
    let owners1 ← alloc.vec.Vec.push owners a
    ok (cont (iter1, owners1))

/-- [lt_stateful_arc::arc_vec_remove_preserves_order]: loop 0:
    Source: 'tests/src/lt-stateful-arc.rs', lines 432:4-434:5
    Visibility: public -/
@[rust_loop]
def arc_vec_remove_preserves_order_loop
  (iter : alloc.vec.into_iter.IntoIter Std.I32)
  (owners : alloc.vec.Vec (Arc Std.I32)) :
  Result (alloc.vec.Vec (Arc Std.I32))
  := do
  loop
    (fun (iter1, owners1) => arc_vec_remove_preserves_order_loop.body iter1
      owners1)
    (iter, owners)

/-- [lt_stateful_arc::arc_vec_remove_preserves_order]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 430:0-446:1
    Visibility: public -/
def arc_vec_remove_preserves_order
  (values : alloc.vec.Vec Std.I32) : Result (Std.I32 × Std.I32) := do
  let iter ← alloc.vec.IntoIteratorVec.into_iter values
  let owners ←
    arc_vec_remove_preserves_order_loop iter (alloc.vec.Vec.new (Arc Std.I32))
  let (removed, owners1) ← alloc.vec.Vec.remove Global owners 0#usize
  let removed_value ← Arc.get removed
  core.mem.drop removed
  let b ← alloc.vec.Vec.is_empty Global owners1
  if b
  then ok (removed_value, (-1)#i32)
  else
    let a ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Arc Std.I32))
        owners1 0#usize
    let first_remaining ← Arc.get a
    ok (removed_value, first_remaining)

/-- [lt_stateful_arc::arc_vec_swap_remove_reorders]: loop body 0:
    Source: 'tests/src/lt-stateful-arc.rs', lines 458:4-460:5
    Visibility: public -/
@[rust_loop_body]
def arc_vec_swap_remove_reorders_loop.body
  (iter : alloc.vec.into_iter.IntoIter Std.I32)
  (owners : alloc.vec.Vec (Arc Std.I32)) :
  Result (ControlFlow ((alloc.vec.into_iter.IntoIter Std.I32) × (alloc.vec.Vec
    (Arc Std.I32))) (alloc.vec.Vec (Arc Std.I32)))
  := do
  let (o, iter1) ← alloc.vec.into_iter.IteratorIntoIter.next iter
  match o with
  | none => ok (done owners)
  | some v =>
    let a ← Arc.new v
    let owners1 ← alloc.vec.Vec.push owners a
    ok (cont (iter1, owners1))

/-- [lt_stateful_arc::arc_vec_swap_remove_reorders]: loop 0:
    Source: 'tests/src/lt-stateful-arc.rs', lines 458:4-460:5
    Visibility: public -/
@[rust_loop]
def arc_vec_swap_remove_reorders_loop
  (iter : alloc.vec.into_iter.IntoIter Std.I32)
  (owners : alloc.vec.Vec (Arc Std.I32)) :
  Result (alloc.vec.Vec (Arc Std.I32))
  := do
  loop
    (fun (iter1, owners1) => arc_vec_swap_remove_reorders_loop.body iter1
      owners1)
    (iter, owners)

/-- [lt_stateful_arc::arc_vec_swap_remove_reorders]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 456:0-471:1
    Visibility: public -/
def arc_vec_swap_remove_reorders
  (values : alloc.vec.Vec Std.I32) : Result (Std.I32 × Std.I32) := do
  let iter ← alloc.vec.IntoIteratorVec.into_iter values
  let owners ←
    arc_vec_swap_remove_reorders_loop iter (alloc.vec.Vec.new (Arc Std.I32))
  let (removed, owners1) ← alloc.vec.Vec.swap_remove Global owners 0#usize
  let removed_value ← Arc.get removed
  core.mem.drop removed
  let b ← alloc.vec.Vec.is_empty Global owners1
  if b
  then ok (removed_value, (-1)#i32)
  else
    let a ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Arc Std.I32))
        owners1 0#usize
    let first_remaining ← Arc.get a
    ok (removed_value, first_remaining)

/-- [lt_stateful_arc::arc_in_node_struct_chain]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 478:0-482:1
    Visibility: public -/
def arc_in_node_struct_chain : Result Std.I32 := do
  let tail ← Node.new 2#i32 none
  let a ← Arc.new tail
  let head ← Node.new 1#i32 (some a)
  Node.value head

/-- [lt_stateful_arc::arc_downgrade_to_weak]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 493:0-497:1
    Visibility: public -/
def arc_downgrade_to_weak (value : Std.I32) : Result Std.I32 := do
  let a ← Arc.new value
  let _ ← Arc.downgrade a
  Arc.get a

/-- [lt_stateful_arc::weak_clone_independent]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 502:0-509:1
    Visibility: public -/
def weak_clone_independent (value : Std.I32) : Result Unit := do
  let a ← Arc.new value
  let w1 ← Arc.downgrade a
  let w2 ← Weak.clone_weak w1
  core.mem.drop w1
  core.mem.drop w2
  core.mem.drop a

/-- [lt_stateful_arc::weak_drop_no_effect_on_strong]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 515:0-520:1
    Visibility: public -/
def weak_drop_no_effect_on_strong (value : Std.I32) : Result Std.I32 := do
  let a ← Arc.new value
  let w ← Arc.downgrade a
  core.mem.drop w
  Arc.get a

/-- [lt_stateful_arc::dangling_weak_never_upgrades]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 524:0-527:1
    Visibility: public -/
def dangling_weak_never_upgrades : Result Bool := do
  let w ← Weak.new Std.I32
  let o ← Weak.upgrade w
  ok (core.option.Option.is_some o)

/-- [lt_stateful_arc::weak_upgrade_while_strong_alive]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 533:0-538:1
    Visibility: public -/
def weak_upgrade_while_strong_alive (value : Std.I32) : Result Bool := do
  let a ← Arc.new value
  let w ← Arc.downgrade a
  let upgraded ← Weak.upgrade w
  ok (core.option.Option.is_some upgraded)

/-- [lt_stateful_arc::weak_upgrade_after_strong_dropped]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 545:0-551:1
    Visibility: public -/
def weak_upgrade_after_strong_dropped (value : Std.I32) : Result Bool := do
  let a ← Arc.new value
  let w ← Arc.downgrade a
  core.mem.drop a
  let upgraded ← Weak.upgrade w
  ok (core.option.Option.is_some upgraded)

/-- [lt_stateful_arc::weak_upgrade_before_and_after_last_owner_dropped]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 562:0-572:1
    Visibility: public -/
def weak_upgrade_before_and_after_last_owner_dropped
  (value : Std.I32) : Result (Bool × Bool) := do
  let a ← Arc.new value
  let b ← Arc.clone_arc a
  let w ← Arc.downgrade a
  let w_after ← Weak.clone_weak w
  core.mem.drop a
  let o ← Weak.upgrade w
  let before_last := core.option.Option.is_some o
  core.mem.drop b
  let o1 ← Weak.upgrade w_after
  let after_last := core.option.Option.is_some o1
  ok (before_last, after_last)

/-- [lt_stateful_arc::weak_upgrade_after_owner_scope_exit]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 579:0-585:1
    Visibility: public -/
def weak_upgrade_after_owner_scope_exit (value : Std.I32) : Result Bool := do
  let a ← Arc.new value
  let w ← Arc.downgrade a
  let o ← Weak.upgrade w
  ok (core.option.Option.is_some o)

/-- [lt_stateful_arc::arc_strong_count_across_clone_and_drop]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 597:0-604:1
    Visibility: public -/
def arc_strong_count_across_clone_and_drop
  (value : Std.I32) : Result (Std.Usize × Std.Usize) := do
  let a ← Arc.new value
  let before ← Arc.strong_count a
  let b ← Arc.clone_arc a
  let after ← Arc.strong_count b
  core.mem.drop b
  ok (before, after)

/-- [lt_stateful_arc::weak_count_after_downgrade]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 610:0-614:1
    Visibility: public -/
def weak_count_after_downgrade (value : Std.I32) : Result Std.Usize := do
  let a ← Arc.new value
  let _ ← Arc.downgrade a
  Arc.weak_count a

/-- [lt_stateful_arc::clone_in_true_branch_only]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 626:0-633:1
    Visibility: public -/
def clone_in_true_branch_only
  (value : Std.I32) (take_extra : Bool) : Result Unit := do
  let a ← Arc.new value
  let _ ←
    if take_extra
    then do
         let b ← Arc.clone_arc a
         core.mem.drop b
         ok true
    else ok false
  core.mem.drop a

/-- [lt_stateful_arc::clone_in_one_match_arm_only]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 641:0-654:1
    Visibility: public -/
def clone_in_one_match_arm_only
  (value : Std.I32) (choice : Std.U8) : Result Unit := do
  let a ← Arc.new value
  let _ ←
    match choice with
    | 0#uscalar => do
                   let b ← Arc.clone_arc a
                   core.mem.drop b
                   ok 0#u8
    | 1#uscalar => do
                   let _ ← Arc.get a
                   ok 1#u8
    | _ => ok choice
  core.mem.drop a

/-- [lt_stateful_arc::drop_in_one_branch_only]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 661:0-669:1
    Visibility: public -/
def drop_in_one_branch_only
  (value : Std.I32) (drop_early : Bool) : Result Unit := do
  let a ← Arc.new value
  if drop_early
  then core.mem.drop a
  else let _ ← Arc.get a
       ok ()

/-- [lt_stateful_arc::arc_rwlock_read_then_release]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 681:0-687:1
    Visibility: public -/
def arc_rwlock_read_then_release (value : Std.I32) : Result Std.I32 := do
  let l ← Lock.new value
  let shared ← Arc.new l
  let l1 ← Arc.get shared
  let guard ← Lock.read l1
  let v ← ReadGuard.get guard
  ReadGuard.release guard
  ok v

/-- [lt_stateful_arc::arc_rwlock_write_then_release]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 694:0-699:1
    Visibility: public -/
def arc_rwlock_write_then_release (value : Std.I32) : Result Unit := do
  let l ← Lock.new value
  let shared ← Arc.new l
  let l1 ← Arc.get shared
  let (guard, _) ← Lock.write l1
  let (_, get_mut_back, _) ← WriteGuard.get_mut guard
  let guard1 := get_mut_back 42#i32
  let _ ← WriteGuard.release guard1
  ok ()

/-- [lt_stateful_arc::arc_rwlock_read_then_write_ordering]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 708:0-718:1
    Visibility: public -/
def arc_rwlock_read_then_write_ordering
  (value : Std.I32) : Result Std.I32 := do
  let l ← Lock.new value
  let shared ← Arc.new l
  let lock ← Arc.get shared
  let read_guard ← Lock.read lock
  let seen ← ReadGuard.get read_guard
  ReadGuard.release read_guard
  let (write_guard, _) ← Lock.write lock
  let (_, get_mut_back, _) ← WriteGuard.get_mut write_guard
  let write_guard1 := get_mut_back 42#i32
  let _ ← WriteGuard.release write_guard1
  ok seen

/-- [lt_stateful_arc::consume_arc]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 726:0-730:1 -/
def consume_arc (a : Arc Std.I32) : Result Std.I32 := do
  let v ← Arc.get a
  core.mem.drop a
  ok v

/-- [lt_stateful_arc::arc_moved_into_function]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 736:0-739:1
    Visibility: public -/
def arc_moved_into_function (value : Std.I32) : Result Std.I32 := do
  let a ← Arc.new value
  consume_arc a

/-- [lt_stateful_arc::produce_arc]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 742:0-744:1 -/
def produce_arc (value : Std.I32) : Result (Arc Std.I32) := do
  Arc.new value

/-- [lt_stateful_arc::arc_returned_from_function]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 751:0-754:1
    Visibility: public -/
def arc_returned_from_function (value : Std.I32) : Result Std.I32 := do
  let a ← produce_arc value
  Arc.get a

/-- [lt_stateful_arc::weak_stored_in_struct_back_pointer]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 761:0-769:1
    Visibility: public -/
def weak_stored_in_struct_back_pointer
  (parent_name : Std.I32) : Result Bool := do
  let parent ← Arc.new ({ «name» := parent_name } : Parent)
  let w ← Arc.downgrade parent
  let o ← Weak.upgrade w
  let still_alive := core.option.Option.is_some o
  core.mem.drop ({ parent := w } : Child)
  ok still_alive

/-- [lt_stateful_arc::Holder]
    Source: 'tests/src/lt-stateful-arc.rs', lines 777:0-779:1
    Visibility: public -/
structure Holder where
  owner : Arc Std.I32

/-- [lt_stateful_arc::observe_holder]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 782:0-784:1 -/
axiom observe_holder : Holder → Result Std.I32

/-- [lt_stateful_arc::struct_field_vs_local_drop_order]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 796:0-804:1
    Visibility: public -/
def struct_field_vs_local_drop_order
  (value_struct : Std.I32) (value_local : Std.I32) : Result Std.I32 := do
  let a ← Arc.new value_struct
  let local1 ← Arc.new value_local
  let i ← observe_holder { owner := a }
  let i1 ← Arc.get local1
  i + i1

/-- [lt_stateful_arc::CycleNode]
    Source: 'tests/src/lt-stateful-arc.rs', lines 817:0-820:1
    Visibility: public -/
axiom CycleNode : Type

/-- [lt_stateful_arc::{lt_stateful_arc::CycleNode}::new]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 824:4-826:5
    Visibility: public -/
axiom CycleNode.new : Std.I32 → Result CycleNode

/-- [lt_stateful_arc::{lt_stateful_arc::CycleNode}::set_next]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 829:4-831:5
    Visibility: public -/
axiom CycleNode.set_next
  : CycleNode → Arc (Lock CycleNode) → Result CycleNode

/-- [lt_stateful_arc::arc_two_node_strong_cycle]:
    Source: 'tests/src/lt-stateful-arc.rs', lines 852:0-868:1
    Visibility: public -/
def arc_two_node_strong_cycle
  (value_a : Std.I32) (value_b : Std.I32) : Result Unit := do
  let cn ← CycleNode.new value_a
  let l ← Lock.new cn
  let node_a ← Arc.new l
  let cn1 ← CycleNode.new value_b
  let l1 ← Lock.new cn1
  let node_b ← Arc.new l1
  let l2 ← Arc.get node_a
  let (guard, _) ← Lock.write l2
  let (cn2, get_mut_back, _) ← WriteGuard.get_mut guard
  let a ← Arc.clone_arc node_b
  let cn3 ← CycleNode.set_next cn2 a
  let guard1 := get_mut_back cn3
  let _ ← WriteGuard.release guard1
  let l3 ← Arc.get node_b
  let (guard2, _) ← Lock.write l3
  let (cn4, get_mut_back1, _) ← WriteGuard.get_mut guard2
  let a1 ← Arc.clone_arc node_a
  let cn5 ← CycleNode.set_next cn4 a1
  let guard3 := get_mut_back1 cn5
  let _ ← WriteGuard.release guard3
  ok ()

end lt_stateful_arc
