-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_returns]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_returns

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2793:4-2793:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [lt_stateful_returns::Lock]
    Source: 'tests/src/lt-stateful-returns.rs', lines 103:0-105:1
    Visibility: public -/
axiom Lock : Type

/-- [lt_stateful_returns::Guard]
    Source: 'tests/src/lt-stateful-returns.rs', lines 112:0-114:1
    Visibility: public -/
axiom Guard : Type

/-- [lt_stateful_returns::acquire]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 120:0-122:1
    Visibility: public -/
axiom acquire : Lock → Result Guard

/-- [lt_stateful_returns::release]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 127:0-129:1
    Visibility: public -/
axiom release : Guard → Result Unit

/-- [lt_stateful_returns::consume_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 135:0-137:1
    Visibility: public -/
axiom consume_guard : Guard → Result Std.U32

/-- [lt_stateful_returns::peek]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 141:0-143:1
    Visibility: public -/
axiom peek : Guard → Result Std.U32

/-- [lt_stateful_returns::MutGuard]
    Source: 'tests/src/lt-stateful-returns.rs', lines 148:0-150:1
    Visibility: public -/
axiom MutGuard : Type

/-- [lt_stateful_returns::acquire_mut]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 154:0-156:1
    Visibility: public -/
axiom acquire_mut : Lock → Result (MutGuard × (MutGuard → Lock))

/-- [lt_stateful_returns::release_mut]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 160:0-162:1
    Visibility: public -/
axiom release_mut : MutGuard → Result MutGuard

/-- [lt_stateful_returns::return_guard_no_release]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 172:0-174:1
    Visibility: public -/
def return_guard_no_release (lock : Lock) : Result Guard := do
  acquire lock

/-- [lt_stateful_returns::return_mut_guard_no_release]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 179:0-181:1
    Visibility: public -/
def return_mut_guard_no_release
  (lock : Lock) : Result (MutGuard × (MutGuard → Lock)) := do
  acquire_mut lock

/-- [lt_stateful_returns::return_mut_guard_in_option]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 186:0-192:1
    Visibility: public -/
def return_mut_guard_in_option
  (lock : Lock) (enabled : Bool) :
  Result ((Option MutGuard) × (Option MutGuard → Lock))
  := do
  if enabled
  then
    let (mg, acquire_mut_back) ← acquire_mut lock
    let back :=
      fun o =>
        let mg1 := match o with
                   | some mg2 => mg2
                   | _ => mg
        acquire_mut_back mg1
    ok (some mg, back)
  else let back := fun o => lock
       ok (none, back)

/-- [lt_stateful_returns::caller_releases_mut_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 197:0-200:1
    Visibility: public -/
def caller_releases_mut_guard (lock : Lock) : Result Lock := do
  let (guard, return_mut_guard_no_release_back) ←
    return_mut_guard_no_release lock
  let guard1 ← release_mut guard
  ok (return_mut_guard_no_release_back guard1)

/-- [lt_stateful_returns::move_guard_into_callee]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 207:0-210:1
    Visibility: public -/
def move_guard_into_callee (lock : Lock) : Result Std.U32 := do
  let g ← acquire lock
  consume_guard g

/-- [lt_stateful_returns::consume_and_report]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 217:0-219:1 -/
def consume_and_report (g : Guard) : Result Std.U32 := do
  consume_guard g

/-- [lt_stateful_returns::call_consume_and_report]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 222:0-225:1
    Visibility: public -/
def call_consume_and_report (lock : Lock) : Result Std.U32 := do
  let g ← acquire lock
  consume_and_report g

/-- [lt_stateful_returns::early_return_with_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 232:0-237:1
    Visibility: public -/
def early_return_with_guard
  (lock : Lock) (take_early : Bool) : Result Guard := do
  if take_early
  then acquire lock
  else acquire lock

/-- [lt_stateful_returns::branch_match_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 244:0-253:1
    Visibility: public -/
def branch_match_guard (lock : Lock) (mode : Std.U8) : Result Guard := do
  match mode with
  | 0#uscalar => acquire lock
  | 1#uscalar => acquire lock
  | _ => acquire lock

/-- [lt_stateful_returns::option_try_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 260:0-263:1
    Visibility: public -/
def option_try_guard (maybe_lock : Option Lock) : Result (Option Guard) := do
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch maybe_lock
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let g ← acquire val
    ok (some g)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      Guard residual

/-- [lt_stateful_returns::result_try_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 270:0-273:1
    Visibility: public -/
def result_try_guard
  (maybe_lock : core.result.Result Lock Std.U32) :
  Result (core.result.Result Guard Std.U32)
  := do
  let cf ← core.result.Result.Insts.CoreOpsTry.branch maybe_lock
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let g ← acquire val
    ok (core.result.Result.Ok g)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Guard (core.convert.FromSame Std.U32) residual

/-- [lt_stateful_returns::inner_acquire_helper]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 281:0-283:1 -/
def inner_acquire_helper (lock : Lock) : Result Guard := do
  acquire lock

/-- [lt_stateful_returns::outer_nested_helper]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 286:0-288:1
    Visibility: public -/
def outer_nested_helper (lock : Lock) : Result Guard := do
  inner_acquire_helper lock

/-- [lt_stateful_returns::guard_in_option]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 295:0-301:1
    Visibility: public -/
def guard_in_option
  (lock : Lock) (present : Bool) : Result (Option Guard) := do
  if present
  then let g ← acquire lock
       ok (some g)
  else ok none

/-- [lt_stateful_returns::guard_in_result]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 320:0-326:1
    Visibility: public -/
def guard_in_result
  (lock : Lock) (ok1 : Bool) : Result (core.result.Result Guard Std.U32) := do
  if ok1
  then let g ← acquire lock
       ok (core.result.Result.Ok g)
  else ok (core.result.Result.Err 57005#u32)

/-- [lt_stateful_returns::guard_in_tuple]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 333:0-336:1
    Visibility: public -/
def guard_in_tuple (lock : Lock) : Result (Guard × Std.U32) := do
  let g ← acquire lock
  ok (g, 42#u32)

/-- [lt_stateful_returns::replace_guard_before_return]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 345:0-349:1
    Visibility: public -/
def replace_guard_before_return
  (first : Lock) (second : Lock) : Result Guard := do
  let _ ← acquire first
  acquire second

/-- [lt_stateful_returns::if_expr_tail_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 369:0-375:1
    Visibility: public -/
def if_expr_tail_guard (lock : Lock) (left : Bool) : Result Guard := do
  if left
  then acquire lock
  else acquire lock

/-- [lt_stateful_returns::match_expr_tail_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 382:0-387:1
    Visibility: public -/
def match_expr_tail_guard (lock : Lock) (mode : Std.U8) : Result Guard := do
  match mode with
  | 0#uscalar => acquire lock
  | _ => acquire lock

/-- [lt_stateful_returns::guard_after_computation]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 395:0-398:1
    Visibility: public -/
def guard_after_computation
  (lock : Lock) (x : Std.U32) : Result (Guard × Std.U32) := do
  let y ← lift (core.num.U32.wrapping_add x 1#u32)
  let g ← acquire lock
  ok (g, y)

/-- [lt_stateful_returns::loop_break_with_guard]: loop body 0:
    Source: 'tests/src/lt-stateful-returns.rs', lines 415:4-420:5
    Visibility: public -/
@[rust_loop_body]
def loop_break_with_guard_loop.body
  (retries : Std.U32) (count : Std.U32) :
  Result (ControlFlow Std.U32 Unit)
  := do
  if count >= retries
  then ok (done ())
  else let count1 ← count + 1#u32
       ok (cont count1)

/-- [lt_stateful_returns::loop_break_with_guard]: loop 0:
    Source: 'tests/src/lt-stateful-returns.rs', lines 415:4-420:5
    Visibility: public -/
@[rust_loop]
def loop_break_with_guard_loop
  (retries : Std.U32) (count : Std.U32) : Result Unit := do
  loop
    (fun count1 => loop_break_with_guard_loop.body retries count1)
    count

/-- [lt_stateful_returns::loop_break_with_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 413:0-421:1
    Visibility: public -/
def loop_break_with_guard
  (lock : Lock) (retries : Std.U32) : Result Guard := do
  loop_break_with_guard_loop retries 0#u32
  acquire lock

/-- [lt_stateful_returns::nested_option_try_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 430:0-433:1
    Visibility: public -/
def nested_option_try_guard
  (maybe_lock : Option (Option Lock)) : Result (Option Guard) := do
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch maybe_lock
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let cf1 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch val
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let g ← acquire val1
      ok (some g)
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        Guard residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      Guard residual

/-- [lt_stateful_returns::acquire_with_status]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 442:0-448:1 -/
def acquire_with_status
  (lock : Lock) (ok1 : Bool) : Result (core.result.Result Guard Std.U32) := do
  if ok1
  then let g ← acquire lock
       ok (core.result.Result.Ok g)
  else ok (core.result.Result.Err 1#u32)

/-- [lt_stateful_returns::call_acquire_with_status]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 461:0-464:1
    Visibility: public -/
def call_acquire_with_status
  (lock : Lock) (ok1 : Bool) : Result (core.result.Result Guard Std.U32) := do
  let r ← acquire_with_status lock ok1
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    ok (core.result.Result.Ok val)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Guard (core.convert.FromSame Std.U32) residual

/-- [lt_stateful_returns::peek_then_return_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 474:0-478:1
    Visibility: public -/
def peek_then_return_guard (lock : Lock) : Result Guard := do
  let g ← acquire lock
  let _ ← peek g
  ok g

/-- [lt_stateful_returns::nested_match_real_loop_return]: loop body 0:
    Source: 'tests/src/lt-stateful-returns.rs', lines 495:4-511:1
    Visibility: public -/
@[rust_loop_body]
def nested_match_real_loop_return_loop.body
  (lock : Lock) (iterations : Std.U32) (mode : Std.U8) (count : Std.U32) :
  Result (ControlFlow (Std.U8 × Std.U32) Guard)
  := do
  match mode with
  | 0#uscalar =>
    if count >= iterations
    then let g ← acquire lock
         ok (done g)
    else let count1 ← count + 1#u32
         ok (cont (0#u8, count1))
  | _ =>
    let count1 ← count + 1#u32
    if count1 >= iterations
    then let g ← acquire lock
         ok (done g)
    else ok (cont (mode, count1))

/-- [lt_stateful_returns::nested_match_real_loop_return]: loop 0:
    Source: 'tests/src/lt-stateful-returns.rs', lines 495:4-511:1
    Visibility: public -/
@[rust_loop]
def nested_match_real_loop_return_loop
  (mode : Std.U8) (lock : Lock) (iterations : Std.U32) (count : Std.U32) :
  Result Guard
  := do
  loop
    (fun (mode1, count1) => nested_match_real_loop_return_loop.body lock
      iterations mode1 count1)
    (mode, count)

/-- [lt_stateful_returns::nested_match_real_loop_return]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 493:0-511:1
    Visibility: public -/
@[reducible]
def nested_match_real_loop_return
  (lock : Lock) (mode : Std.U8) (iterations : Std.U32) : Result Guard := do
  nested_match_real_loop_return_loop mode lock iterations 0#u32

/-- [lt_stateful_returns::nested_match_real_loop_return_mut]: loop body 0:
    Source: 'tests/src/lt-stateful-returns.rs', lines 529:4-545:1
    Visibility: public -/
@[rust_loop_body]
def nested_match_real_loop_return_mut_loop.body
  (lock : Lock) (iterations : Std.U32) (mode : Std.U8) (count : Std.U32) :
  Result (ControlFlow (Std.U8 × Std.U32) (MutGuard × (MutGuard → Lock)))
  := do
  match mode with
  | 0#uscalar =>
    if count >= iterations
    then
      let (mg, acquire_mut_back) ← acquire_mut lock
      ok (done (mg, acquire_mut_back))
    else let count1 ← count + 1#u32
         ok (cont (0#u8, count1))
  | _ =>
    let count1 ← count + 1#u32
    if count1 >= iterations
    then
      let (mg, acquire_mut_back) ← acquire_mut lock
      ok (done (mg, acquire_mut_back))
    else ok (cont (mode, count1))

/-- [lt_stateful_returns::nested_match_real_loop_return_mut]: loop 0:
    Source: 'tests/src/lt-stateful-returns.rs', lines 529:4-545:1
    Visibility: public -/
@[rust_loop]
def nested_match_real_loop_return_mut_loop
  (mode : Std.U8) (lock : Lock) (iterations : Std.U32) (count : Std.U32) :
  Result (MutGuard × (MutGuard → Lock))
  := do
  loop
    (fun (mode1, count1) => nested_match_real_loop_return_mut_loop.body lock
      iterations mode1 count1)
    (mode, count)

/-- [lt_stateful_returns::nested_match_real_loop_return_mut]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 523:0-545:1
    Visibility: public -/
@[reducible]
def nested_match_real_loop_return_mut
  (lock : Lock) (mode : Std.U8) (iterations : Std.U32) :
  Result (MutGuard × (MutGuard → Lock))
  := do
  nested_match_real_loop_return_mut_loop mode lock iterations 0#u32

/-- [lt_stateful_returns::callee_releases_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 558:0-562:1
    Visibility: public -/
def callee_releases_guard (lock : Lock) : Result Std.U32 := do
  let g ← acquire lock
  release g
  ok 42#u32

/-- [lt_stateful_returns::caller_releases_guard]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 579:0-581:1
    Visibility: public -/
def caller_releases_guard (lock : Lock) : Result Guard := do
  acquire lock

/-- [lt_stateful_returns::manual_cleanup_both_arms]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 598:0-608:1
    Visibility: public -/
def manual_cleanup_both_arms
  (lock_a : Lock) (lock_b : Lock) (left : Bool) : Result Std.U32 := do
  if left
  then let g ← acquire lock_a
       consume_guard g
  else let g ← acquire lock_b
       release g
       ok 0#u32

/-- [lt_stateful_returns::guard_in_result_option]:
    Source: 'tests/src/lt-stateful-returns.rs', lines 623:0-629:1
    Visibility: public -/
def guard_in_result_option
  (lock : Lock) (mode : Std.U8) :
  Result (core.result.Result (Option Guard) Std.U32)
  := do
  match mode with
  | 0#uscalar => let g ← acquire lock
                 ok (core.result.Result.Ok (some g))
  | 1#uscalar => ok (core.result.Result.Ok none)
  | _ => ok (core.result.Result.Err 48879#u32)

end lt_stateful_returns
