-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_signatures]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_signatures

/-- [lt_stateful_signatures::Lock]
    Source: 'tests/src/lt-stateful-signatures.rs', lines 102:0-104:1
    Visibility: public -/
axiom Lock (T : Type) : Type

/-- [lt_stateful_signatures::ReadGuard]
    Source: 'tests/src/lt-stateful-signatures.rs', lines 110:0-112:1
    Visibility: public -/
axiom ReadGuard (T : Type) : Type

/-- [lt_stateful_signatures::WriteGuard]
    Source: 'tests/src/lt-stateful-signatures.rs', lines 118:0-120:1
    Visibility: public -/
axiom WriteGuard (T : Type) : Type

/-- [lt_stateful_signatures::{lt_stateful_signatures::Lock<T>}::new]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 124:4-126:5
    Visibility: public -/
axiom Lock.new {T : Type} : T → Result (Lock T)

/-- [lt_stateful_signatures::{lt_stateful_signatures::Lock<T>}::read]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 131:4-133:5
    Visibility: public -/
axiom Lock.read {T : Type} : Lock T → Result (ReadGuard T)

/-- [lt_stateful_signatures::{lt_stateful_signatures::Lock<T>}::write]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 138:4-140:5
    Visibility: public -/
axiom Lock.write
  {T : Type} : Lock T → Result ((WriteGuard T) × (WriteGuard T → Unit))

/-- [lt_stateful_signatures::{lt_stateful_signatures::Lock<T>}::try_read]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 145:4-147:5
    Visibility: public -/
axiom Lock.try_read {T : Type} : Lock T → Result (Option (ReadGuard T))

/-- [lt_stateful_signatures::{lt_stateful_signatures::Lock<T>}::try_write]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 152:4-154:5
    Visibility: public -/
axiom Lock.try_write
  {T : Type} :
  Lock T → Result ((Option (WriteGuard T)) × (Option (WriteGuard T) →
    Unit))

/-- [lt_stateful_signatures::{lt_stateful_signatures::Lock<T>}::get_mut]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 160:4-162:5
    Visibility: public -/
axiom Lock.get_mut {T : Type} : Lock T → Result (T × (T → Lock T))

/-- [lt_stateful_signatures::{lt_stateful_signatures::Lock<T>}::acquire_exclusive]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 175:4-177:5
    Visibility: public -/
axiom Lock.acquire_exclusive
  {T : Type} : Lock T → Result ((WriteGuard T) × (WriteGuard T → Lock T))

/-- [lt_stateful_signatures::{lt_stateful_signatures::Lock<T>}::acquire_exclusive_counting]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 186:4-191:5
    Visibility: public -/
axiom Lock.acquire_exclusive_counting
  {T : Type} :
  Lock T → Std.U32 → Result ((WriteGuard T) × (WriteGuard T → Lock T) ×
    Std.U32)

/-- [lt_stateful_signatures::{lt_stateful_signatures::ReadGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 197:4-199:5
    Visibility: public -/
axiom ReadGuard.get {T : Type} : ReadGuard T → Result T

/-- [lt_stateful_signatures::{lt_stateful_signatures::ReadGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 206:4-206:27
    Visibility: public -/
axiom ReadGuard.release {T : Type} : ReadGuard T → Result Unit

/-- [lt_stateful_signatures::{lt_stateful_signatures::WriteGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 212:4-214:5
    Visibility: public -/
axiom WriteGuard.get {T : Type} : WriteGuard T → Result T

/-- [lt_stateful_signatures::{lt_stateful_signatures::WriteGuard<'a, T>}::get_mut]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 222:4-224:5
    Visibility: public -/
axiom WriteGuard.get_mut
  {T : Type} :
  WriteGuard T → Result (T × (T → WriteGuard T) × (WriteGuard T →
    WriteGuard T))

/-- [lt_stateful_signatures::{lt_stateful_signatures::WriteGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 229:4-229:27
    Visibility: public -/
axiom WriteGuard.release {T : Type} : WriteGuard T → Result (WriteGuard T)

/-- [lt_stateful_signatures::{lt_stateful_signatures::WriteGuard<'a, T>}::downgrade]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 243:4-245:5
    Visibility: public -/
axiom WriteGuard.downgrade
  {T : Type} : WriteGuard T → Result ((ReadGuard T) × (WriteGuard T))

/-- [lt_stateful_signatures::minimal_write_acquire_release]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 250:0-253:1
    Visibility: public -/
def minimal_write_acquire_release
  {T : Type} (lock : Lock T) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let _ ← WriteGuard.release guard
  ok ()

/-- [lt_stateful_signatures::minimal_write_acquire_release_named]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 263:0-266:1
    Visibility: public -/
def minimal_write_acquire_release_named
  {T : Type} (lock : Lock T) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let _ ← WriteGuard.release guard
  ok ()

/-- [lt_stateful_signatures::minimal_write_acquire_release_trailing_comma]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 271:0-274:1
    Visibility: public -/
def minimal_write_acquire_release_trailing_comma
  {T : Type} (lock : Lock T) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let _ ← WriteGuard.release guard
  ok ()

/-- [lt_stateful_signatures::unannotated_write_acquire_release]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 283:0-286:1
    Visibility: public -/
def unannotated_write_acquire_release
  {T : Type} (lock : Lock T) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let _ ← WriteGuard.release guard
  ok ()

/-- [lt_stateful_signatures::minimal_read_acquire_release]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 290:0-293:1
    Visibility: public -/
def minimal_read_acquire_release {T : Type} (lock : Lock T) : Result Unit := do
  let guard ← Lock.read lock
  ReadGuard.release guard

/-- [lt_stateful_signatures::try_write_acquire_release]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 298:0-306:1
    Visibility: public -/
def try_write_acquire_release {T : Type} (lock : Lock T) : Result Bool := do
  let (o, _) ← Lock.try_write lock
  match o with
  | none => ok false
  | some guard => let _ ← WriteGuard.release guard
                  ok true

/-- [lt_stateful_signatures::try_read_acquire_release]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 310:0-318:1
    Visibility: public -/
def try_read_acquire_release {T : Type} (lock : Lock T) : Result Bool := do
  let o ← Lock.try_read lock
  match o with
  | none => ok false
  | some guard => ReadGuard.release guard
                  ok true

/-- [lt_stateful_signatures::try_write_option_held_before_match]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 327:0-337:1
    Visibility: public -/
def try_write_option_held_before_match
  {T : Type} (lock : Lock T) (unrelated : Std.I32) : Result Std.I32 := do
  let (maybe_guard, _) ← Lock.try_write lock
  let doubled ← unrelated * 2#i32
  match maybe_guard with
  | none => ok doubled
  | some guard => let _ ← WriteGuard.release guard
                  ok doubled

/-- [lt_stateful_signatures::read_guard_deref_copy]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 342:0-347:1
    Visibility: public -/
def read_guard_deref_copy (lock : Lock Std.I32) : Result Std.I32 := do
  let guard ← Lock.read lock
  let value ← ReadGuard.get guard
  ReadGuard.release guard
  ok value

/-- [lt_stateful_signatures::write_guard_deref_shared_copy]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 352:0-357:1
    Visibility: public -/
def write_guard_deref_shared_copy (lock : Lock Std.I32) : Result Std.I32 := do
  let (guard, _) ← Lock.write lock
  let value ← WriteGuard.get guard
  let _ ← WriteGuard.release guard
  ok value

/-- [lt_stateful_signatures::write_guard_deref_mut_set]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 362:0-366:1
    Visibility: public -/
def write_guard_deref_mut_set (lock : Lock Std.I32) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let (_, get_mut_back, _) ← WriteGuard.get_mut guard
  let guard1 := get_mut_back 42#i32
  let _ ← WriteGuard.release guard1
  ok ()

/-- [lt_stateful_signatures::write_guard_deref_mut_repeated]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 373:0-379:1
    Visibility: public -/
def write_guard_deref_mut_repeated (lock : Lock Std.I32) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let (_, get_mut_back, _) ← WriteGuard.get_mut guard
  let guard1 := get_mut_back 1#i32
  let (_, get_mut_back1, _) ← WriteGuard.get_mut guard1
  let guard2 := get_mut_back1 2#i32
  let (i, get_mut_back2, _) ← WriteGuard.get_mut guard2
  let i1 ← i + 3#i32
  let guard3 := get_mut_back2 i1
  let _ ← WriteGuard.release guard3
  ok ()

/-- [lt_stateful_signatures::write_guard_get_mut_unused]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 389:0-393:1
    Visibility: public -/
def write_guard_get_mut_unused {T : Type} (lock : Lock T) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let (t, get_mut_back, _) ← WriteGuard.get_mut guard
  let guard1 := get_mut_back t
  let _ ← WriteGuard.release guard1
  ok ()

/-- [lt_stateful_signatures::write_guard_interleaved_shared_and_mut]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 401:0-408:1
    Visibility: public -/
def write_guard_interleaved_shared_and_mut
  (lock : Lock Std.I32) : Result Std.I32 := do
  let (guard, _) ← Lock.write lock
  let _ ← WriteGuard.get guard
  let (_, get_mut_back, _) ← WriteGuard.get_mut guard
  let guard1 := get_mut_back 1#i32
  let after ← WriteGuard.get guard1
  let _ ← WriteGuard.release guard1
  ok after

/-- [lt_stateful_signatures::write_guard_downgrade_to_read]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 418:0-422:1
    Visibility: public -/
def write_guard_downgrade_to_read
  {T : Type} (lock : Lock T) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let (read_guard, _) ← WriteGuard.downgrade guard
  ReadGuard.release read_guard

/-- [lt_stateful_signatures::generic_write_replace]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 427:0-431:1
    Visibility: public -/
def generic_write_replace
  {T : Type} (lock : Lock T) (value : T) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let (_, get_mut_back, _) ← WriteGuard.get_mut guard
  let guard1 := get_mut_back value
  let _ ← WriteGuard.release guard1
  ok ()

/-- [lt_stateful_signatures::read_two_locks]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 436:0-444:1
    Visibility: public -/
def read_two_locks
  {T : Type} {U : Type} (coremarkerCopyInst : core.marker.Copy T)
  (coremarkerCopyInst1 : core.marker.Copy U) (lock1 : Lock T) (lock2 : Lock U)
  :
  Result (T × U)
  := do
  let g1 ← Lock.read lock1
  let g2 ← Lock.read lock2
  let v1 ← ReadGuard.get g1
  let v2 ← ReadGuard.get g2
  ReadGuard.release g1
  ReadGuard.release g2
  ok (v1, v2)

/-- [lt_stateful_signatures::read_two_locks_bare]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 449:0-460:1
    Visibility: public -/
def read_two_locks_bare
  {T : Type} {U : Type} (coremarkerCopyInst : core.marker.Copy T)
  (coremarkerCopyInst1 : core.marker.Copy U) (lock1 : Lock T) (lock2 : Lock U)
  :
  Result (T × U)
  := do
  let g1 ← Lock.read lock1
  let g2 ← Lock.read lock2
  let v1 ← ReadGuard.get g1
  let v2 ← ReadGuard.get g2
  ReadGuard.release g1
  ReadGuard.release g2
  ok (v1, v2)

/-- [lt_stateful_signatures::ImplLifetimeLock]
    Source: 'tests/src/lt-stateful-signatures.rs', lines 465:0-467:1
    Visibility: public -/
axiom ImplLifetimeLock (T : Type) : Type

/-- [lt_stateful_signatures::{lt_stateful_signatures::ImplLifetimeLock<'a, T>}::read_bound]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 472:4-474:5
    Visibility: public -/
axiom ImplLifetimeLock.read_bound
  {T : Type} : ImplLifetimeLock T → Result (ReadGuard T)

/-- [lt_stateful_signatures::mixed_stateful_and_pure]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 482:0-488:1
    Visibility: public -/
def mixed_stateful_and_pure
  {T : Type} (coremarkerCopyInst : core.marker.Copy T) (lock : Lock T)
  (plain : T) :
  Result (T × T)
  := do
  let guard ← Lock.read lock
  let from_lock ← ReadGuard.get guard
  ReadGuard.release guard
  ok (from_lock, plain)

/-- [lt_stateful_signatures::get_mut_without_lock]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 496:0-498:1
    Visibility: public -/
def get_mut_without_lock
  {T : Type} (lock : Lock T) : Result (T × (T → Lock T)) := do
  Lock.get_mut lock

/-- [lt_stateful_signatures::write_guard_via_mut_self_acquire]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 504:0-507:1
    Visibility: public -/
def write_guard_via_mut_self_acquire
  {T : Type} (lock : Lock T) : Result (Lock T) := do
  let (guard, acquire_exclusive_back) ← Lock.acquire_exclusive lock
  let guard1 ← WriteGuard.release guard
  ok (acquire_exclusive_back guard1)

/-- [lt_stateful_signatures::write_guard_via_mut_self_with_counter]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 514:0-520:1
    Visibility: public -/
def write_guard_via_mut_self_with_counter
  {T : Type} (lock : Lock T) (counter : Std.U32) :
  Result ((Lock T) × Std.U32)
  := do
  let (guard, acquire_exclusive_counting_back, counter1) ←
    Lock.acquire_exclusive_counting lock counter
  let guard1 ← WriteGuard.release guard
  let lock1 := acquire_exclusive_counting_back guard1
  ok (lock1, counter1)

/-- [lt_stateful_signatures::write_guard_release_only]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 526:0-529:1
    Visibility: public -/
def write_guard_release_only {T : Type} (lock : Lock T) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let _ ← WriteGuard.release guard
  ok ()

/-- [lt_stateful_signatures::read_guard_covariance]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 539:0-544:1
    Visibility: public -/
def read_guard_covariance
  {T : Type} (guard : ReadGuard T) : Result (ReadGuard T) := do
  ok guard

/-- [lt_stateful_signatures::write_guard_invariance_contrast]:
    Source: 'tests/src/lt-stateful-signatures.rs', lines 569:0-572:1
    Visibility: public -/
def write_guard_invariance_contrast
  {T : Type} (lock : Lock T) : Result Unit := do
  let (guard, _) ← Lock.write lock
  let _ ← WriteGuard.release guard
  ok ()

end lt_stateful_signatures
