-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_pass_backend_failures]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace lt_stateful_pass_backend_failures

/-- [lt_stateful_pass_backend_failures::constrain]:
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 25:0-30:1 -/
def constrain
  {F : Type} (coreopsfunctionFnFTupleMutI32MutI32Inst : core.ops.function.Fn F
  Std.I32 Std.I32) (f : F) :
  Result F
  := do
  ok f

/-- [lt_stateful_pass_backend_failures::closure_backward_borrow_once::closure]
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 33:37-33:68 -/
@[reducible]
def closure_backward_borrow_once.closure := Unit

/-- [lt_stateful_pass_backend_failures::closure_backward_borrow_once::{impl core::ops::function::Fn<(&'_ mut i32,), &'_ mut i32> for lt_stateful_pass_backend_failures::closure_backward_borrow_once::closure}::call]:
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 33:37-33:68 -/
def
  closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32.call
  (c : closure_backward_borrow_once.closure) (tupled_args : Std.I32) :
  Result (Std.I32 × (Std.I32 → Std.I32))
  := do
  ok (tupled_args, fun tupled_args1 => tupled_args1)

/-- [lt_stateful_pass_backend_failures::closure_backward_borrow_once::{impl core::ops::function::FnMut<(&'_ mut i32,), &'_ mut i32> for lt_stateful_pass_backend_failures::closure_backward_borrow_once::closure}::call_mut]:
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 33:37-33:68 -/
def
  closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnMutTupleMutI32MutI32.call_mut
  (state : closure_backward_borrow_once.closure) (args : Std.I32) :
  Result (Std.I32 × (Std.I32 → Std.I32) ×
    closure_backward_borrow_once.closure)
  := do
  let (i, call_back) ←
    closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32.call
      state args
  ok (i, call_back, state)

/-- [lt_stateful_pass_backend_failures::closure_backward_borrow_once::{impl core::ops::function::FnOnce<(&'_ mut i32,), &'_ mut i32> for lt_stateful_pass_backend_failures::closure_backward_borrow_once::closure}::call_once]:
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 33:37-33:68 -/
def
  closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnOnceTupleMutI32MutI32.call_once
  (c : closure_backward_borrow_once.closure) (i : Std.I32) :
  Result (Std.I32 × (Std.I32 → Std.I32))
  := do
  let (i1, call_mut_back, _) ←
    closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnMutTupleMutI32MutI32.call_mut
      c i
  ok (i1, call_mut_back)

/-- Trait implementation: [lt_stateful_pass_backend_failures::closure_backward_borrow_once::{impl core::ops::function::FnOnce<(&'_ mut i32,), &'_ mut i32> for lt_stateful_pass_backend_failures::closure_backward_borrow_once::closure}]
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 33:37-33:68 -/
@[reducible]
def
  closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnOnceTupleMutI32MutI32
  : core.ops.function.FnOnce closure_backward_borrow_once.closure Std.I32
  Std.I32 := {
  call_once :=
    closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnOnceTupleMutI32MutI32.call_once
}

/-- Trait implementation: [lt_stateful_pass_backend_failures::closure_backward_borrow_once::{impl core::ops::function::FnMut<(&'_ mut i32,), &'_ mut i32> for lt_stateful_pass_backend_failures::closure_backward_borrow_once::closure}]
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 33:37-33:68 -/
@[reducible]
def
  closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnMutTupleMutI32MutI32
  : core.ops.function.FnMut closure_backward_borrow_once.closure Std.I32
  Std.I32 := {
  FnOnceInst :=
    closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnOnceTupleMutI32MutI32
  call_mut :=
    closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnMutTupleMutI32MutI32.call_mut
}

/-- Trait implementation: [lt_stateful_pass_backend_failures::closure_backward_borrow_once::{impl core::ops::function::Fn<(&'_ mut i32,), &'_ mut i32> for lt_stateful_pass_backend_failures::closure_backward_borrow_once::closure}]
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 33:37-33:68 -/
@[reducible]
def
  closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32
  : core.ops.function.Fn closure_backward_borrow_once.closure Std.I32 Std.I32
  := {
  FnMutInst :=
    closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnMutTupleMutI32MutI32
  call :=
    closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32.call
}

/-- [lt_stateful_pass_backend_failures::closure_backward_borrow_once]:
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 32:0-37:1
    Visibility: public -/
def closure_backward_borrow_once
  (x : Std.I32) : Result (Std.I32 × Std.I32) := do
  let identity_closure ←
    constrain
      closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32
      ()
  let (r, call_back) ←
    closure_backward_borrow_once.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32.call
      identity_closure x
  let r1 ← r + 1#i32
  let x1 := call_back r1
  ok (x1, x1)

/-- [lt_stateful_pass_backend_failures::closure_backward_borrow_twice::closure]
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 40:37-40:68 -/
@[reducible]
def closure_backward_borrow_twice.closure := Unit

/-- [lt_stateful_pass_backend_failures::closure_backward_borrow_twice::{impl core::ops::function::Fn<(&'_ mut i32,), &'_ mut i32> for lt_stateful_pass_backend_failures::closure_backward_borrow_twice::closure}::call]:
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 40:37-40:68 -/
def
  closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32.call
  (c : closure_backward_borrow_twice.closure) (tupled_args : Std.I32) :
  Result (Std.I32 × (Std.I32 → Std.I32))
  := do
  ok (tupled_args, fun tupled_args1 => tupled_args1)

/-- [lt_stateful_pass_backend_failures::closure_backward_borrow_twice::{impl core::ops::function::FnMut<(&'_ mut i32,), &'_ mut i32> for lt_stateful_pass_backend_failures::closure_backward_borrow_twice::closure}::call_mut]:
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 40:37-40:68 -/
def
  closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnMutTupleMutI32MutI32.call_mut
  (state : closure_backward_borrow_twice.closure) (args : Std.I32) :
  Result (Std.I32 × (Std.I32 → Std.I32) ×
    closure_backward_borrow_twice.closure)
  := do
  let (i, call_back) ←
    closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32.call
      state args
  ok (i, call_back, state)

/-- [lt_stateful_pass_backend_failures::closure_backward_borrow_twice::{impl core::ops::function::FnOnce<(&'_ mut i32,), &'_ mut i32> for lt_stateful_pass_backend_failures::closure_backward_borrow_twice::closure}::call_once]:
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 40:37-40:68 -/
def
  closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnOnceTupleMutI32MutI32.call_once
  (c : closure_backward_borrow_twice.closure) (i : Std.I32) :
  Result (Std.I32 × (Std.I32 → Std.I32))
  := do
  let (i1, call_mut_back, _) ←
    closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnMutTupleMutI32MutI32.call_mut
      c i
  ok (i1, call_mut_back)

/-- Trait implementation: [lt_stateful_pass_backend_failures::closure_backward_borrow_twice::{impl core::ops::function::FnOnce<(&'_ mut i32,), &'_ mut i32> for lt_stateful_pass_backend_failures::closure_backward_borrow_twice::closure}]
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 40:37-40:68 -/
@[reducible]
def
  closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnOnceTupleMutI32MutI32
  : core.ops.function.FnOnce closure_backward_borrow_twice.closure Std.I32
  Std.I32 := {
  call_once :=
    closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnOnceTupleMutI32MutI32.call_once
}

/-- Trait implementation: [lt_stateful_pass_backend_failures::closure_backward_borrow_twice::{impl core::ops::function::FnMut<(&'_ mut i32,), &'_ mut i32> for lt_stateful_pass_backend_failures::closure_backward_borrow_twice::closure}]
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 40:37-40:68 -/
@[reducible]
def
  closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnMutTupleMutI32MutI32
  : core.ops.function.FnMut closure_backward_borrow_twice.closure Std.I32
  Std.I32 := {
  FnOnceInst :=
    closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnOnceTupleMutI32MutI32
  call_mut :=
    closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnMutTupleMutI32MutI32.call_mut
}

/-- Trait implementation: [lt_stateful_pass_backend_failures::closure_backward_borrow_twice::{impl core::ops::function::Fn<(&'_ mut i32,), &'_ mut i32> for lt_stateful_pass_backend_failures::closure_backward_borrow_twice::closure}]
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 40:37-40:68 -/
@[reducible]
def
  closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32
  : core.ops.function.Fn closure_backward_borrow_twice.closure Std.I32 Std.I32
  := {
  FnMutInst :=
    closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnMutTupleMutI32MutI32
  call :=
    closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32.call
}

/-- [lt_stateful_pass_backend_failures::closure_backward_borrow_twice]:
    Source: 'tests/src/lt-stateful-pass-backend-failures.rs', lines 39:0-46:1
    Visibility: public -/
def closure_backward_borrow_twice
  (x : Std.I32) : Result (Std.I32 × Std.I32) := do
  let identity_closure ←
    constrain
      closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32
      ()
  let (r1, call_back) ←
    closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32.call
      identity_closure x
  let r11 ← r1 + 1#i32
  let x1 := call_back r11
  let (r2, call_back1) ←
    closure_backward_borrow_twice.closure.Insts.CoreOpsFunctionFnTupleMutI32MutI32.call
      identity_closure x1
  let r21 ← r2 + 1#i32
  let x2 := call_back1 r21
  ok (x2, x2)

end lt_stateful_pass_backend_failures
