-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_explicit_drop_known_failures]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_explicit_drop_known_failures

/-- [core::mem::drop]:
    Source: '/rustc/library/core/src/mem/mod.rs', lines 1000:0-1002:24
    Name pattern: [core::mem::drop]
    Visibility: public -/
@[rust_fun "core::mem::drop"]
axiom core.mem.drop {T : Type} : T → Result Unit

/-- [lt_stateful_explicit_drop_known_failures::Lock]
    Source: 'tests/src/lt-stateful-explicit-drop-known-failures.rs', lines 10:0-12:1
    Visibility: public -/
axiom Lock (T : Type) : Type

/-- [lt_stateful_explicit_drop_known_failures::WriteGuard]
    Source: 'tests/src/lt-stateful-explicit-drop-known-failures.rs', lines 15:0-17:1
    Visibility: public -/
axiom WriteGuard (T : Type) : Type

/-- [lt_stateful_explicit_drop_known_failures::{lt_stateful_explicit_drop_known_failures::Lock<T>}::write]:
    Source: 'tests/src/lt-stateful-explicit-drop-known-failures.rs', lines 22:4-24:5
    Visibility: public -/
axiom Lock.write
  {T : Type} :
  Lock T → Result ((WriteGuard T) × (WriteGuard T → Result Unit))

/-- [lt_stateful_explicit_drop_known_failures::{lt_stateful_explicit_drop_known_failures::WriteGuard<'_0, T>}::get]:
    Source: 'tests/src/lt-stateful-explicit-drop-known-failures.rs', lines 29:4-31:5
    Visibility: public -/
axiom WriteGuard.get {T : Type} : WriteGuard T → Result T

/-- [lt_stateful_explicit_drop_known_failures::explicit_drop]:
    Source: 'tests/src/lt-stateful-explicit-drop-known-failures.rs', lines 61:0-65:1
    Visibility: public -/
def explicit_drop (lock : Lock Std.I32) : Result Unit := do
  let p ← Lock.write lock
  let (guard, write_back) := p
  let _ ← WriteGuard.get guard
  let guard1 ← core.mem.drop guard
  write_back guard1

end lt_stateful_explicit_drop_known_failures
