-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_concurrency_backend_failures]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_concurrency_backend_failures

/-- [lt_stateful_concurrency_backend_failures::JoinHandle]
    Source: 'tests/src/lt-stateful-concurrency-backend-failures.rs', lines 24:0-26:1
    Visibility: public -/
axiom JoinHandle (T : Type) : Type

/-- [lt_stateful_concurrency_backend_failures::{lt_stateful_concurrency_backend_failures::JoinHandle<T>}::join]:
    Source: 'tests/src/lt-stateful-concurrency-backend-failures.rs', lines 30:4-32:5
    Visibility: public -/
axiom JoinHandle.join {T : Type} : JoinHandle T → Result T

/-- [lt_stateful_concurrency_backend_failures::spawn]:
    Source: 'tests/src/lt-stateful-concurrency-backend-failures.rs', lines 36:0-41:1
    Visibility: public -/
axiom spawn
  {F : Type} {T : Type} (coreopsfunctionFnOnceFTupleTInst :
  core.ops.function.FnOnce F Unit T) :
  F → Result (JoinHandle T)

/-- [lt_stateful_concurrency_backend_failures::spawn_capturing_mut_borrow::closure]
    Source: 'tests/src/lt-stateful-concurrency-backend-failures.rs', lines 47:23-50:5 -/
@[reducible]
def spawn_capturing_mut_borrow.closure := Std.I32

/-- [lt_stateful_concurrency_backend_failures::spawn_capturing_mut_borrow::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency_backend_failures::spawn_capturing_mut_borrow::closure<'_0>}::call_once]:
    Source: 'tests/src/lt-stateful-concurrency-backend-failures.rs', lines 47:23-50:5 -/
def
  spawn_capturing_mut_borrow.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
  (c : spawn_capturing_mut_borrow.closure) (_ : Unit) :
  Result (Std.I32 × spawn_capturing_mut_borrow.closure)
  := do
  let i ← c + 1#i32
  ok (i, i)

/-- Trait implementation: [lt_stateful_concurrency_backend_failures::spawn_capturing_mut_borrow::{impl core::ops::function::FnOnce<(), i32> for lt_stateful_concurrency_backend_failures::spawn_capturing_mut_borrow::closure<'_0>}]
    Source: 'tests/src/lt-stateful-concurrency-backend-failures.rs', lines 47:23-50:5 -/
@[reducible]
def spawn_capturing_mut_borrow.closure.Insts.CoreOpsFunctionFnOnceTupleI32 :
  core.ops.function.FnOnce spawn_capturing_mut_borrow.closure Unit Std.I32 := {
  call_once :=
    spawn_capturing_mut_borrow.closure.Insts.CoreOpsFunctionFnOnceTupleI32.call_once
}

/-- [lt_stateful_concurrency_backend_failures::spawn_capturing_mut_borrow]:
    Source: 'tests/src/lt-stateful-concurrency-backend-failures.rs', lines 46:0-52:1
    Visibility: public -/
def spawn_capturing_mut_borrow
  (x : Std.I32) : Result (Std.I32 × Std.I32) := do
  let (handle, c) ←
    spawn
      spawn_capturing_mut_borrow.closure.Insts.CoreOpsFunctionFnOnceTupleI32 x
  let i ← JoinHandle.join handle
  ok (i, c)

end lt_stateful_concurrency_backend_failures
