-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [lt_stateful_loop_backend_failures]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace lt_stateful_loop_backend_failures

/-- [core::iter::traits::iterator::Iterator::sum]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 3669:4-3672:35
    Name pattern: [core::iter::traits::iterator::Iterator::sum]
    Visibility: public -/
@[trait_default, rust_fun "core::iter::traits::iterator::Iterator::sum"]
axiom core.iter.traits.iterator.Iterator.sum.default
  {Self : Type} {S : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item) (accumSumInst :
  core.iter.traits.accum.Sum S Clause0_Item) :
  Self → Result S

/-- [core::iter::traits::iterator::Iterator::map]:
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 831:4-834:34
    Name pattern: [core::iter::traits::iterator::Iterator::map]
    Visibility: public -/
@[trait_default, rust_fun "core::iter::traits::iterator::Iterator::map"]
axiom core.iter.traits.iterator.Iterator.map.default
  {Self : Type} {B : Type} {F : Type} {Clause0_Item : Type} (IteratorInst :
  core.iter.traits.iterator.Iterator Self Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBInst : core.ops.function.FnMut F
  Clause0_Item B) :
  Self → F → Result (core.iter.adapters.map.Map Self F)

/-- [core::iter::adapters::map::{impl core::iter::traits::iterator::Iterator<B> for core::iter::adapters::map::Map<I, F>}::next]:
    Source: '/rustc/library/core/src/iter/adapters/map.rs', lines 106:4-106:35
    Name pattern: [core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::next]
    Visibility: public -/
@[rust_fun
  "core::iter::adapters::map::{core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>}::next"]
axiom core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next
  {B : Type} {I : Type} {F : Type} {Clause0_Item : Type}
  (traitsiteratorIteratorInst : core.iter.traits.iterator.Iterator I
  Clause0_Item) (opsfunctionFnMutFTupleClause0_ItemBInst :
  core.ops.function.FnMut F Clause0_Item B) :
  core.iter.adapters.map.Map I F → Result ((Option B) ×
    (core.iter.adapters.map.Map I F))

/-- Trait implementation: [core::iter::adapters::map::{impl core::iter::traits::iterator::Iterator<B> for core::iter::adapters::map::Map<I, F>}]
    Source: '/rustc/library/core/src/iter/adapters/map.rs', lines 99:0-101:27
    Name pattern: [core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>] -/
@[reducible, rust_trait_impl
  "core::iter::traits::iterator::Iterator<core::iter::adapters::map::Map<@I, @F>, @B>"]
impl_def core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator {B :
  Type} {I : Type} {F : Type} {Clause0_Item : Type} (traitsiteratorIteratorInst
  : core.iter.traits.iterator.Iterator I Clause0_Item)
  (opsfunctionFnMutFTupleClause0_ItemBInst : core.ops.function.FnMut F
  Clause0_Item B) : core.iter.traits.iterator.Iterator
  (core.iter.adapters.map.Map I F) B := {
  next := core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator.next
    traitsiteratorIteratorInst opsfunctionFnMutFTupleClause0_ItemBInst
  map := fun {B1 : Type} {F1 : Type} (opsfunctionFnMutPTupleBPInst :
    core.ops.function.FnMut F1 B B1) =>
    core.iter.traits.iterator.Iterator.map.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    traitsiteratorIteratorInst opsfunctionFnMutFTupleClause0_ItemBInst)
    opsfunctionFnMutPTupleBPInst
  sum := fun {S : Type} (accumSumInst : core.iter.traits.accum.Sum S B) =>
    core.iter.traits.iterator.Iterator.sum.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    traitsiteratorIteratorInst opsfunctionFnMutFTupleClause0_ItemBInst)
    accumSumInst
}

/-- [core::iter::traits::accum::{impl core::iter::traits::accum::Sum<i32> for i32}::sum]:
    Source: '/rustc/library/core/src/iter/traits/accum.rs', lines 51:12-51:59
    Name pattern: [core::iter::traits::accum::{core::iter::traits::accum::Sum<i32, i32>}::sum]
    Visibility: public -/
@[rust_fun
  "core::iter::traits::accum::{core::iter::traits::accum::Sum<i32, i32>}::sum"]
axiom I32.Insts.CoreIterTraitsAccumSumI32.sum
  {I : Type} (iteratorIteratorII32Inst : core.iter.traits.iterator.Iterator I
  Std.I32) :
  I → Result Std.I32

/-- Trait implementation: [core::iter::traits::accum::{impl core::iter::traits::accum::Sum<i32> for i32}]
    Source: '/rustc/library/core/src/iter/traits/accum.rs', lines 50:8-50:23
    Name pattern: [core::iter::traits::accum::Sum<i32, i32>] -/
@[reducible, rust_trait_impl "core::iter::traits::accum::Sum<i32, i32>"]
def I32.Insts.CoreIterTraitsAccumSumI32 : core.iter.traits.accum.Sum Std.I32
  Std.I32 := {
  sum := fun {I : Type} (iteratorIteratorPI32Inst :
    core.iter.traits.iterator.Iterator I Std.I32) =>
    I32.Insts.CoreIterTraitsAccumSumI32.sum iteratorIteratorPI32Inst
}

/-- [lt_stateful_loop_backend_failures::Lock]
    Source: 'tests/src/lt-stateful-loop-backend-failures.rs', lines 16:0-18:1
    Visibility: public -/
axiom Lock (T : Type) : Type

/-- [lt_stateful_loop_backend_failures::WriteGuard]
    Source: 'tests/src/lt-stateful-loop-backend-failures.rs', lines 21:0-23:1
    Visibility: public -/
axiom WriteGuard (T : Type) : Type

/-- [lt_stateful_loop_backend_failures::{lt_stateful_loop_backend_failures::Lock<T>}::write]:
    Source: 'tests/src/lt-stateful-loop-backend-failures.rs', lines 27:4-29:5
    Visibility: public -/
axiom Lock.write
  {T : Type} : Lock T → Result ((WriteGuard T) × (WriteGuard T → Unit))

/-- [lt_stateful_loop_backend_failures::{lt_stateful_loop_backend_failures::WriteGuard<'a, T>}::get]:
    Source: 'tests/src/lt-stateful-loop-backend-failures.rs', lines 34:4-36:5
    Visibility: public -/
axiom WriteGuard.get {T : Type} : WriteGuard T → Result T

/-- [lt_stateful_loop_backend_failures::{lt_stateful_loop_backend_failures::WriteGuard<'a, T>}::get_mut]:
    Source: 'tests/src/lt-stateful-loop-backend-failures.rs', lines 39:4-41:5
    Visibility: public -/
axiom WriteGuard.get_mut
  {T : Type} :
  WriteGuard T → Result (T × (T → WriteGuard T) × (WriteGuard T →
    WriteGuard T))

/-- [lt_stateful_loop_backend_failures::{lt_stateful_loop_backend_failures::WriteGuard<'a, T>}::release]:
    Source: 'tests/src/lt-stateful-loop-backend-failures.rs', lines 44:4-44:27
    Visibility: public -/
axiom WriteGuard.release {T : Type} : WriteGuard T → Result (WriteGuard T)

/-- [lt_stateful_loop_backend_failures::iterator_adapter_sum_with_guard::closure]
    Source: 'tests/src/lt-stateful-loop-backend-failures.rs', lines 50:13-56:9 -/
@[reducible]
def iterator_adapter_sum_with_guard.closure := Lock Std.I32

/-- [lt_stateful_loop_backend_failures::iterator_adapter_sum_with_guard::{impl core::ops::function::FnMut<(u32,), i32> for lt_stateful_loop_backend_failures::iterator_adapter_sum_with_guard::closure<'_0>}::call_mut]:
    Source: 'tests/src/lt-stateful-loop-backend-failures.rs', lines 50:13-56:9 -/
def
  iterator_adapter_sum_with_guard.closure.Insts.CoreOpsFunctionFnMutTupleU32I32.call_mut
  (c : iterator_adapter_sum_with_guard.closure) (tupled_args : Std.U32) :
  Result (Std.I32 × iterator_adapter_sum_with_guard.closure)
  := do
  let (guard, _) ← Lock.write c
  let (i, get_mut_back, _) ← WriteGuard.get_mut guard
  let i1 ← i + 1#i32
  let guard1 := get_mut_back i1
  let value ← WriteGuard.get guard1
  let _ ← WriteGuard.release guard1
  let i2 ← lift (UScalar.hcast .I32 tupled_args)
  let i3 ← value + i2
  ok (i3, c)

/-- [lt_stateful_loop_backend_failures::iterator_adapter_sum_with_guard::{impl core::ops::function::FnOnce<(u32,), i32> for lt_stateful_loop_backend_failures::iterator_adapter_sum_with_guard::closure<'_0>}::call_once]:
    Source: 'tests/src/lt-stateful-loop-backend-failures.rs', lines 50:13-56:9 -/
def
  iterator_adapter_sum_with_guard.closure.Insts.CoreOpsFunctionFnOnceTupleU32I32.call_once
  (c : iterator_adapter_sum_with_guard.closure) (i : Std.U32) :
  Result Std.I32
  := do
  let (i1, _) ←
    iterator_adapter_sum_with_guard.closure.Insts.CoreOpsFunctionFnMutTupleU32I32.call_mut
      c i
  ok i1

/-- Trait implementation: [lt_stateful_loop_backend_failures::iterator_adapter_sum_with_guard::{impl core::ops::function::FnOnce<(u32,), i32> for lt_stateful_loop_backend_failures::iterator_adapter_sum_with_guard::closure<'_0>}]
    Source: 'tests/src/lt-stateful-loop-backend-failures.rs', lines 50:13-56:9 -/
@[reducible]
def
  iterator_adapter_sum_with_guard.closure.Insts.CoreOpsFunctionFnOnceTupleU32I32
  : core.ops.function.FnOnce iterator_adapter_sum_with_guard.closure Std.U32
  Std.I32 := {
  call_once :=
    iterator_adapter_sum_with_guard.closure.Insts.CoreOpsFunctionFnOnceTupleU32I32.call_once
}

/-- Trait implementation: [lt_stateful_loop_backend_failures::iterator_adapter_sum_with_guard::{impl core::ops::function::FnMut<(u32,), i32> for lt_stateful_loop_backend_failures::iterator_adapter_sum_with_guard::closure<'_0>}]
    Source: 'tests/src/lt-stateful-loop-backend-failures.rs', lines 50:13-56:9 -/
@[reducible]
def
  iterator_adapter_sum_with_guard.closure.Insts.CoreOpsFunctionFnMutTupleU32I32
  : core.ops.function.FnMut iterator_adapter_sum_with_guard.closure Std.U32
  Std.I32 := {
  FnOnceInst :=
    iterator_adapter_sum_with_guard.closure.Insts.CoreOpsFunctionFnOnceTupleU32I32
  call_mut :=
    iterator_adapter_sum_with_guard.closure.Insts.CoreOpsFunctionFnMutTupleU32I32.call_mut
}

/-- [lt_stateful_loop_backend_failures::iterator_adapter_sum_with_guard]:
    Source: 'tests/src/lt-stateful-loop-backend-failures.rs', lines 48:0-58:1
    Visibility: public -/
def iterator_adapter_sum_with_guard
  (lock : Lock Std.I32) (n : Std.U32) : Result Std.I32 := do
  let m ←
    core.iter.traits.iterator.Iterator.map.default
      (core.iter.traits.iterator.IteratorRange core.iter.range.StepU32)
      iterator_adapter_sum_with_guard.closure.Insts.CoreOpsFunctionFnMutTupleU32I32
      { start := 0#u32, «end» := n } lock
  core.iter.traits.iterator.Iterator.sum.default
    (core.iter.adapters.map.Map.Insts.CoreIterTraitsIteratorIterator
    (core.iter.traits.iterator.IteratorRange core.iter.range.StepU32)
    iterator_adapter_sum_with_guard.closure.Insts.CoreOpsFunctionFnMutTupleU32I32)
    I32.Insts.CoreIterTraitsAccumSumI32 m

end lt_stateful_loop_backend_failures
